<?php
/**
 * AddAppointmentRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.23
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Nlocascio\Mindbody;

/**
 * AddAppointmentRequestTest Class Doc Comment
 *
 * @category    Class
 * @description AddAppointmentRequest
 * @package     Nlocascio\Mindbody
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AddAppointmentRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AddAppointmentRequest"
     */
    public function testAddAppointmentRequest()
    {
    }

    /**
     * Test attribute "ApplyPayment"
     */
    public function testPropertyApplyPayment()
    {
    }

    /**
     * Test attribute "ClientId"
     */
    public function testPropertyClientId()
    {
    }

    /**
     * Test attribute "Duration"
     */
    public function testPropertyDuration()
    {
    }

    /**
     * Test attribute "Execute"
     */
    public function testPropertyExecute()
    {
    }

    /**
     * Test attribute "EndDateTime"
     */
    public function testPropertyEndDateTime()
    {
    }

    /**
     * Test attribute "GenderPreference"
     */
    public function testPropertyGenderPreference()
    {
    }

    /**
     * Test attribute "LocationId"
     */
    public function testPropertyLocationId()
    {
    }

    /**
     * Test attribute "Notes"
     */
    public function testPropertyNotes()
    {
    }

    /**
     * Test attribute "ProviderId"
     */
    public function testPropertyProviderId()
    {
    }

    /**
     * Test attribute "ResourceIds"
     */
    public function testPropertyResourceIds()
    {
    }

    /**
     * Test attribute "SendEmail"
     */
    public function testPropertySendEmail()
    {
    }

    /**
     * Test attribute "SessionTypeId"
     */
    public function testPropertySessionTypeId()
    {
    }

    /**
     * Test attribute "StaffId"
     */
    public function testPropertyStaffId()
    {
    }

    /**
     * Test attribute "StaffRequested"
     */
    public function testPropertyStaffRequested()
    {
    }

    /**
     * Test attribute "StartDateTime"
     */
    public function testPropertyStartDateTime()
    {
    }

    /**
     * Test attribute "Test"
     */
    public function testPropertyTest()
    {
    }
}
