<?php
/**
 * AppointmentTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.23
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Nlocascio\Mindbody;

/**
 * AppointmentTest Class Doc Comment
 *
 * @category    Class
 * @description Contains information about an appointment.
 * @package     Nlocascio\Mindbody
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AppointmentTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Appointment"
     */
    public function testAppointment()
    {
    }

    /**
     * Test attribute "GenderPreference"
     */
    public function testPropertyGenderPreference()
    {
    }

    /**
     * Test attribute "Duration"
     */
    public function testPropertyDuration()
    {
    }

    /**
     * Test attribute "ProviderId"
     */
    public function testPropertyProviderId()
    {
    }

    /**
     * Test attribute "Id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "Status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "StartDateTime"
     */
    public function testPropertyStartDateTime()
    {
    }

    /**
     * Test attribute "EndDateTime"
     */
    public function testPropertyEndDateTime()
    {
    }

    /**
     * Test attribute "Notes"
     */
    public function testPropertyNotes()
    {
    }

    /**
     * Test attribute "StaffRequested"
     */
    public function testPropertyStaffRequested()
    {
    }

    /**
     * Test attribute "ProgramId"
     */
    public function testPropertyProgramId()
    {
    }

    /**
     * Test attribute "SessionTypeId"
     */
    public function testPropertySessionTypeId()
    {
    }

    /**
     * Test attribute "LocationId"
     */
    public function testPropertyLocationId()
    {
    }

    /**
     * Test attribute "StaffId"
     */
    public function testPropertyStaffId()
    {
    }

    /**
     * Test attribute "ClientId"
     */
    public function testPropertyClientId()
    {
    }

    /**
     * Test attribute "FirstAppointment"
     */
    public function testPropertyFirstAppointment()
    {
    }

    /**
     * Test attribute "ClientServiceId"
     */
    public function testPropertyClientServiceId()
    {
    }

    /**
     * Test attribute "Resources"
     */
    public function testPropertyResources()
    {
    }

    /**
     * Test attribute "AddOns"
     */
    public function testPropertyAddOns()
    {
    }
}
