<?php
/**
 * CheckoutShoppingCartRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.23
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Nlocascio\Mindbody;

/**
 * CheckoutShoppingCartRequestTest Class Doc Comment
 *
 * @category    Class
 * @description CheckoutShoppingCartRequest
 * @package     Nlocascio\Mindbody
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CheckoutShoppingCartRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CheckoutShoppingCartRequest"
     */
    public function testCheckoutShoppingCartRequest()
    {
    }

    /**
     * Test attribute "CartId"
     */
    public function testPropertyCartId()
    {
    }

    /**
     * Test attribute "ClientId"
     */
    public function testPropertyClientId()
    {
    }

    /**
     * Test attribute "Test"
     */
    public function testPropertyTest()
    {
    }

    /**
     * Test attribute "Items"
     */
    public function testPropertyItems()
    {
    }

    /**
     * Test attribute "InStore"
     */
    public function testPropertyInStore()
    {
    }

    /**
     * Test attribute "CalculateTax"
     */
    public function testPropertyCalculateTax()
    {
    }

    /**
     * Test attribute "PromotionCode"
     */
    public function testPropertyPromotionCode()
    {
    }

    /**
     * Test attribute "Payments"
     */
    public function testPropertyPayments()
    {
    }

    /**
     * Test attribute "SendEmail"
     */
    public function testPropertySendEmail()
    {
    }

    /**
     * Test attribute "LocationId"
     */
    public function testPropertyLocationId()
    {
    }

    /**
     * Test attribute "Image"
     */
    public function testPropertyImage()
    {
    }

    /**
     * Test attribute "ImageFileName"
     */
    public function testPropertyImageFileName()
    {
    }

    /**
     * Test attribute "ConsumerPresent"
     */
    public function testPropertyConsumerPresent()
    {
    }

    /**
     * Test attribute "PaymentAuthenticationCallbackUrl"
     */
    public function testPropertyPaymentAuthenticationCallbackUrl()
    {
    }

    /**
     * Test attribute "TransactionIds"
     */
    public function testPropertyTransactionIds()
    {
    }

    /**
     * Test attribute "IsBillingPostalCodeRequired"
     */
    public function testPropertyIsBillingPostalCodeRequired()
    {
    }
}
