<?php
/**
 * CheckoutItemWrapperTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.23
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Nlocascio\Mindbody;

/**
 * CheckoutItemWrapperTest Class Doc Comment
 *
 * @category    Class
 * @description CheckoutItemWrapper
 * @package     Nlocascio\Mindbody
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CheckoutItemWrapperTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CheckoutItemWrapper"
     */
    public function testCheckoutItemWrapper()
    {
    }

    /**
     * Test attribute "Item"
     */
    public function testPropertyItem()
    {
    }

    /**
     * Test attribute "DiscountAmount"
     */
    public function testPropertyDiscountAmount()
    {
    }

    /**
     * Test attribute "AppointmentBookingRequests"
     */
    public function testPropertyAppointmentBookingRequests()
    {
    }

    /**
     * Test attribute "EnrollmentIds"
     */
    public function testPropertyEnrollmentIds()
    {
    }

    /**
     * Test attribute "ClassIds"
     */
    public function testPropertyClassIds()
    {
    }

    /**
     * Test attribute "CourseIds"
     */
    public function testPropertyCourseIds()
    {
    }

    /**
     * Test attribute "VisitIds"
     */
    public function testPropertyVisitIds()
    {
    }

    /**
     * Test attribute "AppointmentIds"
     */
    public function testPropertyAppointmentIds()
    {
    }

    /**
     * Test attribute "Id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "Quantity"
     */
    public function testPropertyQuantity()
    {
    }
}
