<?php
/**
 * LocationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.23
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Nlocascio\Mindbody;

/**
 * LocationTest Class Doc Comment
 *
 * @category    Class
 * @description Location
 * @package     Nlocascio\Mindbody
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LocationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Location"
     */
    public function testLocation()
    {
    }

    /**
     * Test attribute "AdditionalImageURLs"
     */
    public function testPropertyAdditionalImageURLs()
    {
    }

    /**
     * Test attribute "Address"
     */
    public function testPropertyAddress()
    {
    }

    /**
     * Test attribute "Address2"
     */
    public function testPropertyAddress2()
    {
    }

    /**
     * Test attribute "Amenities"
     */
    public function testPropertyAmenities()
    {
    }

    /**
     * Test attribute "BusinessDescription"
     */
    public function testPropertyBusinessDescription()
    {
    }

    /**
     * Test attribute "City"
     */
    public function testPropertyCity()
    {
    }

    /**
     * Test attribute "Description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "HasClasses"
     */
    public function testPropertyHasClasses()
    {
    }

    /**
     * Test attribute "Id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "Latitude"
     */
    public function testPropertyLatitude()
    {
    }

    /**
     * Test attribute "Longitude"
     */
    public function testPropertyLongitude()
    {
    }

    /**
     * Test attribute "Name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "Phone"
     */
    public function testPropertyPhone()
    {
    }

    /**
     * Test attribute "PhoneExtension"
     */
    public function testPropertyPhoneExtension()
    {
    }

    /**
     * Test attribute "PostalCode"
     */
    public function testPropertyPostalCode()
    {
    }

    /**
     * Test attribute "SiteID"
     */
    public function testPropertySiteID()
    {
    }

    /**
     * Test attribute "StateProvCode"
     */
    public function testPropertyStateProvCode()
    {
    }

    /**
     * Test attribute "Tax1"
     */
    public function testPropertyTax1()
    {
    }

    /**
     * Test attribute "Tax2"
     */
    public function testPropertyTax2()
    {
    }

    /**
     * Test attribute "Tax3"
     */
    public function testPropertyTax3()
    {
    }

    /**
     * Test attribute "Tax4"
     */
    public function testPropertyTax4()
    {
    }

    /**
     * Test attribute "Tax5"
     */
    public function testPropertyTax5()
    {
    }

    /**
     * Test attribute "TotalNumberOfRatings"
     */
    public function testPropertyTotalNumberOfRatings()
    {
    }

    /**
     * Test attribute "AverageRating"
     */
    public function testPropertyAverageRating()
    {
    }

    /**
     * Test attribute "TotalNumberOfDeals"
     */
    public function testPropertyTotalNumberOfDeals()
    {
    }
}
