<?php
/**
 * PurchaseContractRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.23
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Nlocascio\Mindbody;

/**
 * PurchaseContractRequestTest Class Doc Comment
 *
 * @category    Class
 * @description PurchaseContractRequest
 * @package     Nlocascio\Mindbody
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PurchaseContractRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PurchaseContractRequest"
     */
    public function testPurchaseContractRequest()
    {
    }

    /**
     * Test attribute "Test"
     */
    public function testPropertyTest()
    {
    }

    /**
     * Test attribute "LocationId"
     */
    public function testPropertyLocationId()
    {
    }

    /**
     * Test attribute "ClientId"
     */
    public function testPropertyClientId()
    {
    }

    /**
     * Test attribute "ContractId"
     */
    public function testPropertyContractId()
    {
    }

    /**
     * Test attribute "StartDate"
     */
    public function testPropertyStartDate()
    {
    }

    /**
     * Test attribute "FirstPaymentOccurs"
     */
    public function testPropertyFirstPaymentOccurs()
    {
    }

    /**
     * Test attribute "ClientSignature"
     */
    public function testPropertyClientSignature()
    {
    }

    /**
     * Test attribute "PromotionCode"
     */
    public function testPropertyPromotionCode()
    {
    }

    /**
     * Test attribute "CreditCardInfo"
     */
    public function testPropertyCreditCardInfo()
    {
    }

    /**
     * Test attribute "StoredCardInfo"
     */
    public function testPropertyStoredCardInfo()
    {
    }

    /**
     * Test attribute "SendNotifications"
     */
    public function testPropertySendNotifications()
    {
    }

    /**
     * Test attribute "SalesRepId"
     */
    public function testPropertySalesRepId()
    {
    }

    /**
     * Test attribute "UseDirectDebit"
     */
    public function testPropertyUseDirectDebit()
    {
    }

    /**
     * Test attribute "ConsumerPresent"
     */
    public function testPropertyConsumerPresent()
    {
    }

    /**
     * Test attribute "PaymentAuthenticationCallbackUrl"
     */
    public function testPropertyPaymentAuthenticationCallbackUrl()
    {
    }
}
