<?php
/**
 * SendPasswordResetEmailRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.23
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Nlocascio\Mindbody;

/**
 * SendPasswordResetEmailRequestTest Class Doc Comment
 *
 * @category    Class
 * @description Request to send a password reset email to a user
 * @package     Nlocascio\Mindbody
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SendPasswordResetEmailRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SendPasswordResetEmailRequest"
     */
    public function testSendPasswordResetEmailRequest()
    {
    }

    /**
     * Test attribute "UserEmail"
     */
    public function testPropertyUserEmail()
    {
    }

    /**
     * Test attribute "UserFirstName"
     */
    public function testPropertyUserFirstName()
    {
    }

    /**
     * Test attribute "UserLastName"
     */
    public function testPropertyUserLastName()
    {
    }
}
