<?php
/**
 * AddAvailabilitiesRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.50
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Nlocascio\Mindbody\Model;

/**
 * AddAvailabilitiesRequest Class Doc Comment
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 * @property bool $Test When `true`, the request ensures that its parameters are valid without affecting real data.  When `false`, the request performs as intended and may affect live client data.  (optional) Defaults to false.
 * @property int $LocationID Location of availability.  <br />Not used when IsUnavailable is `true`.
 * @property int[] $StaffIDs A list of requested staff IDs.<br />  (optional) Defaults to staff ID of user credentials. Use 0 for all.
 * @property int[] $ProgramIDs A list of program IDs.<br />  (optional) Defaults to all.  <br />Not used when IsUnavailable is true.
 * @property \DateTime $StartDateTime The start date and time of the new availabilities or unavailabilities.
 * @property \DateTime $EndDateTime The end date and time of the new availabilities or unavailabilities.
 * @property string[] $DaysOfWeek The days of the week to set.<br />  (optional) Defaults to all.
 * @property string $UnavailableDescription Description of unavalability.  <br />Only used when IsUnavailable is true.
 * @property bool $IsUnavailable When `true`, indicates that unavailability is getting added. When `false`, indicates that availability is getting added.  Default: **false**
 * @property string $PublicDisplay Sets the public display of the availability.<br /><ul><li>Show</li><li>Mask</li><li>Hide</li></ul>  (optional) Defaults to Show.
 *
 */
class AddAvailabilitiesRequest extends BaseModel
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'AddAvailabilitiesRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'Test' => 'bool',
        'LocationID' => 'int',
        'StaffIDs' => 'int[]',
        'ProgramIDs' => 'int[]',
        'StartDateTime' => '\DateTime',
        'EndDateTime' => '\DateTime',
        'DaysOfWeek' => 'string[]',
        'UnavailableDescription' => 'string',
        'IsUnavailable' => 'bool',
        'PublicDisplay' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static $swaggerFormats = [
        'Test' => null,
        'LocationID' => 'int32',
        'StaffIDs' => 'int64',
        'ProgramIDs' => 'int32',
        'StartDateTime' => 'date-time',
        'EndDateTime' => 'date-time',
        'DaysOfWeek' => null,
        'UnavailableDescription' => null,
        'IsUnavailable' => null,
        'PublicDisplay' => null
    ];


    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'Test' => 'Test',
        'LocationID' => 'LocationID',
        'StaffIDs' => 'StaffIDs',
        'ProgramIDs' => 'ProgramIDs',
        'StartDateTime' => 'StartDateTime',
        'EndDateTime' => 'EndDateTime',
        'DaysOfWeek' => 'DaysOfWeek',
        'UnavailableDescription' => 'UnavailableDescription',
        'IsUnavailable' => 'IsUnavailable',
        'PublicDisplay' => 'PublicDisplay'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'Test' => 'setTest',
        'LocationID' => 'setLocationID',
        'StaffIDs' => 'setStaffIDs',
        'ProgramIDs' => 'setProgramIDs',
        'StartDateTime' => 'setStartDateTime',
        'EndDateTime' => 'setEndDateTime',
        'DaysOfWeek' => 'setDaysOfWeek',
        'UnavailableDescription' => 'setUnavailableDescription',
        'IsUnavailable' => 'setIsUnavailable',
        'PublicDisplay' => 'setPublicDisplay'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'Test' => 'getTest',
        'LocationID' => 'getLocationID',
        'StaffIDs' => 'getStaffIDs',
        'ProgramIDs' => 'getProgramIDs',
        'StartDateTime' => 'getStartDateTime',
        'EndDateTime' => 'getEndDateTime',
        'DaysOfWeek' => 'getDaysOfWeek',
        'UnavailableDescription' => 'getUnavailableDescription',
        'IsUnavailable' => 'getIsUnavailable',
        'PublicDisplay' => 'getPublicDisplay'
    ];


    const DAYS_OF_WEEK_SUNDAY = 'Sunday';
    const DAYS_OF_WEEK_MONDAY = 'Monday';
    const DAYS_OF_WEEK_TUESDAY = 'Tuesday';
    const DAYS_OF_WEEK_WEDNESDAY = 'Wednesday';
    const DAYS_OF_WEEK_THURSDAY = 'Thursday';
    const DAYS_OF_WEEK_FRIDAY = 'Friday';
    const DAYS_OF_WEEK_SATURDAY = 'Saturday';
    const PUBLIC_DISPLAY_HIDE = 'Hide';
    const PUBLIC_DISPLAY_SHOW = 'Show';
    const PUBLIC_DISPLAY_MASK = 'Mask';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getDaysOfWeekAllowableValues(): array
    {
        return [
            self::DAYS_OF_WEEK_SUNDAY,
            self::DAYS_OF_WEEK_MONDAY,
            self::DAYS_OF_WEEK_TUESDAY,
            self::DAYS_OF_WEEK_WEDNESDAY,
            self::DAYS_OF_WEEK_THURSDAY,
            self::DAYS_OF_WEEK_FRIDAY,
            self::DAYS_OF_WEEK_SATURDAY,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getPublicDisplayAllowableValues(): array
    {
        return [
            self::PUBLIC_DISPLAY_HIDE,
            self::PUBLIC_DISPLAY_SHOW,
            self::PUBLIC_DISPLAY_MASK,
        ];
    }
    

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['Test'] = isset($data['Test']) ? $data['Test'] : null;
        $this->container['LocationID'] = isset($data['LocationID']) ? $data['LocationID'] : null;
        $this->container['StaffIDs'] = isset($data['StaffIDs']) ? $data['StaffIDs'] : null;
        $this->container['ProgramIDs'] = isset($data['ProgramIDs']) ? $data['ProgramIDs'] : null;
        $this->container['StartDateTime'] = isset($data['StartDateTime']) ? $data['StartDateTime'] : null;
        $this->container['EndDateTime'] = isset($data['EndDateTime']) ? $data['EndDateTime'] : null;
        $this->container['DaysOfWeek'] = isset($data['DaysOfWeek']) ? $data['DaysOfWeek'] : null;
        $this->container['UnavailableDescription'] = isset($data['UnavailableDescription']) ? $data['UnavailableDescription'] : null;
        $this->container['IsUnavailable'] = isset($data['IsUnavailable']) ? $data['IsUnavailable'] : null;
        $this->container['PublicDisplay'] = isset($data['PublicDisplay']) ? $data['PublicDisplay'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = parent::listInvalidProperties();

        $allowedValues = $this->getPublicDisplayAllowableValues();
        if (!is_null($this->container['PublicDisplay']) && !in_array($this->container['PublicDisplay'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'PublicDisplay', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }


    /**
     * Gets Test
     *
     * @return bool
     */
    public function getTest()
    {
        return $this->container['Test'];
    }

    /**
     * Sets Test
     *
     * @param bool $Test When `true`, the request ensures that its parameters are valid without affecting real data.  When `false`, the request performs as intended and may affect live client data.  (optional) Defaults to false.
     *
     * @return $this
     */
    public function setTest($Test): self
    {
        $this->container['Test'] = $Test;

        return $this;
    }

    /**
     * Gets LocationID
     *
     * @return int
     */
    public function getLocationID()
    {
        return $this->container['LocationID'];
    }

    /**
     * Sets LocationID
     *
     * @param int $LocationID Location of availability.  <br />Not used when IsUnavailable is `true`.
     *
     * @return $this
     */
    public function setLocationID($LocationID): self
    {
        $this->container['LocationID'] = $LocationID;

        return $this;
    }

    /**
     * Gets StaffIDs
     *
     * @return int[]
     */
    public function getStaffIDs()
    {
        return $this->container['StaffIDs'];
    }

    /**
     * Sets StaffIDs
     *
     * @param int[] $StaffIDs A list of requested staff IDs.<br />  (optional) Defaults to staff ID of user credentials. Use 0 for all.
     *
     * @return $this
     */
    public function setStaffIDs($StaffIDs): self
    {
        $this->container['StaffIDs'] = $StaffIDs;

        return $this;
    }

    /**
     * Gets ProgramIDs
     *
     * @return int[]
     */
    public function getProgramIDs()
    {
        return $this->container['ProgramIDs'];
    }

    /**
     * Sets ProgramIDs
     *
     * @param int[] $ProgramIDs A list of program IDs.<br />  (optional) Defaults to all.  <br />Not used when IsUnavailable is true.
     *
     * @return $this
     */
    public function setProgramIDs($ProgramIDs): self
    {
        $this->container['ProgramIDs'] = $ProgramIDs;

        return $this;
    }

    /**
     * Gets StartDateTime
     *
     * @return \DateTime
     */
    public function getStartDateTime()
    {
        return $this->container['StartDateTime'];
    }

    /**
     * Sets StartDateTime
     *
     * @param \DateTime $StartDateTime The start date and time of the new availabilities or unavailabilities.
     *
     * @return $this
     */
    public function setStartDateTime($StartDateTime): self
    {
        $this->container['StartDateTime'] = $StartDateTime;

        return $this;
    }

    /**
     * Gets EndDateTime
     *
     * @return \DateTime
     */
    public function getEndDateTime()
    {
        return $this->container['EndDateTime'];
    }

    /**
     * Sets EndDateTime
     *
     * @param \DateTime $EndDateTime The end date and time of the new availabilities or unavailabilities.
     *
     * @return $this
     */
    public function setEndDateTime($EndDateTime): self
    {
        $this->container['EndDateTime'] = $EndDateTime;

        return $this;
    }

    /**
     * Gets DaysOfWeek
     *
     * @return string[]
     */
    public function getDaysOfWeek()
    {
        return $this->container['DaysOfWeek'];
    }

    /**
     * Sets DaysOfWeek
     *
     * @param string[] $DaysOfWeek The days of the week to set.<br />  (optional) Defaults to all.
     *
     * @return $this
     */
    public function setDaysOfWeek($DaysOfWeek): self
    {
        $allowedValues = $this->getDaysOfWeekAllowableValues();
        if (!is_null($DaysOfWeek) && array_diff($DaysOfWeek, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'DaysOfWeek', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['DaysOfWeek'] = $DaysOfWeek;

        return $this;
    }

    /**
     * Gets UnavailableDescription
     *
     * @return string
     */
    public function getUnavailableDescription()
    {
        return $this->container['UnavailableDescription'];
    }

    /**
     * Sets UnavailableDescription
     *
     * @param string $UnavailableDescription Description of unavalability.  <br />Only used when IsUnavailable is true.
     *
     * @return $this
     */
    public function setUnavailableDescription($UnavailableDescription): self
    {
        $this->container['UnavailableDescription'] = $UnavailableDescription;

        return $this;
    }

    /**
     * Gets IsUnavailable
     *
     * @return bool
     */
    public function getIsUnavailable()
    {
        return $this->container['IsUnavailable'];
    }

    /**
     * Sets IsUnavailable
     *
     * @param bool $IsUnavailable When `true`, indicates that unavailability is getting added. When `false`, indicates that availability is getting added.  Default: **false**
     *
     * @return $this
     */
    public function setIsUnavailable($IsUnavailable): self
    {
        $this->container['IsUnavailable'] = $IsUnavailable;

        return $this;
    }

    /**
     * Gets PublicDisplay
     *
     * @return string
     */
    public function getPublicDisplay()
    {
        return $this->container['PublicDisplay'];
    }

    /**
     * Sets PublicDisplay
     *
     * @param string $PublicDisplay Sets the public display of the availability.<br /><ul><li>Show</li><li>Mask</li><li>Hide</li></ul>  (optional) Defaults to Show.
     *
     * @return $this
     */
    public function setPublicDisplay($PublicDisplay): self
    {
        $allowedValues = $this->getPublicDisplayAllowableValues();
        if (!is_null($PublicDisplay) && !in_array($PublicDisplay, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'PublicDisplay', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['PublicDisplay'] = $PublicDisplay;

        return $this;
    }
    
}


