<?php
/**
 * AddClientToClassVisit
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Nlocascio\Mindbody\Model;

/**
 * AddClientToClassVisit Class Doc Comment
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 * @property int $AppointmentId The appointment’s ID.
 * @property string $AppointmentGenderPreference The gender of staff member with whom the client prefers to book appointments.
 * @property string $AppointmentStatus The status of the appointment.
 * @property int $ClassId The class ID that was used to retrieve the visits.
 * @property string $ClientId The ID of the client associated with the visit.
 * @property \DateTime $StartDateTime The time this class is scheduled to start.
 * @property \DateTime $EndDateTime The date and time the visit ends. The Public API returns UTC dates and times. For example, a class that occurs on June 25th, 2018 at 2:15PM (EST) appears as “2018-06-25T19:15:00Z” because EST is five hours behind UTC. Date time pairs always return in the format YYYY-MM-DDTHH:mm:ssZ.
 * @property int $Id The ID of the visit.
 * @property \DateTime $LastModifiedDateTime When included in the request, only records modified on or after the specified `LastModifiedDate` are included in the response. The Public API returns UTC dates and times. For example, a class that occurs on June 25th, 2018 at 2:15PM (EST) appears as “2018-06-25T19:15:00Z” because EST is five hours behind UTC. Date time pairs always return in the format YYYY-MM-DDTHH:mm:ssZ.
 * @property bool $LateCancelled When `true`, indicates that the class has been `LateCancelled`.<br />  When `false`, indicates that the class has not been `LateCancelled`.
 * @property int $LocationId The ID of the location where the visit took place or is to take place.
 * @property bool $MakeUp When `true`, the client can make up this session and a session is not deducted from the pricing option that was used to sign the client into the enrollment. When the client has the make-up session, a session is automatically removed from a pricing option that matches the service category of the enrollment and is within the same date range of the missed session.<br />  When `false`, the client cannot make up this session. See [Enrollments: Make-ups](https://support.mindbodyonline.com/s/article/203259433-Enrollments-Make-ups?language=en_US) for more information.
 * @property string $Name The name of the class.
 * @property int $ServiceId The ID of the client's pricing option applied to the class visit.
 * @property string $ServiceName The name of the pricing option applied to the class visit.
 * @property int $ProductId The business' ID of the type of pricing option used to pay for the class visit.
 * @property bool $SignedIn When `true`, indicates that the client has been signed in.<br />  When `false`, indicates that the client has not been signed in.
 * @property int $StaffId The ID of the staff member who is teaching the class.
 * @property bool $WebSignup When `true`, indicates that the client signed up online.<br />  When `false`, indicates that the client was signed up by a staff member.
 * @property string $Action The action taken.
 * @property bool $CrossRegionalBookingPerformed When `true`, indicates that the client is paying for the visit using a pricing option from one of their associated cross-regional profiles.
 * @property int $SiteId The ID of the business from which cross-regional payment is applied.
 * @property int $WaitlistEntryId When this value is not null, it indicates that the client is on the waiting list for the requested class. The only additional fields that are populated when this is not null are:  * ClassId  * ClientId    You can call GET WaitlistEntries using `WaitlistEntryId` to obtain more data about this waiting list entry.
 *
 */
class AddClientToClassVisit extends BaseModel implements ModelWithIntId
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $swaggerModelName = 'AddClientToClassVisit';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static array $swaggerTypes = [
        'AppointmentId' => 'int',
        'AppointmentGenderPreference' => 'string',
        'AppointmentStatus' => 'string',
        'ClassId' => 'int',
        'ClientId' => 'string',
        'StartDateTime' => '\DateTime',
        'EndDateTime' => '\DateTime',
        'Id' => 'int',
        'LastModifiedDateTime' => '\DateTime',
        'LateCancelled' => 'bool',
        'LocationId' => 'int',
        'MakeUp' => 'bool',
        'Name' => 'string',
        'ServiceId' => 'int',
        'ServiceName' => 'string',
        'ProductId' => 'int',
        'SignedIn' => 'bool',
        'StaffId' => 'int',
        'WebSignup' => 'bool',
        'Action' => 'string',
        'CrossRegionalBookingPerformed' => 'bool',
        'SiteId' => 'int',
        'WaitlistEntryId' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $swaggerFormats = [
        'AppointmentId' => 'int32',
        'AppointmentGenderPreference' => null,
        'AppointmentStatus' => null,
        'ClassId' => 'int32',
        'ClientId' => null,
        'StartDateTime' => 'date-time',
        'EndDateTime' => 'date-time',
        'Id' => 'int64',
        'LastModifiedDateTime' => 'date-time',
        'LateCancelled' => null,
        'LocationId' => 'int32',
        'MakeUp' => null,
        'Name' => null,
        'ServiceId' => 'int64',
        'ServiceName' => null,
        'ProductId' => 'int64',
        'SignedIn' => null,
        'StaffId' => 'int64',
        'WebSignup' => null,
        'Action' => null,
        'CrossRegionalBookingPerformed' => null,
        'SiteId' => 'int32',
        'WaitlistEntryId' => 'int32'
    ];


    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static array $attributeMap = [
        'AppointmentId' => 'AppointmentId',
        'AppointmentGenderPreference' => 'AppointmentGenderPreference',
        'AppointmentStatus' => 'AppointmentStatus',
        'ClassId' => 'ClassId',
        'ClientId' => 'ClientId',
        'StartDateTime' => 'StartDateTime',
        'EndDateTime' => 'EndDateTime',
        'Id' => 'Id',
        'LastModifiedDateTime' => 'LastModifiedDateTime',
        'LateCancelled' => 'LateCancelled',
        'LocationId' => 'LocationId',
        'MakeUp' => 'MakeUp',
        'Name' => 'Name',
        'ServiceId' => 'ServiceId',
        'ServiceName' => 'ServiceName',
        'ProductId' => 'ProductId',
        'SignedIn' => 'SignedIn',
        'StaffId' => 'StaffId',
        'WebSignup' => 'WebSignup',
        'Action' => 'Action',
        'CrossRegionalBookingPerformed' => 'CrossRegionalBookingPerformed',
        'SiteId' => 'SiteId',
        'WaitlistEntryId' => 'WaitlistEntryId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static array $setters = [
        'AppointmentId' => 'setAppointmentId',
        'AppointmentGenderPreference' => 'setAppointmentGenderPreference',
        'AppointmentStatus' => 'setAppointmentStatus',
        'ClassId' => 'setClassId',
        'ClientId' => 'setClientId',
        'StartDateTime' => 'setStartDateTime',
        'EndDateTime' => 'setEndDateTime',
        'Id' => 'setId',
        'LastModifiedDateTime' => 'setLastModifiedDateTime',
        'LateCancelled' => 'setLateCancelled',
        'LocationId' => 'setLocationId',
        'MakeUp' => 'setMakeUp',
        'Name' => 'setName',
        'ServiceId' => 'setServiceId',
        'ServiceName' => 'setServiceName',
        'ProductId' => 'setProductId',
        'SignedIn' => 'setSignedIn',
        'StaffId' => 'setStaffId',
        'WebSignup' => 'setWebSignup',
        'Action' => 'setAction',
        'CrossRegionalBookingPerformed' => 'setCrossRegionalBookingPerformed',
        'SiteId' => 'setSiteId',
        'WaitlistEntryId' => 'setWaitlistEntryId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static array $getters = [
        'AppointmentId' => 'getAppointmentId',
        'AppointmentGenderPreference' => 'getAppointmentGenderPreference',
        'AppointmentStatus' => 'getAppointmentStatus',
        'ClassId' => 'getClassId',
        'ClientId' => 'getClientId',
        'StartDateTime' => 'getStartDateTime',
        'EndDateTime' => 'getEndDateTime',
        'Id' => 'getId',
        'LastModifiedDateTime' => 'getLastModifiedDateTime',
        'LateCancelled' => 'getLateCancelled',
        'LocationId' => 'getLocationId',
        'MakeUp' => 'getMakeUp',
        'Name' => 'getName',
        'ServiceId' => 'getServiceId',
        'ServiceName' => 'getServiceName',
        'ProductId' => 'getProductId',
        'SignedIn' => 'getSignedIn',
        'StaffId' => 'getStaffId',
        'WebSignup' => 'getWebSignup',
        'Action' => 'getAction',
        'CrossRegionalBookingPerformed' => 'getCrossRegionalBookingPerformed',
        'SiteId' => 'getSiteId',
        'WaitlistEntryId' => 'getWaitlistEntryId'
    ];


    const APPOINTMENT_GENDER_PREFERENCE_NONE = 'None';
    const APPOINTMENT_GENDER_PREFERENCE_FEMALE = 'Female';
    const APPOINTMENT_GENDER_PREFERENCE_MALE = 'Male';
    const APPOINTMENT_STATUS_NONE = 'None';
    const APPOINTMENT_STATUS_REQUESTED = 'Requested';
    const APPOINTMENT_STATUS_BOOKED = 'Booked';
    const APPOINTMENT_STATUS_COMPLETED = 'Completed';
    const APPOINTMENT_STATUS_CONFIRMED = 'Confirmed';
    const APPOINTMENT_STATUS_ARRIVED = 'Arrived';
    const APPOINTMENT_STATUS_NO_SHOW = 'NoShow';
    const APPOINTMENT_STATUS_CANCELLED = 'Cancelled';
    const APPOINTMENT_STATUS_LATE_CANCELLED = 'LateCancelled';
    const ACTION_NONE = 'None';
    const ACTION_ADDED = 'Added';
    const ACTION_UPDATED = 'Updated';
    const ACTION_FAILED = 'Failed';
    const ACTION_REMOVED = 'Removed';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getAppointmentGenderPreferenceAllowableValues(): array
    {
        return [
            self::APPOINTMENT_GENDER_PREFERENCE_NONE,
            self::APPOINTMENT_GENDER_PREFERENCE_FEMALE,
            self::APPOINTMENT_GENDER_PREFERENCE_MALE,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getAppointmentStatusAllowableValues(): array
    {
        return [
            self::APPOINTMENT_STATUS_NONE,
            self::APPOINTMENT_STATUS_REQUESTED,
            self::APPOINTMENT_STATUS_BOOKED,
            self::APPOINTMENT_STATUS_COMPLETED,
            self::APPOINTMENT_STATUS_CONFIRMED,
            self::APPOINTMENT_STATUS_ARRIVED,
            self::APPOINTMENT_STATUS_NO_SHOW,
            self::APPOINTMENT_STATUS_CANCELLED,
            self::APPOINTMENT_STATUS_LATE_CANCELLED,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getActionAllowableValues(): array
    {
        return [
            self::ACTION_NONE,
            self::ACTION_ADDED,
            self::ACTION_UPDATED,
            self::ACTION_FAILED,
            self::ACTION_REMOVED,
        ];
    }
    

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->container['AppointmentId'] = isset($data['AppointmentId']) ? $data['AppointmentId'] : null;
        $this->container['AppointmentGenderPreference'] = isset($data['AppointmentGenderPreference']) ? $data['AppointmentGenderPreference'] : null;
        $this->container['AppointmentStatus'] = isset($data['AppointmentStatus']) ? $data['AppointmentStatus'] : null;
        $this->container['ClassId'] = isset($data['ClassId']) ? $data['ClassId'] : null;
        $this->container['ClientId'] = isset($data['ClientId']) ? $data['ClientId'] : null;
        $this->container['StartDateTime'] = isset($data['StartDateTime']) ? $data['StartDateTime'] : null;
        $this->container['EndDateTime'] = isset($data['EndDateTime']) ? $data['EndDateTime'] : null;
        $this->container['Id'] = isset($data['Id']) ? $data['Id'] : null;
        $this->container['LastModifiedDateTime'] = isset($data['LastModifiedDateTime']) ? $data['LastModifiedDateTime'] : null;
        $this->container['LateCancelled'] = isset($data['LateCancelled']) ? $data['LateCancelled'] : null;
        $this->container['LocationId'] = isset($data['LocationId']) ? $data['LocationId'] : null;
        $this->container['MakeUp'] = isset($data['MakeUp']) ? $data['MakeUp'] : null;
        $this->container['Name'] = isset($data['Name']) ? $data['Name'] : null;
        $this->container['ServiceId'] = isset($data['ServiceId']) ? $data['ServiceId'] : null;
        $this->container['ServiceName'] = isset($data['ServiceName']) ? $data['ServiceName'] : null;
        $this->container['ProductId'] = isset($data['ProductId']) ? $data['ProductId'] : null;
        $this->container['SignedIn'] = isset($data['SignedIn']) ? $data['SignedIn'] : null;
        $this->container['StaffId'] = isset($data['StaffId']) ? $data['StaffId'] : null;
        $this->container['WebSignup'] = isset($data['WebSignup']) ? $data['WebSignup'] : null;
        $this->container['Action'] = isset($data['Action']) ? $data['Action'] : null;
        $this->container['CrossRegionalBookingPerformed'] = isset($data['CrossRegionalBookingPerformed']) ? $data['CrossRegionalBookingPerformed'] : null;
        $this->container['SiteId'] = isset($data['SiteId']) ? $data['SiteId'] : null;
        $this->container['WaitlistEntryId'] = isset($data['WaitlistEntryId']) ? $data['WaitlistEntryId'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = parent::listInvalidProperties();

        $allowedValues = $this->getAppointmentGenderPreferenceAllowableValues();
        if (!is_null($this->container['AppointmentGenderPreference']) && !in_array($this->container['AppointmentGenderPreference'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'AppointmentGenderPreference', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getAppointmentStatusAllowableValues();
        if (!is_null($this->container['AppointmentStatus']) && !in_array($this->container['AppointmentStatus'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'AppointmentStatus', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getActionAllowableValues();
        if (!is_null($this->container['Action']) && !in_array($this->container['Action'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'Action', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }


    /**
     * Gets AppointmentId
     *
     * @return int
     */
    public function getAppointmentId(): int
    {
        return $this->container['AppointmentId'];
    }

    /**
     * Sets AppointmentId
     *
     * @param int $AppointmentId The appointment’s ID.
     *
     * @return $this
     */


    public function setAppointmentId(int $AppointmentId): static
    {
        $this->container['AppointmentId'] = $AppointmentId;

        return $this;
    }

    /**
     * Gets AppointmentGenderPreference
     *
     * @return string
     */
    public function getAppointmentGenderPreference(): string
    {
        return $this->container['AppointmentGenderPreference'];
    }

    /**
     * Sets AppointmentGenderPreference
     *
     * @param string $AppointmentGenderPreference The gender of staff member with whom the client prefers to book appointments.
     *
     * @return $this
     */


    public function setAppointmentGenderPreference(string $AppointmentGenderPreference): static
    {
        $allowedValues = $this->getAppointmentGenderPreferenceAllowableValues();
        if (!is_null($AppointmentGenderPreference) && !in_array($AppointmentGenderPreference, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'AppointmentGenderPreference', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['AppointmentGenderPreference'] = $AppointmentGenderPreference;

        return $this;
    }

    /**
     * Gets AppointmentStatus
     *
     * @return string
     */
    public function getAppointmentStatus(): string
    {
        return $this->container['AppointmentStatus'];
    }

    /**
     * Sets AppointmentStatus
     *
     * @param string $AppointmentStatus The status of the appointment.
     *
     * @return $this
     */


    public function setAppointmentStatus(string $AppointmentStatus): static
    {
        $allowedValues = $this->getAppointmentStatusAllowableValues();
        if (!is_null($AppointmentStatus) && !in_array($AppointmentStatus, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'AppointmentStatus', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['AppointmentStatus'] = $AppointmentStatus;

        return $this;
    }

    /**
     * Gets ClassId
     *
     * @return int
     */
    public function getClassId(): int
    {
        return $this->container['ClassId'];
    }

    /**
     * Sets ClassId
     *
     * @param int $ClassId The class ID that was used to retrieve the visits.
     *
     * @return $this
     */


    public function setClassId(int $ClassId): static
    {
        $this->container['ClassId'] = $ClassId;

        return $this;
    }

    /**
     * Gets ClientId
     *
     * @return string
     */
    public function getClientId(): string
    {
        return $this->container['ClientId'];
    }

    /**
     * Sets ClientId
     *
     * @param string $ClientId The ID of the client associated with the visit.
     *
     * @return $this
     */


    public function setClientId(string $ClientId): static
    {
        $this->container['ClientId'] = $ClientId;

        return $this;
    }

    /**
     * Gets StartDateTime
     *
     * @return \DateTime
     */
    public function getStartDateTime(): \DateTime
    {
        return $this->container['StartDateTime'];
    }

    /**
     * Sets StartDateTime
     *
     * @param \DateTime $StartDateTime The time this class is scheduled to start.
     *
     * @return $this
     */


    public function setStartDateTime(\DateTime $StartDateTime): static
    {
        $this->container['StartDateTime'] = $StartDateTime;

        return $this;
    }

    /**
     * Gets EndDateTime
     *
     * @return \DateTime
     */
    public function getEndDateTime(): \DateTime
    {
        return $this->container['EndDateTime'];
    }

    /**
     * Sets EndDateTime
     *
     * @param \DateTime $EndDateTime The date and time the visit ends. The Public API returns UTC dates and times. For example, a class that occurs on June 25th, 2018 at 2:15PM (EST) appears as “2018-06-25T19:15:00Z” because EST is five hours behind UTC. Date time pairs always return in the format YYYY-MM-DDTHH:mm:ssZ.
     *
     * @return $this
     */


    public function setEndDateTime(\DateTime $EndDateTime): static
    {
        $this->container['EndDateTime'] = $EndDateTime;

        return $this;
    }

    /**
     * Gets Id
     *
     * @return int
     */
    public function getId(): int
    {
        return $this->container['Id'];
    }

    /**
     * Sets Id
     *
     * @param int $Id The ID of the visit.
     *
     * @return $this
     */


    public function setId(int $Id): static
    {
        $this->container['Id'] = $Id;

        return $this;
    }

    /**
     * Gets LastModifiedDateTime
     *
     * @return \DateTime
     */
    public function getLastModifiedDateTime(): \DateTime
    {
        return $this->container['LastModifiedDateTime'];
    }

    /**
     * Sets LastModifiedDateTime
     *
     * @param \DateTime $LastModifiedDateTime When included in the request, only records modified on or after the specified `LastModifiedDate` are included in the response. The Public API returns UTC dates and times. For example, a class that occurs on June 25th, 2018 at 2:15PM (EST) appears as “2018-06-25T19:15:00Z” because EST is five hours behind UTC. Date time pairs always return in the format YYYY-MM-DDTHH:mm:ssZ.
     *
     * @return $this
     */


    public function setLastModifiedDateTime(\DateTime $LastModifiedDateTime): static
    {
        $this->container['LastModifiedDateTime'] = $LastModifiedDateTime;

        return $this;
    }

    /**
     * Gets LateCancelled
     *
     * @return bool
     */
    public function getLateCancelled(): bool
    {
        return $this->container['LateCancelled'];
    }

    /**
     * Sets LateCancelled
     *
     * @param bool $LateCancelled When `true`, indicates that the class has been `LateCancelled`.<br />  When `false`, indicates that the class has not been `LateCancelled`.
     *
     * @return $this
     */


    public function setLateCancelled(bool $LateCancelled): static
    {
        $this->container['LateCancelled'] = $LateCancelled;

        return $this;
    }

    /**
     * Gets LocationId
     *
     * @return int
     */
    public function getLocationId(): int
    {
        return $this->container['LocationId'];
    }

    /**
     * Sets LocationId
     *
     * @param int $LocationId The ID of the location where the visit took place or is to take place.
     *
     * @return $this
     */


    public function setLocationId(int $LocationId): static
    {
        $this->container['LocationId'] = $LocationId;

        return $this;
    }

    /**
     * Gets MakeUp
     *
     * @return bool
     */
    public function getMakeUp(): bool
    {
        return $this->container['MakeUp'];
    }

    /**
     * Sets MakeUp
     *
     * @param bool $MakeUp When `true`, the client can make up this session and a session is not deducted from the pricing option that was used to sign the client into the enrollment. When the client has the make-up session, a session is automatically removed from a pricing option that matches the service category of the enrollment and is within the same date range of the missed session.<br />  When `false`, the client cannot make up this session. See [Enrollments: Make-ups](https://support.mindbodyonline.com/s/article/203259433-Enrollments-Make-ups?language=en_US) for more information.
     *
     * @return $this
     */


    public function setMakeUp(bool $MakeUp): static
    {
        $this->container['MakeUp'] = $MakeUp;

        return $this;
    }

    /**
     * Gets Name
     *
     * @return string
     */
    public function getName(): string
    {
        return $this->container['Name'];
    }

    /**
     * Sets Name
     *
     * @param string $Name The name of the class.
     *
     * @return $this
     */


    public function setName(string $Name): static
    {
        $this->container['Name'] = $Name;

        return $this;
    }

    /**
     * Gets ServiceId
     *
     * @return int
     */
    public function getServiceId(): int
    {
        return $this->container['ServiceId'];
    }

    /**
     * Sets ServiceId
     *
     * @param int $ServiceId The ID of the client's pricing option applied to the class visit.
     *
     * @return $this
     */


    public function setServiceId(int $ServiceId): static
    {
        $this->container['ServiceId'] = $ServiceId;

        return $this;
    }

    /**
     * Gets ServiceName
     *
     * @return string
     */
    public function getServiceName(): string
    {
        return $this->container['ServiceName'];
    }

    /**
     * Sets ServiceName
     *
     * @param string $ServiceName The name of the pricing option applied to the class visit.
     *
     * @return $this
     */


    public function setServiceName(string $ServiceName): static
    {
        $this->container['ServiceName'] = $ServiceName;

        return $this;
    }

    /**
     * Gets ProductId
     *
     * @return int
     */
    public function getProductId(): int
    {
        return $this->container['ProductId'];
    }

    /**
     * Sets ProductId
     *
     * @param int $ProductId The business' ID of the type of pricing option used to pay for the class visit.
     *
     * @return $this
     */


    public function setProductId(int $ProductId): static
    {
        $this->container['ProductId'] = $ProductId;

        return $this;
    }

    /**
     * Gets SignedIn
     *
     * @return bool
     */
    public function getSignedIn(): bool
    {
        return $this->container['SignedIn'];
    }

    /**
     * Sets SignedIn
     *
     * @param bool $SignedIn When `true`, indicates that the client has been signed in.<br />  When `false`, indicates that the client has not been signed in.
     *
     * @return $this
     */


    public function setSignedIn(bool $SignedIn): static
    {
        $this->container['SignedIn'] = $SignedIn;

        return $this;
    }

    /**
     * Gets StaffId
     *
     * @return int
     */
    public function getStaffId(): int
    {
        return $this->container['StaffId'];
    }

    /**
     * Sets StaffId
     *
     * @param int $StaffId The ID of the staff member who is teaching the class.
     *
     * @return $this
     */


    public function setStaffId(int $StaffId): static
    {
        $this->container['StaffId'] = $StaffId;

        return $this;
    }

    /**
     * Gets WebSignup
     *
     * @return bool
     */
    public function getWebSignup(): bool
    {
        return $this->container['WebSignup'];
    }

    /**
     * Sets WebSignup
     *
     * @param bool $WebSignup When `true`, indicates that the client signed up online.<br />  When `false`, indicates that the client was signed up by a staff member.
     *
     * @return $this
     */


    public function setWebSignup(bool $WebSignup): static
    {
        $this->container['WebSignup'] = $WebSignup;

        return $this;
    }

    /**
     * Gets Action
     *
     * @return string
     */
    public function getAction(): string
    {
        return $this->container['Action'];
    }

    /**
     * Sets Action
     *
     * @param string $Action The action taken.
     *
     * @return $this
     */


    public function setAction(string $Action): static
    {
        $allowedValues = $this->getActionAllowableValues();
        if (!is_null($Action) && !in_array($Action, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'Action', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['Action'] = $Action;

        return $this;
    }

    /**
     * Gets CrossRegionalBookingPerformed
     *
     * @return bool
     */
    public function getCrossRegionalBookingPerformed(): bool
    {
        return $this->container['CrossRegionalBookingPerformed'];
    }

    /**
     * Sets CrossRegionalBookingPerformed
     *
     * @param bool $CrossRegionalBookingPerformed When `true`, indicates that the client is paying for the visit using a pricing option from one of their associated cross-regional profiles.
     *
     * @return $this
     */


    public function setCrossRegionalBookingPerformed(bool $CrossRegionalBookingPerformed): static
    {
        $this->container['CrossRegionalBookingPerformed'] = $CrossRegionalBookingPerformed;

        return $this;
    }

    /**
     * Gets SiteId
     *
     * @return int
     */
    public function getSiteId(): int
    {
        return $this->container['SiteId'];
    }

    /**
     * Sets SiteId
     *
     * @param int $SiteId The ID of the business from which cross-regional payment is applied.
     *
     * @return $this
     */


    public function setSiteId(int $SiteId): static
    {
        $this->container['SiteId'] = $SiteId;

        return $this;
    }

    /**
     * Gets WaitlistEntryId
     *
     * @return int
     */
    public function getWaitlistEntryId(): int
    {
        return $this->container['WaitlistEntryId'];
    }

    /**
     * Sets WaitlistEntryId
     *
     * @param int $WaitlistEntryId When this value is not null, it indicates that the client is on the waiting list for the requested class. The only additional fields that are populated when this is not null are:  * ClassId  * ClientId    You can call GET WaitlistEntries using `WaitlistEntryId` to obtain more data about this waiting list entry.
     *
     * @return $this
     */


    public function setWaitlistEntryId(int $WaitlistEntryId): static
    {
        $this->container['WaitlistEntryId'] = $WaitlistEntryId;

        return $this;
    }
    
}


