<?php
/**
 * AddClientToClassRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.40-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Nlocascio\Mindbody\Model;

/**
 * AddClientToClassRequest Class Doc Comment
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 * @property string $ClientId The ID of the client who is being booked into the class
 * @property int $ClassId The ID of the class into which the client is being booked
 * @property bool $Test When `true`, indicates that input information is validated, but not committed.<br />  When `false`, the information is committed and the database is affected.<br />  Default: **false**
 * @property bool $RequirePayment When `true`, the client must have an active, usable pricing option on their account.<br />  When `false` or omitted, an active pricing option is not required to complete the client’s booking.
 * @property bool $Waitlist When `true`, indicates that the client should be added to a specific class waiting list.<br />  When `false`, the client should not be added to the waiting list.
 * @property bool $SendEmail When `true`, the subscriber’s configured Booking Confirmation automatic email is sent to the client. Note that an email is sent only if the client has an email address and automatic emails have been set up.<br />  When `false`, indicates that the client does not receive emails.<br />  Default: **false**  **Note**: When the Authorization header is passed and the SendEmail is set to `true`, then an email will be sent.  When the Authorization header is passed and the SendEmail is set to `false`, then an email will not be sent.  When the Authorization header is not passed and the SendEmail is set to either `true` or `false`, then an email will not be sent.
 * @property int $WaitlistEntryId The ID of the waiting list entry from which you are moving a client into a class.
 * @property int $ClientServiceId The ID of the pricing option on the client’s account that you want to use to pay for this booking, if payment is required at the time of the update.
 * @property bool $CrossRegionalBooking When `true`, cross regional series are checked and used if applicable.
 * @property int $CrossRegionalBookingClientServiceSiteId If the request is cross regional, use a purchased pricing option from this specified site. If omitted, an attempt is made to use an applicable pricing option from the local site.
 * @property int $UniqueId The UniqueID of the client who is being booked into the class
 *
 */
class AddClientToClassRequest extends BaseModel
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'AddClientToClassRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'ClientId' => 'string',
        'ClassId' => 'int',
        'Test' => 'bool',
        'RequirePayment' => 'bool',
        'Waitlist' => 'bool',
        'SendEmail' => 'bool',
        'WaitlistEntryId' => 'int',
        'ClientServiceId' => 'int',
        'CrossRegionalBooking' => 'bool',
        'CrossRegionalBookingClientServiceSiteId' => 'int',
        'UniqueId' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static $swaggerFormats = [
        'ClientId' => null,
        'ClassId' => 'int32',
        'Test' => null,
        'RequirePayment' => null,
        'Waitlist' => null,
        'SendEmail' => null,
        'WaitlistEntryId' => 'int32',
        'ClientServiceId' => 'int32',
        'CrossRegionalBooking' => null,
        'CrossRegionalBookingClientServiceSiteId' => 'int32',
        'UniqueId' => 'int64'
    ];


    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'ClientId' => 'ClientId',
        'ClassId' => 'ClassId',
        'Test' => 'Test',
        'RequirePayment' => 'RequirePayment',
        'Waitlist' => 'Waitlist',
        'SendEmail' => 'SendEmail',
        'WaitlistEntryId' => 'WaitlistEntryId',
        'ClientServiceId' => 'ClientServiceId',
        'CrossRegionalBooking' => 'CrossRegionalBooking',
        'CrossRegionalBookingClientServiceSiteId' => 'CrossRegionalBookingClientServiceSiteId',
        'UniqueId' => 'UniqueId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'ClientId' => 'setClientId',
        'ClassId' => 'setClassId',
        'Test' => 'setTest',
        'RequirePayment' => 'setRequirePayment',
        'Waitlist' => 'setWaitlist',
        'SendEmail' => 'setSendEmail',
        'WaitlistEntryId' => 'setWaitlistEntryId',
        'ClientServiceId' => 'setClientServiceId',
        'CrossRegionalBooking' => 'setCrossRegionalBooking',
        'CrossRegionalBookingClientServiceSiteId' => 'setCrossRegionalBookingClientServiceSiteId',
        'UniqueId' => 'setUniqueId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'ClientId' => 'getClientId',
        'ClassId' => 'getClassId',
        'Test' => 'getTest',
        'RequirePayment' => 'getRequirePayment',
        'Waitlist' => 'getWaitlist',
        'SendEmail' => 'getSendEmail',
        'WaitlistEntryId' => 'getWaitlistEntryId',
        'ClientServiceId' => 'getClientServiceId',
        'CrossRegionalBooking' => 'getCrossRegionalBooking',
        'CrossRegionalBookingClientServiceSiteId' => 'getCrossRegionalBookingClientServiceSiteId',
        'UniqueId' => 'getUniqueId'
    ];


    

    

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['ClientId'] = isset($data['ClientId']) ? $data['ClientId'] : null;
        $this->container['ClassId'] = isset($data['ClassId']) ? $data['ClassId'] : null;
        $this->container['Test'] = isset($data['Test']) ? $data['Test'] : null;
        $this->container['RequirePayment'] = isset($data['RequirePayment']) ? $data['RequirePayment'] : null;
        $this->container['Waitlist'] = isset($data['Waitlist']) ? $data['Waitlist'] : null;
        $this->container['SendEmail'] = isset($data['SendEmail']) ? $data['SendEmail'] : null;
        $this->container['WaitlistEntryId'] = isset($data['WaitlistEntryId']) ? $data['WaitlistEntryId'] : null;
        $this->container['ClientServiceId'] = isset($data['ClientServiceId']) ? $data['ClientServiceId'] : null;
        $this->container['CrossRegionalBooking'] = isset($data['CrossRegionalBooking']) ? $data['CrossRegionalBooking'] : null;
        $this->container['CrossRegionalBookingClientServiceSiteId'] = isset($data['CrossRegionalBookingClientServiceSiteId']) ? $data['CrossRegionalBookingClientServiceSiteId'] : null;
        $this->container['UniqueId'] = isset($data['UniqueId']) ? $data['UniqueId'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = parent::listInvalidProperties();

        if ($this->container['ClientId'] === null) {
            $invalidProperties[] = "'ClientId' can't be null";
        }
        if ($this->container['ClassId'] === null) {
            $invalidProperties[] = "'ClassId' can't be null";
        }
        return $invalidProperties;
    }


    /**
     * Gets ClientId
     *
     * @return string
     */
    public function getClientId()
    {
        return $this->container['ClientId'];
    }

    /**
     * Sets ClientId
     *
     * @param string $ClientId The ID of the client who is being booked into the class
     *
     * @return $this
     */
    public function setClientId($ClientId): self
    {
        $this->container['ClientId'] = $ClientId;

        return $this;
    }

    /**
     * Gets ClassId
     *
     * @return int
     */
    public function getClassId()
    {
        return $this->container['ClassId'];
    }

    /**
     * Sets ClassId
     *
     * @param int $ClassId The ID of the class into which the client is being booked
     *
     * @return $this
     */
    public function setClassId($ClassId): self
    {
        $this->container['ClassId'] = $ClassId;

        return $this;
    }

    /**
     * Gets Test
     *
     * @return bool
     */
    public function getTest()
    {
        return $this->container['Test'];
    }

    /**
     * Sets Test
     *
     * @param bool $Test When `true`, indicates that input information is validated, but not committed.<br />  When `false`, the information is committed and the database is affected.<br />  Default: **false**
     *
     * @return $this
     */
    public function setTest($Test): self
    {
        $this->container['Test'] = $Test;

        return $this;
    }

    /**
     * Gets RequirePayment
     *
     * @return bool
     */
    public function getRequirePayment()
    {
        return $this->container['RequirePayment'];
    }

    /**
     * Sets RequirePayment
     *
     * @param bool $RequirePayment When `true`, the client must have an active, usable pricing option on their account.<br />  When `false` or omitted, an active pricing option is not required to complete the client’s booking.
     *
     * @return $this
     */
    public function setRequirePayment($RequirePayment): self
    {
        $this->container['RequirePayment'] = $RequirePayment;

        return $this;
    }

    /**
     * Gets Waitlist
     *
     * @return bool
     */
    public function getWaitlist()
    {
        return $this->container['Waitlist'];
    }

    /**
     * Sets Waitlist
     *
     * @param bool $Waitlist When `true`, indicates that the client should be added to a specific class waiting list.<br />  When `false`, the client should not be added to the waiting list.
     *
     * @return $this
     */
    public function setWaitlist($Waitlist): self
    {
        $this->container['Waitlist'] = $Waitlist;

        return $this;
    }

    /**
     * Gets SendEmail
     *
     * @return bool
     */
    public function getSendEmail()
    {
        return $this->container['SendEmail'];
    }

    /**
     * Sets SendEmail
     *
     * @param bool $SendEmail When `true`, the subscriber’s configured Booking Confirmation automatic email is sent to the client. Note that an email is sent only if the client has an email address and automatic emails have been set up.<br />  When `false`, indicates that the client does not receive emails.<br />  Default: **false**  **Note**: When the Authorization header is passed and the SendEmail is set to `true`, then an email will be sent.  When the Authorization header is passed and the SendEmail is set to `false`, then an email will not be sent.  When the Authorization header is not passed and the SendEmail is set to either `true` or `false`, then an email will not be sent.
     *
     * @return $this
     */
    public function setSendEmail($SendEmail): self
    {
        $this->container['SendEmail'] = $SendEmail;

        return $this;
    }

    /**
     * Gets WaitlistEntryId
     *
     * @return int
     */
    public function getWaitlistEntryId()
    {
        return $this->container['WaitlistEntryId'];
    }

    /**
     * Sets WaitlistEntryId
     *
     * @param int $WaitlistEntryId The ID of the waiting list entry from which you are moving a client into a class.
     *
     * @return $this
     */
    public function setWaitlistEntryId($WaitlistEntryId): self
    {
        $this->container['WaitlistEntryId'] = $WaitlistEntryId;

        return $this;
    }

    /**
     * Gets ClientServiceId
     *
     * @return int
     */
    public function getClientServiceId()
    {
        return $this->container['ClientServiceId'];
    }

    /**
     * Sets ClientServiceId
     *
     * @param int $ClientServiceId The ID of the pricing option on the client’s account that you want to use to pay for this booking, if payment is required at the time of the update.
     *
     * @return $this
     */
    public function setClientServiceId($ClientServiceId): self
    {
        $this->container['ClientServiceId'] = $ClientServiceId;

        return $this;
    }

    /**
     * Gets CrossRegionalBooking
     *
     * @return bool
     */
    public function getCrossRegionalBooking()
    {
        return $this->container['CrossRegionalBooking'];
    }

    /**
     * Sets CrossRegionalBooking
     *
     * @param bool $CrossRegionalBooking When `true`, cross regional series are checked and used if applicable.
     *
     * @return $this
     */
    public function setCrossRegionalBooking($CrossRegionalBooking): self
    {
        $this->container['CrossRegionalBooking'] = $CrossRegionalBooking;

        return $this;
    }

    /**
     * Gets CrossRegionalBookingClientServiceSiteId
     *
     * @return int
     */
    public function getCrossRegionalBookingClientServiceSiteId()
    {
        return $this->container['CrossRegionalBookingClientServiceSiteId'];
    }

    /**
     * Sets CrossRegionalBookingClientServiceSiteId
     *
     * @param int $CrossRegionalBookingClientServiceSiteId If the request is cross regional, use a purchased pricing option from this specified site. If omitted, an attempt is made to use an applicable pricing option from the local site.
     *
     * @return $this
     */
    public function setCrossRegionalBookingClientServiceSiteId($CrossRegionalBookingClientServiceSiteId): self
    {
        $this->container['CrossRegionalBookingClientServiceSiteId'] = $CrossRegionalBookingClientServiceSiteId;

        return $this;
    }

    /**
     * Gets UniqueId
     *
     * @return int
     */
    public function getUniqueId()
    {
        return $this->container['UniqueId'];
    }

    /**
     * Sets UniqueId
     *
     * @param int $UniqueId The UniqueID of the client who is being booked into the class
     *
     * @return $this
     */
    public function setUniqueId($UniqueId): self
    {
        $this->container['UniqueId'] = $UniqueId;

        return $this;
    }
    
}


