<?php
/**
 * AssignStaffSessionTypeRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.50
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Nlocascio\Mindbody\Model;

/**
 * AssignStaffSessionTypeRequest Class Doc Comment
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 * @property int $StaffId The ID of the staff member session type is getting assigned to. The staff member must be assignable to appointments or already be assigned to the session type in the request.
 * @property int $SessionTypeId The ID of the session type that is getting assigned to the staff member. The session type must be an appointment.
 * @property bool $Active Indicates if assignment is active. Passing `false` is equivalent to deleting the assignment.
 * @property int $TimeLength The staff specific amount of time that a session of this type typically lasts.
 * @property int $PrepTime Prep time in minutes
 * @property int $FinishTime Finish time in minutes
 * @property string $PayRateType The pay rate type. Can be one of the following (case insensitive):     Percent     Flat     No Pay     If PayRateType is not provided in the request and the request is creating a completely new assignment (not editing an existing active or inactive assignment), then the staff member default pay rate and pay rate amount are used to create the assignment. Otherwise, the existing assignment values are used for any optional request parameters not included in the request.
 * @property double $PayRateAmount The pay rate amount for the specific staff member. It is parsed according to the PayRateType.
 *
 */
class AssignStaffSessionTypeRequest extends BaseModel
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'AssignStaffSessionTypeRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'StaffId' => 'int',
        'SessionTypeId' => 'int',
        'Active' => 'bool',
        'TimeLength' => 'int',
        'PrepTime' => 'int',
        'FinishTime' => 'int',
        'PayRateType' => 'string',
        'PayRateAmount' => 'double'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static $swaggerFormats = [
        'StaffId' => 'int64',
        'SessionTypeId' => 'int32',
        'Active' => null,
        'TimeLength' => 'int32',
        'PrepTime' => 'int32',
        'FinishTime' => 'int32',
        'PayRateType' => null,
        'PayRateAmount' => 'double'
    ];


    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'StaffId' => 'StaffId',
        'SessionTypeId' => 'SessionTypeId',
        'Active' => 'Active',
        'TimeLength' => 'TimeLength',
        'PrepTime' => 'PrepTime',
        'FinishTime' => 'FinishTime',
        'PayRateType' => 'PayRateType',
        'PayRateAmount' => 'PayRateAmount'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'StaffId' => 'setStaffId',
        'SessionTypeId' => 'setSessionTypeId',
        'Active' => 'setActive',
        'TimeLength' => 'setTimeLength',
        'PrepTime' => 'setPrepTime',
        'FinishTime' => 'setFinishTime',
        'PayRateType' => 'setPayRateType',
        'PayRateAmount' => 'setPayRateAmount'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'StaffId' => 'getStaffId',
        'SessionTypeId' => 'getSessionTypeId',
        'Active' => 'getActive',
        'TimeLength' => 'getTimeLength',
        'PrepTime' => 'getPrepTime',
        'FinishTime' => 'getFinishTime',
        'PayRateType' => 'getPayRateType',
        'PayRateAmount' => 'getPayRateAmount'
    ];


    

    

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['StaffId'] = isset($data['StaffId']) ? $data['StaffId'] : null;
        $this->container['SessionTypeId'] = isset($data['SessionTypeId']) ? $data['SessionTypeId'] : null;
        $this->container['Active'] = isset($data['Active']) ? $data['Active'] : null;
        $this->container['TimeLength'] = isset($data['TimeLength']) ? $data['TimeLength'] : null;
        $this->container['PrepTime'] = isset($data['PrepTime']) ? $data['PrepTime'] : null;
        $this->container['FinishTime'] = isset($data['FinishTime']) ? $data['FinishTime'] : null;
        $this->container['PayRateType'] = isset($data['PayRateType']) ? $data['PayRateType'] : null;
        $this->container['PayRateAmount'] = isset($data['PayRateAmount']) ? $data['PayRateAmount'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = parent::listInvalidProperties();

        if ($this->container['StaffId'] === null) {
            $invalidProperties[] = "'StaffId' can't be null";
        }
        if (($this->container['StaffId'] < 1)) {
            $invalidProperties[] = "invalid value for 'StaffId', must be bigger than or equal to 1.";
        }

        if ($this->container['SessionTypeId'] === null) {
            $invalidProperties[] = "'SessionTypeId' can't be null";
        }
        if (($this->container['SessionTypeId'] > 2147483647)) {
            $invalidProperties[] = "invalid value for 'SessionTypeId', must be smaller than or equal to 2147483647.";
        }

        if (($this->container['SessionTypeId'] < 1)) {
            $invalidProperties[] = "invalid value for 'SessionTypeId', must be bigger than or equal to 1.";
        }

        if ($this->container['Active'] === null) {
            $invalidProperties[] = "'Active' can't be null";
        }
        return $invalidProperties;
    }


    /**
     * Gets StaffId
     *
     * @return int
     */
    public function getStaffId()
    {
        return $this->container['StaffId'];
    }

    /**
     * Sets StaffId
     *
     * @param int $StaffId The ID of the staff member session type is getting assigned to. The staff member must be assignable to appointments or already be assigned to the session type in the request.
     *
     * @return $this
     */
    public function setStaffId($StaffId): self
    {

        if (($StaffId < 1)) {
            throw new \InvalidArgumentException('invalid value for $StaffId when calling AssignStaffSessionTypeRequest., must be bigger than or equal to 1.');
        }

        $this->container['StaffId'] = $StaffId;

        return $this;
    }

    /**
     * Gets SessionTypeId
     *
     * @return int
     */
    public function getSessionTypeId()
    {
        return $this->container['SessionTypeId'];
    }

    /**
     * Sets SessionTypeId
     *
     * @param int $SessionTypeId The ID of the session type that is getting assigned to the staff member. The session type must be an appointment.
     *
     * @return $this
     */
    public function setSessionTypeId($SessionTypeId): self
    {

        if (($SessionTypeId > 2147483647)) {
            throw new \InvalidArgumentException('invalid value for $SessionTypeId when calling AssignStaffSessionTypeRequest., must be smaller than or equal to 2147483647.');
        }
        if (($SessionTypeId < 1)) {
            throw new \InvalidArgumentException('invalid value for $SessionTypeId when calling AssignStaffSessionTypeRequest., must be bigger than or equal to 1.');
        }

        $this->container['SessionTypeId'] = $SessionTypeId;

        return $this;
    }

    /**
     * Gets Active
     *
     * @return bool
     */
    public function getActive()
    {
        return $this->container['Active'];
    }

    /**
     * Sets Active
     *
     * @param bool $Active Indicates if assignment is active. Passing `false` is equivalent to deleting the assignment.
     *
     * @return $this
     */
    public function setActive($Active): self
    {
        $this->container['Active'] = $Active;

        return $this;
    }

    /**
     * Gets TimeLength
     *
     * @return int
     */
    public function getTimeLength()
    {
        return $this->container['TimeLength'];
    }

    /**
     * Sets TimeLength
     *
     * @param int $TimeLength The staff specific amount of time that a session of this type typically lasts.
     *
     * @return $this
     */
    public function setTimeLength($TimeLength): self
    {
        $this->container['TimeLength'] = $TimeLength;

        return $this;
    }

    /**
     * Gets PrepTime
     *
     * @return int
     */
    public function getPrepTime()
    {
        return $this->container['PrepTime'];
    }

    /**
     * Sets PrepTime
     *
     * @param int $PrepTime Prep time in minutes
     *
     * @return $this
     */
    public function setPrepTime($PrepTime): self
    {
        $this->container['PrepTime'] = $PrepTime;

        return $this;
    }

    /**
     * Gets FinishTime
     *
     * @return int
     */
    public function getFinishTime()
    {
        return $this->container['FinishTime'];
    }

    /**
     * Sets FinishTime
     *
     * @param int $FinishTime Finish time in minutes
     *
     * @return $this
     */
    public function setFinishTime($FinishTime): self
    {
        $this->container['FinishTime'] = $FinishTime;

        return $this;
    }

    /**
     * Gets PayRateType
     *
     * @return string
     */
    public function getPayRateType()
    {
        return $this->container['PayRateType'];
    }

    /**
     * Sets PayRateType
     *
     * @param string $PayRateType The pay rate type. Can be one of the following (case insensitive):     Percent     Flat     No Pay     If PayRateType is not provided in the request and the request is creating a completely new assignment (not editing an existing active or inactive assignment), then the staff member default pay rate and pay rate amount are used to create the assignment. Otherwise, the existing assignment values are used for any optional request parameters not included in the request.
     *
     * @return $this
     */
    public function setPayRateType($PayRateType): self
    {
        $this->container['PayRateType'] = $PayRateType;

        return $this;
    }

    /**
     * Gets PayRateAmount
     *
     * @return double
     */
    public function getPayRateAmount()
    {
        return $this->container['PayRateAmount'];
    }

    /**
     * Sets PayRateAmount
     *
     * @param double $PayRateAmount The pay rate amount for the specific staff member. It is parsed according to the PayRateType.
     *
     * @return $this
     */
    public function setPayRateAmount($PayRateAmount): self
    {
        $this->container['PayRateAmount'] = $PayRateAmount;

        return $this;
    }
    
}


