<?php
/**
 * Availability
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.50
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Nlocascio\Mindbody\Model;

/**
 * Availability Class Doc Comment
 *
 * @category Class
 * @description The availability of a specific staff
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 * @property int $Id Id of the availability
 * @property \Nlocascio\Mindbody\Model\Staff $Staff Availabilities staff.
 * @property \Nlocascio\Mindbody\Model\SessionType $SessionType Availabilities session type.
 * @property \Nlocascio\Mindbody\Model\Program[] $Programs Availabilities program list.
 * @property \DateTime $StartDateTime Availabilities start date and time.
 * @property \DateTime $EndDateTime Availabilities end date and time.
 * @property \DateTime $BookableEndDateTime Availabilities bookable end date and time.
 * @property \Nlocascio\Mindbody\Model\Location $Location Availabilities location.
 * @property int $PrepTime Appointment prep time
 * @property int $FinishTime Appointment finish time
 * @property bool $IsMasked IsMasked
 * @property bool $ShowPublic ShowPublic
 *
 */
class Availability extends BaseModel implements ModelWithId
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Availability';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'Id' => 'int',
        'Staff' => '\Nlocascio\Mindbody\Model\Staff',
        'SessionType' => '\Nlocascio\Mindbody\Model\SessionType',
        'Programs' => '\Nlocascio\Mindbody\Model\Program[]',
        'StartDateTime' => '\DateTime',
        'EndDateTime' => '\DateTime',
        'BookableEndDateTime' => '\DateTime',
        'Location' => '\Nlocascio\Mindbody\Model\Location',
        'PrepTime' => 'int',
        'FinishTime' => 'int',
        'IsMasked' => 'bool',
        'ShowPublic' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static $swaggerFormats = [
        'Id' => 'int32',
        'Staff' => null,
        'SessionType' => null,
        'Programs' => null,
        'StartDateTime' => 'date-time',
        'EndDateTime' => 'date-time',
        'BookableEndDateTime' => 'date-time',
        'Location' => null,
        'PrepTime' => 'int32',
        'FinishTime' => 'int32',
        'IsMasked' => null,
        'ShowPublic' => null
    ];


    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'Id' => 'Id',
        'Staff' => 'Staff',
        'SessionType' => 'SessionType',
        'Programs' => 'Programs',
        'StartDateTime' => 'StartDateTime',
        'EndDateTime' => 'EndDateTime',
        'BookableEndDateTime' => 'BookableEndDateTime',
        'Location' => 'Location',
        'PrepTime' => 'PrepTime',
        'FinishTime' => 'FinishTime',
        'IsMasked' => 'IsMasked',
        'ShowPublic' => 'ShowPublic'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'Id' => 'setId',
        'Staff' => 'setStaff',
        'SessionType' => 'setSessionType',
        'Programs' => 'setPrograms',
        'StartDateTime' => 'setStartDateTime',
        'EndDateTime' => 'setEndDateTime',
        'BookableEndDateTime' => 'setBookableEndDateTime',
        'Location' => 'setLocation',
        'PrepTime' => 'setPrepTime',
        'FinishTime' => 'setFinishTime',
        'IsMasked' => 'setIsMasked',
        'ShowPublic' => 'setShowPublic'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'Id' => 'getId',
        'Staff' => 'getStaff',
        'SessionType' => 'getSessionType',
        'Programs' => 'getPrograms',
        'StartDateTime' => 'getStartDateTime',
        'EndDateTime' => 'getEndDateTime',
        'BookableEndDateTime' => 'getBookableEndDateTime',
        'Location' => 'getLocation',
        'PrepTime' => 'getPrepTime',
        'FinishTime' => 'getFinishTime',
        'IsMasked' => 'getIsMasked',
        'ShowPublic' => 'getShowPublic'
    ];


    

    

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['Id'] = isset($data['Id']) ? $data['Id'] : null;
        $this->container['Staff'] = isset($data['Staff']) ? $data['Staff'] : null;
        $this->container['SessionType'] = isset($data['SessionType']) ? $data['SessionType'] : null;
        $this->container['Programs'] = isset($data['Programs']) ? $data['Programs'] : null;
        $this->container['StartDateTime'] = isset($data['StartDateTime']) ? $data['StartDateTime'] : null;
        $this->container['EndDateTime'] = isset($data['EndDateTime']) ? $data['EndDateTime'] : null;
        $this->container['BookableEndDateTime'] = isset($data['BookableEndDateTime']) ? $data['BookableEndDateTime'] : null;
        $this->container['Location'] = isset($data['Location']) ? $data['Location'] : null;
        $this->container['PrepTime'] = isset($data['PrepTime']) ? $data['PrepTime'] : null;
        $this->container['FinishTime'] = isset($data['FinishTime']) ? $data['FinishTime'] : null;
        $this->container['IsMasked'] = isset($data['IsMasked']) ? $data['IsMasked'] : null;
        $this->container['ShowPublic'] = isset($data['ShowPublic']) ? $data['ShowPublic'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = parent::listInvalidProperties();

        return $invalidProperties;
    }


    /**
     * Gets Id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['Id'];
    }

    /**
     * Sets Id
     *
     * @param int $Id Id of the availability
     *
     * @return $this
     */
    public function setId($Id): self
    {
        $this->container['Id'] = $Id;

        return $this;
    }

    /**
     * Gets Staff
     *
     * @return \Nlocascio\Mindbody\Model\Staff
     */
    public function getStaff()
    {
        return $this->container['Staff'];
    }

    /**
     * Sets Staff
     *
     * @param \Nlocascio\Mindbody\Model\Staff $Staff Availabilities staff.
     *
     * @return $this
     */
    public function setStaff($Staff): self
    {
        $this->container['Staff'] = $Staff;

        return $this;
    }

    /**
     * Gets SessionType
     *
     * @return \Nlocascio\Mindbody\Model\SessionType
     */
    public function getSessionType()
    {
        return $this->container['SessionType'];
    }

    /**
     * Sets SessionType
     *
     * @param \Nlocascio\Mindbody\Model\SessionType $SessionType Availabilities session type.
     *
     * @return $this
     */
    public function setSessionType($SessionType): self
    {
        $this->container['SessionType'] = $SessionType;

        return $this;
    }

    /**
     * Gets Programs
     *
     * @return \Nlocascio\Mindbody\Model\Program[]
     */
    public function getPrograms()
    {
        return $this->container['Programs'];
    }

    /**
     * Sets Programs
     *
     * @param \Nlocascio\Mindbody\Model\Program[] $Programs Availabilities program list.
     *
     * @return $this
     */
    public function setPrograms($Programs): self
    {
        $this->container['Programs'] = $Programs;

        return $this;
    }

    /**
     * Gets StartDateTime
     *
     * @return \DateTime
     */
    public function getStartDateTime()
    {
        return $this->container['StartDateTime'];
    }

    /**
     * Sets StartDateTime
     *
     * @param \DateTime $StartDateTime Availabilities start date and time.
     *
     * @return $this
     */
    public function setStartDateTime($StartDateTime): self
    {
        $this->container['StartDateTime'] = $StartDateTime;

        return $this;
    }

    /**
     * Gets EndDateTime
     *
     * @return \DateTime
     */
    public function getEndDateTime()
    {
        return $this->container['EndDateTime'];
    }

    /**
     * Sets EndDateTime
     *
     * @param \DateTime $EndDateTime Availabilities end date and time.
     *
     * @return $this
     */
    public function setEndDateTime($EndDateTime): self
    {
        $this->container['EndDateTime'] = $EndDateTime;

        return $this;
    }

    /**
     * Gets BookableEndDateTime
     *
     * @return \DateTime
     */
    public function getBookableEndDateTime()
    {
        return $this->container['BookableEndDateTime'];
    }

    /**
     * Sets BookableEndDateTime
     *
     * @param \DateTime $BookableEndDateTime Availabilities bookable end date and time.
     *
     * @return $this
     */
    public function setBookableEndDateTime($BookableEndDateTime): self
    {
        $this->container['BookableEndDateTime'] = $BookableEndDateTime;

        return $this;
    }

    /**
     * Gets Location
     *
     * @return \Nlocascio\Mindbody\Model\Location
     */
    public function getLocation()
    {
        return $this->container['Location'];
    }

    /**
     * Sets Location
     *
     * @param \Nlocascio\Mindbody\Model\Location $Location Availabilities location.
     *
     * @return $this
     */
    public function setLocation($Location): self
    {
        $this->container['Location'] = $Location;

        return $this;
    }

    /**
     * Gets PrepTime
     *
     * @return int
     */
    public function getPrepTime()
    {
        return $this->container['PrepTime'];
    }

    /**
     * Sets PrepTime
     *
     * @param int $PrepTime Appointment prep time
     *
     * @return $this
     */
    public function setPrepTime($PrepTime): self
    {
        $this->container['PrepTime'] = $PrepTime;

        return $this;
    }

    /**
     * Gets FinishTime
     *
     * @return int
     */
    public function getFinishTime()
    {
        return $this->container['FinishTime'];
    }

    /**
     * Sets FinishTime
     *
     * @param int $FinishTime Appointment finish time
     *
     * @return $this
     */
    public function setFinishTime($FinishTime): self
    {
        $this->container['FinishTime'] = $FinishTime;

        return $this;
    }

    /**
     * Gets IsMasked
     *
     * @return bool
     */
    public function getIsMasked()
    {
        return $this->container['IsMasked'];
    }

    /**
     * Sets IsMasked
     *
     * @param bool $IsMasked IsMasked
     *
     * @return $this
     */
    public function setIsMasked($IsMasked): self
    {
        $this->container['IsMasked'] = $IsMasked;

        return $this;
    }

    /**
     * Gets ShowPublic
     *
     * @return bool
     */
    public function getShowPublic()
    {
        return $this->container['ShowPublic'];
    }

    /**
     * Sets ShowPublic
     *
     * @param bool $ShowPublic ShowPublic
     *
     * @return $this
     */
    public function setShowPublic($ShowPublic): self
    {
        $this->container['ShowPublic'] = $ShowPublic;

        return $this;
    }
    
}


