<?php
/**
 * ClassSchedule
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.28
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Nlocascio\Mindbody\Model;

/**
 * ClassSchedule Class Doc Comment
 *
 * @category Class
 * @description Represents a single class instance. The class meets at the start time, goes until the end time.
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 * @property \Nlocascio\Mindbody\Model\ModelClass[] $Classes Contains information about classes.
 * @property \Nlocascio\Mindbody\Model\Client[] $Clients Contains information about clients.
 * @property \Nlocascio\Mindbody\Model\Course $Course Contains information about the course that the enrollment is a part of.
 * @property int $SemesterId The semester ID for the enrollment (if any).
 * @property bool $IsAvailable When `true`, indicates that the enrollment shows in consumer mode, has not started yet, and there is room in each class of the enrollment.<br />  When `false`, indicates that either the enrollment does not show in consumer mode, has already started, or there is no room in some classes of the enrollment.
 * @property int $Id The unique ID of the class schedule.
 * @property \Nlocascio\Mindbody\Model\ClassDescription $ClassDescription Contains information about the class.
 * @property bool $DaySunday When `true`, indicates that this schedule occurs on Sundays.
 * @property bool $DayMonday When `true`, indicates that this schedule occurs on Mondays.
 * @property bool $DayTuesday When `true`, indicates that this schedule occurs on Tuesdays.
 * @property bool $DayWednesday When `true`, indicates that this schedule occurs on Wednesdays.
 * @property bool $DayThursday When `true`, indicates that this schedule occurs on Thursdays.
 * @property bool $DayFriday When `true`, indicates that this schedule occurs on Fridays.
 * @property bool $DaySaturday When `true`, indicates that this schedule occurs on Saturdays.
 * @property bool $AllowOpenEnrollment When `true`, indicates that the enrollment allows booking after the enrollment has started.
 * @property bool $AllowDateForwardEnrollment When `true`, indicates that this the enrollment shows in consumer mode, the enrollment has not started yet, and there is room in each class of the enrollment.
 * @property \DateTime $StartTime The time this class schedule starts.
 * @property \DateTime $EndTime The time this class schedule ends.
 * @property \DateTime $StartDate The date this class schedule starts.
 * @property \DateTime $EndDate The date this class schedule ends.
 * @property \Nlocascio\Mindbody\Model\Staff $Staff Contains information about the staff member who is regularly scheduled to teach the class.
 * @property \Nlocascio\Mindbody\Model\Location $Location Contains information about the regularly scheduled location of this class.
 *
 */
class ClassSchedule extends BaseModel implements ModelWithId
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ClassSchedule';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'Classes' => '\Nlocascio\Mindbody\Model\ModelClass[]',
        'Clients' => '\Nlocascio\Mindbody\Model\Client[]',
        'Course' => '\Nlocascio\Mindbody\Model\Course',
        'SemesterId' => 'int',
        'IsAvailable' => 'bool',
        'Id' => 'int',
        'ClassDescription' => '\Nlocascio\Mindbody\Model\ClassDescription',
        'DaySunday' => 'bool',
        'DayMonday' => 'bool',
        'DayTuesday' => 'bool',
        'DayWednesday' => 'bool',
        'DayThursday' => 'bool',
        'DayFriday' => 'bool',
        'DaySaturday' => 'bool',
        'AllowOpenEnrollment' => 'bool',
        'AllowDateForwardEnrollment' => 'bool',
        'StartTime' => '\DateTime',
        'EndTime' => '\DateTime',
        'StartDate' => '\DateTime',
        'EndDate' => '\DateTime',
        'Staff' => '\Nlocascio\Mindbody\Model\Staff',
        'Location' => '\Nlocascio\Mindbody\Model\Location'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static $swaggerFormats = [
        'Classes' => null,
        'Clients' => null,
        'Course' => null,
        'SemesterId' => 'int32',
        'IsAvailable' => null,
        'Id' => 'int32',
        'ClassDescription' => null,
        'DaySunday' => null,
        'DayMonday' => null,
        'DayTuesday' => null,
        'DayWednesday' => null,
        'DayThursday' => null,
        'DayFriday' => null,
        'DaySaturday' => null,
        'AllowOpenEnrollment' => null,
        'AllowDateForwardEnrollment' => null,
        'StartTime' => 'date-time',
        'EndTime' => 'date-time',
        'StartDate' => 'date-time',
        'EndDate' => 'date-time',
        'Staff' => null,
        'Location' => null
    ];


    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'Classes' => 'Classes',
        'Clients' => 'Clients',
        'Course' => 'Course',
        'SemesterId' => 'SemesterId',
        'IsAvailable' => 'IsAvailable',
        'Id' => 'Id',
        'ClassDescription' => 'ClassDescription',
        'DaySunday' => 'DaySunday',
        'DayMonday' => 'DayMonday',
        'DayTuesday' => 'DayTuesday',
        'DayWednesday' => 'DayWednesday',
        'DayThursday' => 'DayThursday',
        'DayFriday' => 'DayFriday',
        'DaySaturday' => 'DaySaturday',
        'AllowOpenEnrollment' => 'AllowOpenEnrollment',
        'AllowDateForwardEnrollment' => 'AllowDateForwardEnrollment',
        'StartTime' => 'StartTime',
        'EndTime' => 'EndTime',
        'StartDate' => 'StartDate',
        'EndDate' => 'EndDate',
        'Staff' => 'Staff',
        'Location' => 'Location'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'Classes' => 'setClasses',
        'Clients' => 'setClients',
        'Course' => 'setCourse',
        'SemesterId' => 'setSemesterId',
        'IsAvailable' => 'setIsAvailable',
        'Id' => 'setId',
        'ClassDescription' => 'setClassDescription',
        'DaySunday' => 'setDaySunday',
        'DayMonday' => 'setDayMonday',
        'DayTuesday' => 'setDayTuesday',
        'DayWednesday' => 'setDayWednesday',
        'DayThursday' => 'setDayThursday',
        'DayFriday' => 'setDayFriday',
        'DaySaturday' => 'setDaySaturday',
        'AllowOpenEnrollment' => 'setAllowOpenEnrollment',
        'AllowDateForwardEnrollment' => 'setAllowDateForwardEnrollment',
        'StartTime' => 'setStartTime',
        'EndTime' => 'setEndTime',
        'StartDate' => 'setStartDate',
        'EndDate' => 'setEndDate',
        'Staff' => 'setStaff',
        'Location' => 'setLocation'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'Classes' => 'getClasses',
        'Clients' => 'getClients',
        'Course' => 'getCourse',
        'SemesterId' => 'getSemesterId',
        'IsAvailable' => 'getIsAvailable',
        'Id' => 'getId',
        'ClassDescription' => 'getClassDescription',
        'DaySunday' => 'getDaySunday',
        'DayMonday' => 'getDayMonday',
        'DayTuesday' => 'getDayTuesday',
        'DayWednesday' => 'getDayWednesday',
        'DayThursday' => 'getDayThursday',
        'DayFriday' => 'getDayFriday',
        'DaySaturday' => 'getDaySaturday',
        'AllowOpenEnrollment' => 'getAllowOpenEnrollment',
        'AllowDateForwardEnrollment' => 'getAllowDateForwardEnrollment',
        'StartTime' => 'getStartTime',
        'EndTime' => 'getEndTime',
        'StartDate' => 'getStartDate',
        'EndDate' => 'getEndDate',
        'Staff' => 'getStaff',
        'Location' => 'getLocation'
    ];


    

    

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['Classes'] = isset($data['Classes']) ? $data['Classes'] : null;
        $this->container['Clients'] = isset($data['Clients']) ? $data['Clients'] : null;
        $this->container['Course'] = isset($data['Course']) ? $data['Course'] : null;
        $this->container['SemesterId'] = isset($data['SemesterId']) ? $data['SemesterId'] : null;
        $this->container['IsAvailable'] = isset($data['IsAvailable']) ? $data['IsAvailable'] : null;
        $this->container['Id'] = isset($data['Id']) ? $data['Id'] : null;
        $this->container['ClassDescription'] = isset($data['ClassDescription']) ? $data['ClassDescription'] : null;
        $this->container['DaySunday'] = isset($data['DaySunday']) ? $data['DaySunday'] : null;
        $this->container['DayMonday'] = isset($data['DayMonday']) ? $data['DayMonday'] : null;
        $this->container['DayTuesday'] = isset($data['DayTuesday']) ? $data['DayTuesday'] : null;
        $this->container['DayWednesday'] = isset($data['DayWednesday']) ? $data['DayWednesday'] : null;
        $this->container['DayThursday'] = isset($data['DayThursday']) ? $data['DayThursday'] : null;
        $this->container['DayFriday'] = isset($data['DayFriday']) ? $data['DayFriday'] : null;
        $this->container['DaySaturday'] = isset($data['DaySaturday']) ? $data['DaySaturday'] : null;
        $this->container['AllowOpenEnrollment'] = isset($data['AllowOpenEnrollment']) ? $data['AllowOpenEnrollment'] : null;
        $this->container['AllowDateForwardEnrollment'] = isset($data['AllowDateForwardEnrollment']) ? $data['AllowDateForwardEnrollment'] : null;
        $this->container['StartTime'] = isset($data['StartTime']) ? $data['StartTime'] : null;
        $this->container['EndTime'] = isset($data['EndTime']) ? $data['EndTime'] : null;
        $this->container['StartDate'] = isset($data['StartDate']) ? $data['StartDate'] : null;
        $this->container['EndDate'] = isset($data['EndDate']) ? $data['EndDate'] : null;
        $this->container['Staff'] = isset($data['Staff']) ? $data['Staff'] : null;
        $this->container['Location'] = isset($data['Location']) ? $data['Location'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = parent::listInvalidProperties();

        return $invalidProperties;
    }


    /**
     * Gets Classes
     *
     * @return \Nlocascio\Mindbody\Model\ModelClass[]
     */
    public function getClasses()
    {
        return $this->container['Classes'];
    }

    /**
     * Sets Classes
     *
     * @param \Nlocascio\Mindbody\Model\ModelClass[] $Classes Contains information about classes.
     *
     * @return $this
     */
    public function setClasses($Classes): self
    {
        $this->container['Classes'] = $Classes;

        return $this;
    }

    /**
     * Gets Clients
     *
     * @return \Nlocascio\Mindbody\Model\Client[]
     */
    public function getClients()
    {
        return $this->container['Clients'];
    }

    /**
     * Sets Clients
     *
     * @param \Nlocascio\Mindbody\Model\Client[] $Clients Contains information about clients.
     *
     * @return $this
     */
    public function setClients($Clients): self
    {
        $this->container['Clients'] = $Clients;

        return $this;
    }

    /**
     * Gets Course
     *
     * @return \Nlocascio\Mindbody\Model\Course
     */
    public function getCourse()
    {
        return $this->container['Course'];
    }

    /**
     * Sets Course
     *
     * @param \Nlocascio\Mindbody\Model\Course $Course Contains information about the course that the enrollment is a part of.
     *
     * @return $this
     */
    public function setCourse($Course): self
    {
        $this->container['Course'] = $Course;

        return $this;
    }

    /**
     * Gets SemesterId
     *
     * @return int
     */
    public function getSemesterId()
    {
        return $this->container['SemesterId'];
    }

    /**
     * Sets SemesterId
     *
     * @param int $SemesterId The semester ID for the enrollment (if any).
     *
     * @return $this
     */
    public function setSemesterId($SemesterId): self
    {
        $this->container['SemesterId'] = $SemesterId;

        return $this;
    }

    /**
     * Gets IsAvailable
     *
     * @return bool
     */
    public function getIsAvailable()
    {
        return $this->container['IsAvailable'];
    }

    /**
     * Sets IsAvailable
     *
     * @param bool $IsAvailable When `true`, indicates that the enrollment shows in consumer mode, has not started yet, and there is room in each class of the enrollment.<br />  When `false`, indicates that either the enrollment does not show in consumer mode, has already started, or there is no room in some classes of the enrollment.
     *
     * @return $this
     */
    public function setIsAvailable($IsAvailable): self
    {
        $this->container['IsAvailable'] = $IsAvailable;

        return $this;
    }

    /**
     * Gets Id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['Id'];
    }

    /**
     * Sets Id
     *
     * @param int $Id The unique ID of the class schedule.
     *
     * @return $this
     */
    public function setId($Id): self
    {
        $this->container['Id'] = $Id;

        return $this;
    }

    /**
     * Gets ClassDescription
     *
     * @return \Nlocascio\Mindbody\Model\ClassDescription
     */
    public function getClassDescription()
    {
        return $this->container['ClassDescription'];
    }

    /**
     * Sets ClassDescription
     *
     * @param \Nlocascio\Mindbody\Model\ClassDescription $ClassDescription Contains information about the class.
     *
     * @return $this
     */
    public function setClassDescription($ClassDescription): self
    {
        $this->container['ClassDescription'] = $ClassDescription;

        return $this;
    }

    /**
     * Gets DaySunday
     *
     * @return bool
     */
    public function getDaySunday()
    {
        return $this->container['DaySunday'];
    }

    /**
     * Sets DaySunday
     *
     * @param bool $DaySunday When `true`, indicates that this schedule occurs on Sundays.
     *
     * @return $this
     */
    public function setDaySunday($DaySunday): self
    {
        $this->container['DaySunday'] = $DaySunday;

        return $this;
    }

    /**
     * Gets DayMonday
     *
     * @return bool
     */
    public function getDayMonday()
    {
        return $this->container['DayMonday'];
    }

    /**
     * Sets DayMonday
     *
     * @param bool $DayMonday When `true`, indicates that this schedule occurs on Mondays.
     *
     * @return $this
     */
    public function setDayMonday($DayMonday): self
    {
        $this->container['DayMonday'] = $DayMonday;

        return $this;
    }

    /**
     * Gets DayTuesday
     *
     * @return bool
     */
    public function getDayTuesday()
    {
        return $this->container['DayTuesday'];
    }

    /**
     * Sets DayTuesday
     *
     * @param bool $DayTuesday When `true`, indicates that this schedule occurs on Tuesdays.
     *
     * @return $this
     */
    public function setDayTuesday($DayTuesday): self
    {
        $this->container['DayTuesday'] = $DayTuesday;

        return $this;
    }

    /**
     * Gets DayWednesday
     *
     * @return bool
     */
    public function getDayWednesday()
    {
        return $this->container['DayWednesday'];
    }

    /**
     * Sets DayWednesday
     *
     * @param bool $DayWednesday When `true`, indicates that this schedule occurs on Wednesdays.
     *
     * @return $this
     */
    public function setDayWednesday($DayWednesday): self
    {
        $this->container['DayWednesday'] = $DayWednesday;

        return $this;
    }

    /**
     * Gets DayThursday
     *
     * @return bool
     */
    public function getDayThursday()
    {
        return $this->container['DayThursday'];
    }

    /**
     * Sets DayThursday
     *
     * @param bool $DayThursday When `true`, indicates that this schedule occurs on Thursdays.
     *
     * @return $this
     */
    public function setDayThursday($DayThursday): self
    {
        $this->container['DayThursday'] = $DayThursday;

        return $this;
    }

    /**
     * Gets DayFriday
     *
     * @return bool
     */
    public function getDayFriday()
    {
        return $this->container['DayFriday'];
    }

    /**
     * Sets DayFriday
     *
     * @param bool $DayFriday When `true`, indicates that this schedule occurs on Fridays.
     *
     * @return $this
     */
    public function setDayFriday($DayFriday): self
    {
        $this->container['DayFriday'] = $DayFriday;

        return $this;
    }

    /**
     * Gets DaySaturday
     *
     * @return bool
     */
    public function getDaySaturday()
    {
        return $this->container['DaySaturday'];
    }

    /**
     * Sets DaySaturday
     *
     * @param bool $DaySaturday When `true`, indicates that this schedule occurs on Saturdays.
     *
     * @return $this
     */
    public function setDaySaturday($DaySaturday): self
    {
        $this->container['DaySaturday'] = $DaySaturday;

        return $this;
    }

    /**
     * Gets AllowOpenEnrollment
     *
     * @return bool
     */
    public function getAllowOpenEnrollment()
    {
        return $this->container['AllowOpenEnrollment'];
    }

    /**
     * Sets AllowOpenEnrollment
     *
     * @param bool $AllowOpenEnrollment When `true`, indicates that the enrollment allows booking after the enrollment has started.
     *
     * @return $this
     */
    public function setAllowOpenEnrollment($AllowOpenEnrollment): self
    {
        $this->container['AllowOpenEnrollment'] = $AllowOpenEnrollment;

        return $this;
    }

    /**
     * Gets AllowDateForwardEnrollment
     *
     * @return bool
     */
    public function getAllowDateForwardEnrollment()
    {
        return $this->container['AllowDateForwardEnrollment'];
    }

    /**
     * Sets AllowDateForwardEnrollment
     *
     * @param bool $AllowDateForwardEnrollment When `true`, indicates that this the enrollment shows in consumer mode, the enrollment has not started yet, and there is room in each class of the enrollment.
     *
     * @return $this
     */
    public function setAllowDateForwardEnrollment($AllowDateForwardEnrollment): self
    {
        $this->container['AllowDateForwardEnrollment'] = $AllowDateForwardEnrollment;

        return $this;
    }

    /**
     * Gets StartTime
     *
     * @return \DateTime
     */
    public function getStartTime()
    {
        return $this->container['StartTime'];
    }

    /**
     * Sets StartTime
     *
     * @param \DateTime $StartTime The time this class schedule starts.
     *
     * @return $this
     */
    public function setStartTime($StartTime): self
    {
        $this->container['StartTime'] = $StartTime;

        return $this;
    }

    /**
     * Gets EndTime
     *
     * @return \DateTime
     */
    public function getEndTime()
    {
        return $this->container['EndTime'];
    }

    /**
     * Sets EndTime
     *
     * @param \DateTime $EndTime The time this class schedule ends.
     *
     * @return $this
     */
    public function setEndTime($EndTime): self
    {
        $this->container['EndTime'] = $EndTime;

        return $this;
    }

    /**
     * Gets StartDate
     *
     * @return \DateTime
     */
    public function getStartDate()
    {
        return $this->container['StartDate'];
    }

    /**
     * Sets StartDate
     *
     * @param \DateTime $StartDate The date this class schedule starts.
     *
     * @return $this
     */
    public function setStartDate($StartDate): self
    {
        $this->container['StartDate'] = $StartDate;

        return $this;
    }

    /**
     * Gets EndDate
     *
     * @return \DateTime
     */
    public function getEndDate()
    {
        return $this->container['EndDate'];
    }

    /**
     * Sets EndDate
     *
     * @param \DateTime $EndDate The date this class schedule ends.
     *
     * @return $this
     */
    public function setEndDate($EndDate): self
    {
        $this->container['EndDate'] = $EndDate;

        return $this;
    }

    /**
     * Gets Staff
     *
     * @return \Nlocascio\Mindbody\Model\Staff
     */
    public function getStaff()
    {
        return $this->container['Staff'];
    }

    /**
     * Sets Staff
     *
     * @param \Nlocascio\Mindbody\Model\Staff $Staff Contains information about the staff member who is regularly scheduled to teach the class.
     *
     * @return $this
     */
    public function setStaff($Staff): self
    {
        $this->container['Staff'] = $Staff;

        return $this;
    }

    /**
     * Gets Location
     *
     * @return \Nlocascio\Mindbody\Model\Location
     */
    public function getLocation()
    {
        return $this->container['Location'];
    }

    /**
     * Sets Location
     *
     * @param \Nlocascio\Mindbody\Model\Location $Location Contains information about the regularly scheduled location of this class.
     *
     * @return $this
     */
    public function setLocation($Location): self
    {
        $this->container['Location'] = $Location;

        return $this;
    }
    
}


