<?php
/**
 * ClientRelationship
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.23
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Nlocascio\Mindbody\Model;

/**
 * ClientRelationship Class Doc Comment
 *
 * @category Class
 * @description A relation between two clients.
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ClientRelationship extends BaseModel
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ClientRelationship';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'RelatedClientId' => 'string',
        'Relationship' => '\Nlocascio\Mindbody\Model\Relationship',
        'RelationshipName' => 'string',
        'Delete' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'RelatedClientId' => null,
        'Relationship' => null,
        'RelationshipName' => null,
        'Delete' => null
    ];


    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'RelatedClientId' => 'RelatedClientId',
        'Relationship' => 'Relationship',
        'RelationshipName' => 'RelationshipName',
        'Delete' => 'Delete'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'RelatedClientId' => 'setRelatedClientId',
        'Relationship' => 'setRelationship',
        'RelationshipName' => 'setRelationshipName',
        'Delete' => 'setDelete'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'RelatedClientId' => 'getRelatedClientId',
        'Relationship' => 'getRelationship',
        'RelationshipName' => 'getRelationshipName',
        'Delete' => 'getDelete'
    ];


    

    

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['RelatedClientId'] = isset($data['RelatedClientId']) ? $data['RelatedClientId'] : null;
        $this->container['Relationship'] = isset($data['Relationship']) ? $data['Relationship'] : null;
        $this->container['RelationshipName'] = isset($data['RelationshipName']) ? $data['RelationshipName'] : null;
        $this->container['Delete'] = isset($data['Delete']) ? $data['Delete'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = parent::listInvalidProperties();

        return $invalidProperties;
    }


    /**
     * Gets RelatedClientId
     *
     * @return string
     */
    public function getRelatedClientId()
    {
        return $this->container['RelatedClientId'];
    }

    /**
     * Sets RelatedClientId
     *
     * @param string $RelatedClientId The RSSID of the related client.
     *
     * @return $this
     */
    public function setRelatedClientId($RelatedClientId): self
    {
        $this->container['RelatedClientId'] = $RelatedClientId;

        return $this;
    }

    /**
     * Gets Relationship
     *
     * @return \Nlocascio\Mindbody\Model\Relationship
     */
    public function getRelationship()
    {
        return $this->container['Relationship'];
    }

    /**
     * Sets Relationship
     *
     * @param \Nlocascio\Mindbody\Model\Relationship $Relationship Contains details about the relationship between two clients.
     *
     * @return $this
     */
    public function setRelationship($Relationship): self
    {
        $this->container['Relationship'] = $Relationship;

        return $this;
    }

    /**
     * Gets RelationshipName
     *
     * @return string
     */
    public function getRelationshipName()
    {
        return $this->container['RelationshipName'];
    }

    /**
     * Sets RelationshipName
     *
     * @param string $RelationshipName The name of the relationship of the related client.
     *
     * @return $this
     */
    public function setRelationshipName($RelationshipName): self
    {
        $this->container['RelationshipName'] = $RelationshipName;

        return $this;
    }

    /**
     * Gets Delete
     *
     * @return bool
     */
    public function getDelete()
    {
        return $this->container['Delete'];
    }

    /**
     * Sets Delete
     *
     * @param bool $Delete When true, this relationship is removed from the associated clients.
     *
     * @return $this
     */
    public function setDelete($Delete): self
    {
        $this->container['Delete'] = $Delete;

        return $this;
    }
    
}


