<?php
/**
 * Contract
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.23
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Nlocascio\Mindbody\Model;

/**
 * Contract Class Doc Comment
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Contract extends BaseModel implements ModelWithId
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Contract';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'Id' => 'int',
        'Name' => 'string',
        'Description' => 'string',
        'AssignsMembershipId' => 'int',
        'AssignsMembershipName' => 'string',
        'SoldOnline' => 'bool',
        'ContractItems' => '\Nlocascio\Mindbody\Model\ContractItem[]',
        'IntroOffer' => 'string',
        'AutopaySchedule' => '\Nlocascio\Mindbody\Model\AutopaySchedule',
        'NumberOfAutopays' => 'int',
        'AutopayTriggerType' => 'string',
        'ActionUponCompletionOfAutopays' => 'string',
        'ClientsChargedOn' => 'string',
        'ClientsChargedOnSpecificDate' => '\DateTime',
        'DiscountAmount' => 'double',
        'DepositAmount' => 'double',
        'FirstAutopayFree' => 'bool',
        'LastAutopayFree' => 'bool',
        'ClientTerminateOnline' => 'bool',
        'MembershipTypeRestrictions' => '\Nlocascio\Mindbody\Model\MembershipTypeRestriction[]',
        'LocationPurchaseRestrictionIds' => 'int[]',
        'LocationPurchaseRestrictionNames' => 'string[]',
        'AgreementTerms' => 'string',
        'RequiresElectronicConfirmation' => 'bool',
        'AutopayEnabled' => 'bool',
        'FirstPaymentAmountSubtotal' => 'double',
        'FirstPaymentAmountTax' => 'double',
        'FirstPaymentAmountTotal' => 'double',
        'RecurringPaymentAmountSubtotal' => 'double',
        'RecurringPaymentAmountTax' => 'double',
        'RecurringPaymentAmountTotal' => 'double',
        'TotalContractAmountSubtotal' => 'double',
        'TotalContractAmountTax' => 'double',
        'TotalContractAmountTotal' => 'double'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<int, string|null>
      */
    protected static $swaggerFormats = [
        'Id' => 'int32',
        'Name' => null,
        'Description' => null,
        'AssignsMembershipId' => 'int32',
        'AssignsMembershipName' => null,
        'SoldOnline' => null,
        'ContractItems' => null,
        'IntroOffer' => null,
        'AutopaySchedule' => null,
        'NumberOfAutopays' => 'int32',
        'AutopayTriggerType' => null,
        'ActionUponCompletionOfAutopays' => null,
        'ClientsChargedOn' => null,
        'ClientsChargedOnSpecificDate' => 'date-time',
        'DiscountAmount' => 'double',
        'DepositAmount' => 'double',
        'FirstAutopayFree' => null,
        'LastAutopayFree' => null,
        'ClientTerminateOnline' => null,
        'MembershipTypeRestrictions' => null,
        'LocationPurchaseRestrictionIds' => 'int32',
        'LocationPurchaseRestrictionNames' => null,
        'AgreementTerms' => null,
        'RequiresElectronicConfirmation' => null,
        'AutopayEnabled' => null,
        'FirstPaymentAmountSubtotal' => 'double',
        'FirstPaymentAmountTax' => 'double',
        'FirstPaymentAmountTotal' => 'double',
        'RecurringPaymentAmountSubtotal' => 'double',
        'RecurringPaymentAmountTax' => 'double',
        'RecurringPaymentAmountTotal' => 'double',
        'TotalContractAmountSubtotal' => 'double',
        'TotalContractAmountTax' => 'double',
        'TotalContractAmountTotal' => 'double'
    ];


    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'Id' => 'Id',
        'Name' => 'Name',
        'Description' => 'Description',
        'AssignsMembershipId' => 'AssignsMembershipId',
        'AssignsMembershipName' => 'AssignsMembershipName',
        'SoldOnline' => 'SoldOnline',
        'ContractItems' => 'ContractItems',
        'IntroOffer' => 'IntroOffer',
        'AutopaySchedule' => 'AutopaySchedule',
        'NumberOfAutopays' => 'NumberOfAutopays',
        'AutopayTriggerType' => 'AutopayTriggerType',
        'ActionUponCompletionOfAutopays' => 'ActionUponCompletionOfAutopays',
        'ClientsChargedOn' => 'ClientsChargedOn',
        'ClientsChargedOnSpecificDate' => 'ClientsChargedOnSpecificDate',
        'DiscountAmount' => 'DiscountAmount',
        'DepositAmount' => 'DepositAmount',
        'FirstAutopayFree' => 'FirstAutopayFree',
        'LastAutopayFree' => 'LastAutopayFree',
        'ClientTerminateOnline' => 'ClientTerminateOnline',
        'MembershipTypeRestrictions' => 'MembershipTypeRestrictions',
        'LocationPurchaseRestrictionIds' => 'LocationPurchaseRestrictionIds',
        'LocationPurchaseRestrictionNames' => 'LocationPurchaseRestrictionNames',
        'AgreementTerms' => 'AgreementTerms',
        'RequiresElectronicConfirmation' => 'RequiresElectronicConfirmation',
        'AutopayEnabled' => 'AutopayEnabled',
        'FirstPaymentAmountSubtotal' => 'FirstPaymentAmountSubtotal',
        'FirstPaymentAmountTax' => 'FirstPaymentAmountTax',
        'FirstPaymentAmountTotal' => 'FirstPaymentAmountTotal',
        'RecurringPaymentAmountSubtotal' => 'RecurringPaymentAmountSubtotal',
        'RecurringPaymentAmountTax' => 'RecurringPaymentAmountTax',
        'RecurringPaymentAmountTotal' => 'RecurringPaymentAmountTotal',
        'TotalContractAmountSubtotal' => 'TotalContractAmountSubtotal',
        'TotalContractAmountTax' => 'TotalContractAmountTax',
        'TotalContractAmountTotal' => 'TotalContractAmountTotal'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'Id' => 'setId',
        'Name' => 'setName',
        'Description' => 'setDescription',
        'AssignsMembershipId' => 'setAssignsMembershipId',
        'AssignsMembershipName' => 'setAssignsMembershipName',
        'SoldOnline' => 'setSoldOnline',
        'ContractItems' => 'setContractItems',
        'IntroOffer' => 'setIntroOffer',
        'AutopaySchedule' => 'setAutopaySchedule',
        'NumberOfAutopays' => 'setNumberOfAutopays',
        'AutopayTriggerType' => 'setAutopayTriggerType',
        'ActionUponCompletionOfAutopays' => 'setActionUponCompletionOfAutopays',
        'ClientsChargedOn' => 'setClientsChargedOn',
        'ClientsChargedOnSpecificDate' => 'setClientsChargedOnSpecificDate',
        'DiscountAmount' => 'setDiscountAmount',
        'DepositAmount' => 'setDepositAmount',
        'FirstAutopayFree' => 'setFirstAutopayFree',
        'LastAutopayFree' => 'setLastAutopayFree',
        'ClientTerminateOnline' => 'setClientTerminateOnline',
        'MembershipTypeRestrictions' => 'setMembershipTypeRestrictions',
        'LocationPurchaseRestrictionIds' => 'setLocationPurchaseRestrictionIds',
        'LocationPurchaseRestrictionNames' => 'setLocationPurchaseRestrictionNames',
        'AgreementTerms' => 'setAgreementTerms',
        'RequiresElectronicConfirmation' => 'setRequiresElectronicConfirmation',
        'AutopayEnabled' => 'setAutopayEnabled',
        'FirstPaymentAmountSubtotal' => 'setFirstPaymentAmountSubtotal',
        'FirstPaymentAmountTax' => 'setFirstPaymentAmountTax',
        'FirstPaymentAmountTotal' => 'setFirstPaymentAmountTotal',
        'RecurringPaymentAmountSubtotal' => 'setRecurringPaymentAmountSubtotal',
        'RecurringPaymentAmountTax' => 'setRecurringPaymentAmountTax',
        'RecurringPaymentAmountTotal' => 'setRecurringPaymentAmountTotal',
        'TotalContractAmountSubtotal' => 'setTotalContractAmountSubtotal',
        'TotalContractAmountTax' => 'setTotalContractAmountTax',
        'TotalContractAmountTotal' => 'setTotalContractAmountTotal'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'Id' => 'getId',
        'Name' => 'getName',
        'Description' => 'getDescription',
        'AssignsMembershipId' => 'getAssignsMembershipId',
        'AssignsMembershipName' => 'getAssignsMembershipName',
        'SoldOnline' => 'getSoldOnline',
        'ContractItems' => 'getContractItems',
        'IntroOffer' => 'getIntroOffer',
        'AutopaySchedule' => 'getAutopaySchedule',
        'NumberOfAutopays' => 'getNumberOfAutopays',
        'AutopayTriggerType' => 'getAutopayTriggerType',
        'ActionUponCompletionOfAutopays' => 'getActionUponCompletionOfAutopays',
        'ClientsChargedOn' => 'getClientsChargedOn',
        'ClientsChargedOnSpecificDate' => 'getClientsChargedOnSpecificDate',
        'DiscountAmount' => 'getDiscountAmount',
        'DepositAmount' => 'getDepositAmount',
        'FirstAutopayFree' => 'getFirstAutopayFree',
        'LastAutopayFree' => 'getLastAutopayFree',
        'ClientTerminateOnline' => 'getClientTerminateOnline',
        'MembershipTypeRestrictions' => 'getMembershipTypeRestrictions',
        'LocationPurchaseRestrictionIds' => 'getLocationPurchaseRestrictionIds',
        'LocationPurchaseRestrictionNames' => 'getLocationPurchaseRestrictionNames',
        'AgreementTerms' => 'getAgreementTerms',
        'RequiresElectronicConfirmation' => 'getRequiresElectronicConfirmation',
        'AutopayEnabled' => 'getAutopayEnabled',
        'FirstPaymentAmountSubtotal' => 'getFirstPaymentAmountSubtotal',
        'FirstPaymentAmountTax' => 'getFirstPaymentAmountTax',
        'FirstPaymentAmountTotal' => 'getFirstPaymentAmountTotal',
        'RecurringPaymentAmountSubtotal' => 'getRecurringPaymentAmountSubtotal',
        'RecurringPaymentAmountTax' => 'getRecurringPaymentAmountTax',
        'RecurringPaymentAmountTotal' => 'getRecurringPaymentAmountTotal',
        'TotalContractAmountSubtotal' => 'getTotalContractAmountSubtotal',
        'TotalContractAmountTax' => 'getTotalContractAmountTax',
        'TotalContractAmountTotal' => 'getTotalContractAmountTotal'
    ];


    

    

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['Id'] = isset($data['Id']) ? $data['Id'] : null;
        $this->container['Name'] = isset($data['Name']) ? $data['Name'] : null;
        $this->container['Description'] = isset($data['Description']) ? $data['Description'] : null;
        $this->container['AssignsMembershipId'] = isset($data['AssignsMembershipId']) ? $data['AssignsMembershipId'] : null;
        $this->container['AssignsMembershipName'] = isset($data['AssignsMembershipName']) ? $data['AssignsMembershipName'] : null;
        $this->container['SoldOnline'] = isset($data['SoldOnline']) ? $data['SoldOnline'] : null;
        $this->container['ContractItems'] = isset($data['ContractItems']) ? $data['ContractItems'] : null;
        $this->container['IntroOffer'] = isset($data['IntroOffer']) ? $data['IntroOffer'] : null;
        $this->container['AutopaySchedule'] = isset($data['AutopaySchedule']) ? $data['AutopaySchedule'] : null;
        $this->container['NumberOfAutopays'] = isset($data['NumberOfAutopays']) ? $data['NumberOfAutopays'] : null;
        $this->container['AutopayTriggerType'] = isset($data['AutopayTriggerType']) ? $data['AutopayTriggerType'] : null;
        $this->container['ActionUponCompletionOfAutopays'] = isset($data['ActionUponCompletionOfAutopays']) ? $data['ActionUponCompletionOfAutopays'] : null;
        $this->container['ClientsChargedOn'] = isset($data['ClientsChargedOn']) ? $data['ClientsChargedOn'] : null;
        $this->container['ClientsChargedOnSpecificDate'] = isset($data['ClientsChargedOnSpecificDate']) ? $data['ClientsChargedOnSpecificDate'] : null;
        $this->container['DiscountAmount'] = isset($data['DiscountAmount']) ? $data['DiscountAmount'] : null;
        $this->container['DepositAmount'] = isset($data['DepositAmount']) ? $data['DepositAmount'] : null;
        $this->container['FirstAutopayFree'] = isset($data['FirstAutopayFree']) ? $data['FirstAutopayFree'] : null;
        $this->container['LastAutopayFree'] = isset($data['LastAutopayFree']) ? $data['LastAutopayFree'] : null;
        $this->container['ClientTerminateOnline'] = isset($data['ClientTerminateOnline']) ? $data['ClientTerminateOnline'] : null;
        $this->container['MembershipTypeRestrictions'] = isset($data['MembershipTypeRestrictions']) ? $data['MembershipTypeRestrictions'] : null;
        $this->container['LocationPurchaseRestrictionIds'] = isset($data['LocationPurchaseRestrictionIds']) ? $data['LocationPurchaseRestrictionIds'] : null;
        $this->container['LocationPurchaseRestrictionNames'] = isset($data['LocationPurchaseRestrictionNames']) ? $data['LocationPurchaseRestrictionNames'] : null;
        $this->container['AgreementTerms'] = isset($data['AgreementTerms']) ? $data['AgreementTerms'] : null;
        $this->container['RequiresElectronicConfirmation'] = isset($data['RequiresElectronicConfirmation']) ? $data['RequiresElectronicConfirmation'] : null;
        $this->container['AutopayEnabled'] = isset($data['AutopayEnabled']) ? $data['AutopayEnabled'] : null;
        $this->container['FirstPaymentAmountSubtotal'] = isset($data['FirstPaymentAmountSubtotal']) ? $data['FirstPaymentAmountSubtotal'] : null;
        $this->container['FirstPaymentAmountTax'] = isset($data['FirstPaymentAmountTax']) ? $data['FirstPaymentAmountTax'] : null;
        $this->container['FirstPaymentAmountTotal'] = isset($data['FirstPaymentAmountTotal']) ? $data['FirstPaymentAmountTotal'] : null;
        $this->container['RecurringPaymentAmountSubtotal'] = isset($data['RecurringPaymentAmountSubtotal']) ? $data['RecurringPaymentAmountSubtotal'] : null;
        $this->container['RecurringPaymentAmountTax'] = isset($data['RecurringPaymentAmountTax']) ? $data['RecurringPaymentAmountTax'] : null;
        $this->container['RecurringPaymentAmountTotal'] = isset($data['RecurringPaymentAmountTotal']) ? $data['RecurringPaymentAmountTotal'] : null;
        $this->container['TotalContractAmountSubtotal'] = isset($data['TotalContractAmountSubtotal']) ? $data['TotalContractAmountSubtotal'] : null;
        $this->container['TotalContractAmountTax'] = isset($data['TotalContractAmountTax']) ? $data['TotalContractAmountTax'] : null;
        $this->container['TotalContractAmountTotal'] = isset($data['TotalContractAmountTotal']) ? $data['TotalContractAmountTotal'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = parent::listInvalidProperties();

        return $invalidProperties;
    }


    /**
     * Gets Id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['Id'];
    }

    /**
     * Sets Id
     *
     * @param int $Id The contract’s ID at the subscriber’s business.
     *
     * @return $this
     */
    public function setId($Id): self
    {
        $this->container['Id'] = $Id;

        return $this;
    }

    /**
     * Gets Name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['Name'];
    }

    /**
     * Sets Name
     *
     * @param string $Name The name of the contract.
     *
     * @return $this
     */
    public function setName($Name): self
    {
        $this->container['Name'] = $Name;

        return $this;
    }

    /**
     * Gets Description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->container['Description'];
    }

    /**
     * Sets Description
     *
     * @param string $Description A description of the contract.
     *
     * @return $this
     */
    public function setDescription($Description): self
    {
        $this->container['Description'] = $Description;

        return $this;
    }

    /**
     * Gets AssignsMembershipId
     *
     * @return int
     */
    public function getAssignsMembershipId()
    {
        return $this->container['AssignsMembershipId'];
    }

    /**
     * Sets AssignsMembershipId
     *
     * @param int $AssignsMembershipId The ID of the membership that was assigned to the client when the client signed up for a contract.
     *
     * @return $this
     */
    public function setAssignsMembershipId($AssignsMembershipId): self
    {
        $this->container['AssignsMembershipId'] = $AssignsMembershipId;

        return $this;
    }

    /**
     * Gets AssignsMembershipName
     *
     * @return string
     */
    public function getAssignsMembershipName()
    {
        return $this->container['AssignsMembershipName'];
    }

    /**
     * Sets AssignsMembershipName
     *
     * @param string $AssignsMembershipName The name of the membership that was assigned to the client when the client signed up for this contract.
     *
     * @return $this
     */
    public function setAssignsMembershipName($AssignsMembershipName): self
    {
        $this->container['AssignsMembershipName'] = $AssignsMembershipName;

        return $this;
    }

    /**
     * Gets SoldOnline
     *
     * @return bool
     */
    public function getSoldOnline()
    {
        return $this->container['SoldOnline'];
    }

    /**
     * Sets SoldOnline
     *
     * @param bool $SoldOnline When `true`, indicates that this membership is intended to be shown to clients in client experiences.<br />  When `false`, this contract should only be shown to staff members.
     *
     * @return $this
     */
    public function setSoldOnline($SoldOnline): self
    {
        $this->container['SoldOnline'] = $SoldOnline;

        return $this;
    }

    /**
     * Gets ContractItems
     *
     * @return \Nlocascio\Mindbody\Model\ContractItem[]
     */
    public function getContractItems()
    {
        return $this->container['ContractItems'];
    }

    /**
     * Sets ContractItems
     *
     * @param \Nlocascio\Mindbody\Model\ContractItem[] $ContractItems Contains information about the items in the contract.
     *
     * @return $this
     */
    public function setContractItems($ContractItems): self
    {
        $this->container['ContractItems'] = $ContractItems;

        return $this;
    }

    /**
     * Gets IntroOffer
     *
     * @return string
     */
    public function getIntroOffer()
    {
        return $this->container['IntroOffer'];
    }

    /**
     * Sets IntroOffer
     *
     * @param string $IntroOffer Defines whether this contract is treated as an introductory offer. If this is an introductory offer, then clients are always charged a set number of times rather than month to month, using their AutoPays. Possible values are:  * None  * NewConsumer  * NewAndReturningConsumer
     *
     * @return $this
     */
    public function setIntroOffer($IntroOffer): self
    {
        $this->container['IntroOffer'] = $IntroOffer;

        return $this;
    }

    /**
     * Gets AutopaySchedule
     *
     * @return \Nlocascio\Mindbody\Model\AutopaySchedule
     */
    public function getAutopaySchedule()
    {
        return $this->container['AutopaySchedule'];
    }

    /**
     * Sets AutopaySchedule
     *
     * @param \Nlocascio\Mindbody\Model\AutopaySchedule $AutopaySchedule Contains information about the AutoPay schedule. This parameter is null if `AutopayTriggerType` has a value of `PricingOptionRunsOutOrExpires`.
     *
     * @return $this
     */
    public function setAutopaySchedule($AutopaySchedule): self
    {
        $this->container['AutopaySchedule'] = $AutopaySchedule;

        return $this;
    }

    /**
     * Gets NumberOfAutopays
     *
     * @return int
     */
    public function getNumberOfAutopays()
    {
        return $this->container['NumberOfAutopays'];
    }

    /**
     * Sets NumberOfAutopays
     *
     * @param int $NumberOfAutopays The number of times that the AutoPay is to be run. This value is null if `FrequencyType` is `MonthToMonth`.
     *
     * @return $this
     */
    public function setNumberOfAutopays($NumberOfAutopays): self
    {
        $this->container['NumberOfAutopays'] = $NumberOfAutopays;

        return $this;
    }

    /**
     * Gets AutopayTriggerType
     *
     * @return string
     */
    public function getAutopayTriggerType()
    {
        return $this->container['AutopayTriggerType'];
    }

    /**
     * Sets AutopayTriggerType
     *
     * @param string $AutopayTriggerType Defines whether the AutoPay, if applicable to this contract, runs on a set schedule or when the pricing option runs out or expires. Possible values are:  * OnSetSchedule  * PricingOptionRunsOutOrExpires
     *
     * @return $this
     */
    public function setAutopayTriggerType($AutopayTriggerType): self
    {
        $this->container['AutopayTriggerType'] = $AutopayTriggerType;

        return $this;
    }

    /**
     * Gets ActionUponCompletionOfAutopays
     *
     * @return string
     */
    public function getActionUponCompletionOfAutopays()
    {
        return $this->container['ActionUponCompletionOfAutopays'];
    }

    /**
     * Sets ActionUponCompletionOfAutopays
     *
     * @param string $ActionUponCompletionOfAutopays The renewal action to be taken when this AutoPay is completed. Possible values are:  * ContractExpires  * ContractAutomaticallyRenews
     *
     * @return $this
     */
    public function setActionUponCompletionOfAutopays($ActionUponCompletionOfAutopays): self
    {
        $this->container['ActionUponCompletionOfAutopays'] = $ActionUponCompletionOfAutopays;

        return $this;
    }

    /**
     * Gets ClientsChargedOn
     *
     * @return string
     */
    public function getClientsChargedOn()
    {
        return $this->container['ClientsChargedOn'];
    }

    /**
     * Sets ClientsChargedOn
     *
     * @param string $ClientsChargedOn The value that indicates when clients are charged. Possible values are:  * OnSaleDate  * FirstOfTheMonth  * FifteenthOfTheMonth  * LastDayOfTheMonth  * FirstOrFifteenthOfTheMonth  * FirstOrSixteenthOfTheMonth  * FifteenthOrEndOfTheMonth  * SpecificDate
     *
     * @return $this
     */
    public function setClientsChargedOn($ClientsChargedOn): self
    {
        $this->container['ClientsChargedOn'] = $ClientsChargedOn;

        return $this;
    }

    /**
     * Gets ClientsChargedOnSpecificDate
     *
     * @return \DateTime
     */
    public function getClientsChargedOnSpecificDate()
    {
        return $this->container['ClientsChargedOnSpecificDate'];
    }

    /**
     * Sets ClientsChargedOnSpecificDate
     *
     * @param \DateTime $ClientsChargedOnSpecificDate If `ClientsChargedOn` is defined as a specific date, this property holds the value of that date. Otherwise, this property is null.
     *
     * @return $this
     */
    public function setClientsChargedOnSpecificDate($ClientsChargedOnSpecificDate): self
    {
        $this->container['ClientsChargedOnSpecificDate'] = $ClientsChargedOnSpecificDate;

        return $this;
    }

    /**
     * Gets DiscountAmount
     *
     * @return double
     */
    public function getDiscountAmount()
    {
        return $this->container['DiscountAmount'];
    }

    /**
     * Sets DiscountAmount
     *
     * @param double $DiscountAmount The calculated discount applied to the items in this contract.
     *
     * @return $this
     */
    public function setDiscountAmount($DiscountAmount): self
    {
        $this->container['DiscountAmount'] = $DiscountAmount;

        return $this;
    }

    /**
     * Gets DepositAmount
     *
     * @return double
     */
    public function getDepositAmount()
    {
        return $this->container['DepositAmount'];
    }

    /**
     * Sets DepositAmount
     *
     * @param double $DepositAmount The amount of the deposit required for this contract.
     *
     * @return $this
     */
    public function setDepositAmount($DepositAmount): self
    {
        $this->container['DepositAmount'] = $DepositAmount;

        return $this;
    }

    /**
     * Gets FirstAutopayFree
     *
     * @return bool
     */
    public function getFirstAutopayFree()
    {
        return $this->container['FirstAutopayFree'];
    }

    /**
     * Sets FirstAutopayFree
     *
     * @param bool $FirstAutopayFree When `true`, indicates that the first payment for the AutoPay is free.
     *
     * @return $this
     */
    public function setFirstAutopayFree($FirstAutopayFree): self
    {
        $this->container['FirstAutopayFree'] = $FirstAutopayFree;

        return $this;
    }

    /**
     * Gets LastAutopayFree
     *
     * @return bool
     */
    public function getLastAutopayFree()
    {
        return $this->container['LastAutopayFree'];
    }

    /**
     * Sets LastAutopayFree
     *
     * @param bool $LastAutopayFree When `true`, indicates that the last payment for the AutoPay is free.
     *
     * @return $this
     */
    public function setLastAutopayFree($LastAutopayFree): self
    {
        $this->container['LastAutopayFree'] = $LastAutopayFree;

        return $this;
    }

    /**
     * Gets ClientTerminateOnline
     *
     * @return bool
     */
    public function getClientTerminateOnline()
    {
        return $this->container['ClientTerminateOnline'];
    }

    /**
     * Sets ClientTerminateOnline
     *
     * @param bool $ClientTerminateOnline When `true`, indicates that the client can terminate this contract on the Internet.
     *
     * @return $this
     */
    public function setClientTerminateOnline($ClientTerminateOnline): self
    {
        $this->container['ClientTerminateOnline'] = $ClientTerminateOnline;

        return $this;
    }

    /**
     * Gets MembershipTypeRestrictions
     *
     * @return \Nlocascio\Mindbody\Model\MembershipTypeRestriction[]
     */
    public function getMembershipTypeRestrictions()
    {
        return $this->container['MembershipTypeRestrictions'];
    }

    /**
     * Sets MembershipTypeRestrictions
     *
     * @param \Nlocascio\Mindbody\Model\MembershipTypeRestriction[] $MembershipTypeRestrictions Contains information about the memberships that can purchase this contract. If null, then no membership restrictions exist, and anyone can purchase the contract.
     *
     * @return $this
     */
    public function setMembershipTypeRestrictions($MembershipTypeRestrictions): self
    {
        $this->container['MembershipTypeRestrictions'] = $MembershipTypeRestrictions;

        return $this;
    }

    /**
     * Gets LocationPurchaseRestrictionIds
     *
     * @return int[]
     */
    public function getLocationPurchaseRestrictionIds()
    {
        return $this->container['LocationPurchaseRestrictionIds'];
    }

    /**
     * Sets LocationPurchaseRestrictionIds
     *
     * @param int[] $LocationPurchaseRestrictionIds The IDs of the locations where this contract may be sold. If there are no restrictions, this value is null.
     *
     * @return $this
     */
    public function setLocationPurchaseRestrictionIds($LocationPurchaseRestrictionIds): self
    {
        $this->container['LocationPurchaseRestrictionIds'] = $LocationPurchaseRestrictionIds;

        return $this;
    }

    /**
     * Gets LocationPurchaseRestrictionNames
     *
     * @return string[]
     */
    public function getLocationPurchaseRestrictionNames()
    {
        return $this->container['LocationPurchaseRestrictionNames'];
    }

    /**
     * Sets LocationPurchaseRestrictionNames
     *
     * @param string[] $LocationPurchaseRestrictionNames Location names where the contract may be purchased. If this value is null, there are no restrictions.
     *
     * @return $this
     */
    public function setLocationPurchaseRestrictionNames($LocationPurchaseRestrictionNames): self
    {
        $this->container['LocationPurchaseRestrictionNames'] = $LocationPurchaseRestrictionNames;

        return $this;
    }

    /**
     * Gets AgreementTerms
     *
     * @return string
     */
    public function getAgreementTerms()
    {
        return $this->container['AgreementTerms'];
    }

    /**
     * Sets AgreementTerms
     *
     * @param string $AgreementTerms Business-defined terms and conditions for the contract.
     *
     * @return $this
     */
    public function setAgreementTerms($AgreementTerms): self
    {
        $this->container['AgreementTerms'] = $AgreementTerms;

        return $this;
    }

    /**
     * Gets RequiresElectronicConfirmation
     *
     * @return bool
     */
    public function getRequiresElectronicConfirmation()
    {
        return $this->container['RequiresElectronicConfirmation'];
    }

    /**
     * Sets RequiresElectronicConfirmation
     *
     * @param bool $RequiresElectronicConfirmation When `true`, clients who purchase the contract are prompted to agree to the terms of the contract the next time that they log in.
     *
     * @return $this
     */
    public function setRequiresElectronicConfirmation($RequiresElectronicConfirmation): self
    {
        $this->container['RequiresElectronicConfirmation'] = $RequiresElectronicConfirmation;

        return $this;
    }

    /**
     * Gets AutopayEnabled
     *
     * @return bool
     */
    public function getAutopayEnabled()
    {
        return $this->container['AutopayEnabled'];
    }

    /**
     * Sets AutopayEnabled
     *
     * @param bool $AutopayEnabled When `true`, this contract establishes an AutoPay on the client’s account.
     *
     * @return $this
     */
    public function setAutopayEnabled($AutopayEnabled): self
    {
        $this->container['AutopayEnabled'] = $AutopayEnabled;

        return $this;
    }

    /**
     * Gets FirstPaymentAmountSubtotal
     *
     * @return double
     */
    public function getFirstPaymentAmountSubtotal()
    {
        return $this->container['FirstPaymentAmountSubtotal'];
    }

    /**
     * Sets FirstPaymentAmountSubtotal
     *
     * @param double $FirstPaymentAmountSubtotal The subtotal of the amount that the client is to be charged when signing up for the contract.
     *
     * @return $this
     */
    public function setFirstPaymentAmountSubtotal($FirstPaymentAmountSubtotal): self
    {
        $this->container['FirstPaymentAmountSubtotal'] = $FirstPaymentAmountSubtotal;

        return $this;
    }

    /**
     * Gets FirstPaymentAmountTax
     *
     * @return double
     */
    public function getFirstPaymentAmountTax()
    {
        return $this->container['FirstPaymentAmountTax'];
    }

    /**
     * Sets FirstPaymentAmountTax
     *
     * @param double $FirstPaymentAmountTax The amount of tax that the client is to be charged when signing up for the contract.
     *
     * @return $this
     */
    public function setFirstPaymentAmountTax($FirstPaymentAmountTax): self
    {
        $this->container['FirstPaymentAmountTax'] = $FirstPaymentAmountTax;

        return $this;
    }

    /**
     * Gets FirstPaymentAmountTotal
     *
     * @return double
     */
    public function getFirstPaymentAmountTotal()
    {
        return $this->container['FirstPaymentAmountTotal'];
    }

    /**
     * Sets FirstPaymentAmountTotal
     *
     * @param double $FirstPaymentAmountTotal The total amount that the client is to be charged when signing up for the contract.
     *
     * @return $this
     */
    public function setFirstPaymentAmountTotal($FirstPaymentAmountTotal): self
    {
        $this->container['FirstPaymentAmountTotal'] = $FirstPaymentAmountTotal;

        return $this;
    }

    /**
     * Gets RecurringPaymentAmountSubtotal
     *
     * @return double
     */
    public function getRecurringPaymentAmountSubtotal()
    {
        return $this->container['RecurringPaymentAmountSubtotal'];
    }

    /**
     * Sets RecurringPaymentAmountSubtotal
     *
     * @param double $RecurringPaymentAmountSubtotal The subtotal amount that the client is to be charged on an ongoing basis.
     *
     * @return $this
     */
    public function setRecurringPaymentAmountSubtotal($RecurringPaymentAmountSubtotal): self
    {
        $this->container['RecurringPaymentAmountSubtotal'] = $RecurringPaymentAmountSubtotal;

        return $this;
    }

    /**
     * Gets RecurringPaymentAmountTax
     *
     * @return double
     */
    public function getRecurringPaymentAmountTax()
    {
        return $this->container['RecurringPaymentAmountTax'];
    }

    /**
     * Sets RecurringPaymentAmountTax
     *
     * @param double $RecurringPaymentAmountTax The amount of tax the client is to be charged on an ongoing basis.
     *
     * @return $this
     */
    public function setRecurringPaymentAmountTax($RecurringPaymentAmountTax): self
    {
        $this->container['RecurringPaymentAmountTax'] = $RecurringPaymentAmountTax;

        return $this;
    }

    /**
     * Gets RecurringPaymentAmountTotal
     *
     * @return double
     */
    public function getRecurringPaymentAmountTotal()
    {
        return $this->container['RecurringPaymentAmountTotal'];
    }

    /**
     * Sets RecurringPaymentAmountTotal
     *
     * @param double $RecurringPaymentAmountTotal The total amount that the client is to be charged on an ongoing basis.
     *
     * @return $this
     */
    public function setRecurringPaymentAmountTotal($RecurringPaymentAmountTotal): self
    {
        $this->container['RecurringPaymentAmountTotal'] = $RecurringPaymentAmountTotal;

        return $this;
    }

    /**
     * Gets TotalContractAmountSubtotal
     *
     * @return double
     */
    public function getTotalContractAmountSubtotal()
    {
        return $this->container['TotalContractAmountSubtotal'];
    }

    /**
     * Sets TotalContractAmountSubtotal
     *
     * @param double $TotalContractAmountSubtotal The subtotal amount that the client is to be charged over the lifespan of the contract.
     *
     * @return $this
     */
    public function setTotalContractAmountSubtotal($TotalContractAmountSubtotal): self
    {
        $this->container['TotalContractAmountSubtotal'] = $TotalContractAmountSubtotal;

        return $this;
    }

    /**
     * Gets TotalContractAmountTax
     *
     * @return double
     */
    public function getTotalContractAmountTax()
    {
        return $this->container['TotalContractAmountTax'];
    }

    /**
     * Sets TotalContractAmountTax
     *
     * @param double $TotalContractAmountTax The total amount of tax the client is to be charged over the lifespan of the contract.
     *
     * @return $this
     */
    public function setTotalContractAmountTax($TotalContractAmountTax): self
    {
        $this->container['TotalContractAmountTax'] = $TotalContractAmountTax;

        return $this;
    }

    /**
     * Gets TotalContractAmountTotal
     *
     * @return double
     */
    public function getTotalContractAmountTotal()
    {
        return $this->container['TotalContractAmountTotal'];
    }

    /**
     * Sets TotalContractAmountTotal
     *
     * @param double $TotalContractAmountTotal The total amount the client is to be charged over the lifespan of the contract.
     *
     * @return $this
     */
    public function setTotalContractAmountTotal($TotalContractAmountTotal): self
    {
        $this->container['TotalContractAmountTotal'] = $TotalContractAmountTotal;

        return $this;
    }
    
}


