<?php
/**
 * ContactLogComment
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.23
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Nlocascio\Mindbody\Model;

/**
 * ContactLogComment Class Doc Comment
 *
 * @category Class
 * @description A contact log comment.
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ContactLogComment extends BaseModel implements ModelWithId
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ContactLogComment';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'Id' => 'int',
        'Text' => 'string',
        'CreatedDateTime' => '\DateTime',
        'CreatedBy' => '\Nlocascio\Mindbody\Model\Staff'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<int, string|null>
      */
    protected static $swaggerFormats = [
        'Id' => 'int32',
        'Text' => null,
        'CreatedDateTime' => 'date-time',
        'CreatedBy' => null
    ];


    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'Id' => 'Id',
        'Text' => 'Text',
        'CreatedDateTime' => 'CreatedDateTime',
        'CreatedBy' => 'CreatedBy'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'Id' => 'setId',
        'Text' => 'setText',
        'CreatedDateTime' => 'setCreatedDateTime',
        'CreatedBy' => 'setCreatedBy'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'Id' => 'getId',
        'Text' => 'getText',
        'CreatedDateTime' => 'getCreatedDateTime',
        'CreatedBy' => 'getCreatedBy'
    ];


    

    

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['Id'] = isset($data['Id']) ? $data['Id'] : null;
        $this->container['Text'] = isset($data['Text']) ? $data['Text'] : null;
        $this->container['CreatedDateTime'] = isset($data['CreatedDateTime']) ? $data['CreatedDateTime'] : null;
        $this->container['CreatedBy'] = isset($data['CreatedBy']) ? $data['CreatedBy'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = parent::listInvalidProperties();

        return $invalidProperties;
    }


    /**
     * Gets Id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['Id'];
    }

    /**
     * Sets Id
     *
     * @param int $Id The comment’s ID.
     *
     * @return $this
     */
    public function setId($Id): self
    {
        $this->container['Id'] = $Id;

        return $this;
    }

    /**
     * Gets Text
     *
     * @return string
     */
    public function getText()
    {
        return $this->container['Text'];
    }

    /**
     * Sets Text
     *
     * @param string $Text The comment’s body text.
     *
     * @return $this
     */
    public function setText($Text): self
    {
        $this->container['Text'] = $Text;

        return $this;
    }

    /**
     * Gets CreatedDateTime
     *
     * @return \DateTime
     */
    public function getCreatedDateTime()
    {
        return $this->container['CreatedDateTime'];
    }

    /**
     * Sets CreatedDateTime
     *
     * @param \DateTime $CreatedDateTime The local time when the comment was created.
     *
     * @return $this
     */
    public function setCreatedDateTime($CreatedDateTime): self
    {
        $this->container['CreatedDateTime'] = $CreatedDateTime;

        return $this;
    }

    /**
     * Gets CreatedBy
     *
     * @return \Nlocascio\Mindbody\Model\Staff
     */
    public function getCreatedBy()
    {
        return $this->container['CreatedBy'];
    }

    /**
     * Sets CreatedBy
     *
     * @param \Nlocascio\Mindbody\Model\Staff $CreatedBy Information about the staff member who created the comment.
     *
     * @return $this
     */
    public function setCreatedBy($CreatedBy): self
    {
        $this->container['CreatedBy'] = $CreatedBy;

        return $this;
    }
    
}


