<?php
/**
 * ContractItem
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.40-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Nlocascio\Mindbody\Model;

/**
 * ContractItem Class Doc Comment
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 * @property string $Id The ID of the item.
 * @property string $Name The name of the item.
 * @property string $Description A description of the item.
 * @property string $Type The type of the item.
 * @property double $Price The price of the item.
 * @property int $Quantity The quantity of the item.
 * @property bool $OneTimeItem When `true`, indicates that the item is charged only once.<br />  When `false`, indicates that the item is charged multiple times.
 *
 */
class ContractItem extends BaseModel implements ModelWithId
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ContractItem';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'Id' => 'string',
        'Name' => 'string',
        'Description' => 'string',
        'Type' => 'string',
        'Price' => 'double',
        'Quantity' => 'int',
        'OneTimeItem' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static $swaggerFormats = [
        'Id' => null,
        'Name' => null,
        'Description' => null,
        'Type' => null,
        'Price' => 'double',
        'Quantity' => 'int32',
        'OneTimeItem' => null
    ];


    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'Id' => 'Id',
        'Name' => 'Name',
        'Description' => 'Description',
        'Type' => 'Type',
        'Price' => 'Price',
        'Quantity' => 'Quantity',
        'OneTimeItem' => 'OneTimeItem'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'Id' => 'setId',
        'Name' => 'setName',
        'Description' => 'setDescription',
        'Type' => 'setType',
        'Price' => 'setPrice',
        'Quantity' => 'setQuantity',
        'OneTimeItem' => 'setOneTimeItem'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'Id' => 'getId',
        'Name' => 'getName',
        'Description' => 'getDescription',
        'Type' => 'getType',
        'Price' => 'getPrice',
        'Quantity' => 'getQuantity',
        'OneTimeItem' => 'getOneTimeItem'
    ];


    

    

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['Id'] = isset($data['Id']) ? $data['Id'] : null;
        $this->container['Name'] = isset($data['Name']) ? $data['Name'] : null;
        $this->container['Description'] = isset($data['Description']) ? $data['Description'] : null;
        $this->container['Type'] = isset($data['Type']) ? $data['Type'] : null;
        $this->container['Price'] = isset($data['Price']) ? $data['Price'] : null;
        $this->container['Quantity'] = isset($data['Quantity']) ? $data['Quantity'] : null;
        $this->container['OneTimeItem'] = isset($data['OneTimeItem']) ? $data['OneTimeItem'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = parent::listInvalidProperties();

        return $invalidProperties;
    }


    /**
     * Gets Id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['Id'];
    }

    /**
     * Sets Id
     *
     * @param string $Id The ID of the item.
     *
     * @return $this
     */
    public function setId($Id): self
    {
        $this->container['Id'] = $Id;

        return $this;
    }

    /**
     * Gets Name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['Name'];
    }

    /**
     * Sets Name
     *
     * @param string $Name The name of the item.
     *
     * @return $this
     */
    public function setName($Name): self
    {
        $this->container['Name'] = $Name;

        return $this;
    }

    /**
     * Gets Description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->container['Description'];
    }

    /**
     * Sets Description
     *
     * @param string $Description A description of the item.
     *
     * @return $this
     */
    public function setDescription($Description): self
    {
        $this->container['Description'] = $Description;

        return $this;
    }

    /**
     * Gets Type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['Type'];
    }

    /**
     * Sets Type
     *
     * @param string $Type The type of the item.
     *
     * @return $this
     */
    public function setType($Type): self
    {
        $this->container['Type'] = $Type;

        return $this;
    }

    /**
     * Gets Price
     *
     * @return double
     */
    public function getPrice()
    {
        return $this->container['Price'];
    }

    /**
     * Sets Price
     *
     * @param double $Price The price of the item.
     *
     * @return $this
     */
    public function setPrice($Price): self
    {
        $this->container['Price'] = $Price;

        return $this;
    }

    /**
     * Gets Quantity
     *
     * @return int
     */
    public function getQuantity()
    {
        return $this->container['Quantity'];
    }

    /**
     * Sets Quantity
     *
     * @param int $Quantity The quantity of the item.
     *
     * @return $this
     */
    public function setQuantity($Quantity): self
    {
        $this->container['Quantity'] = $Quantity;

        return $this;
    }

    /**
     * Gets OneTimeItem
     *
     * @return bool
     */
    public function getOneTimeItem()
    {
        return $this->container['OneTimeItem'];
    }

    /**
     * Sets OneTimeItem
     *
     * @param bool $OneTimeItem When `true`, indicates that the item is charged only once.<br />  When `false`, indicates that the item is charged multiple times.
     *
     * @return $this
     */
    public function setOneTimeItem($OneTimeItem): self
    {
        $this->container['OneTimeItem'] = $OneTimeItem;

        return $this;
    }
    
}


