<?php
/**
 * CustomClientField
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.23
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Nlocascio\Mindbody\Model;

/**
 * CustomClientField Class Doc Comment
 *
 * @category Class
 * @description A custom client field
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CustomClientField extends BaseModel
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'CustomClientField';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'Id' => 'int',
        'DataType' => 'string',
        'Name' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'Id' => 'int32',
        'DataType' => null,
        'Name' => null
    ];


    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'Id' => 'Id',
        'DataType' => 'DataType',
        'Name' => 'Name'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'Id' => 'setId',
        'DataType' => 'setDataType',
        'Name' => 'setName'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'Id' => 'getId',
        'DataType' => 'getDataType',
        'Name' => 'getName'
    ];


    

    

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['Id'] = isset($data['Id']) ? $data['Id'] : null;
        $this->container['DataType'] = isset($data['DataType']) ? $data['DataType'] : null;
        $this->container['Name'] = isset($data['Name']) ? $data['Name'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = parent::listInvalidProperties();

        return $invalidProperties;
    }


    /**
     * Gets Id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['Id'];
    }

    /**
     * Sets Id
     *
     * @param int $Id The ID of the custom client field.
     *
     * @return $this
     */
    public function setId($Id): self
    {
        $this->container['Id'] = $Id;

        return $this;
    }

    /**
     * Gets DataType
     *
     * @return string
     */
    public function getDataType()
    {
        return $this->container['DataType'];
    }

    /**
     * Sets DataType
     *
     * @param string $DataType The data type of the field.
     *
     * @return $this
     */
    public function setDataType($DataType): self
    {
        $this->container['DataType'] = $DataType;

        return $this;
    }

    /**
     * Gets Name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['Name'];
    }

    /**
     * Sets Name
     *
     * @param string $Name The name of the field.
     *
     * @return $this
     */
    public function setName($Name): self
    {
        $this->container['Name'] = $Name;

        return $this;
    }
    
}


