<?php
/**
 * GetAlternativePaymentMethodsRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Nlocascio\Mindbody\Model;

/**
 * GetAlternativePaymentMethodsRequest Class Doc Comment
 *
 * @category Class
 * @description request object for the GetAlternativePaymentMethods method.
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 * @property int $LocationId The location ID  Default: **null** (Online store location)
 * @property string $ClientId The client ID
 *
 */
class GetAlternativePaymentMethodsRequest extends BaseModel
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $swaggerModelName = 'GetAlternativePaymentMethodsRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static array $swaggerTypes = [
        'LocationId' => 'int',
        'ClientId' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $swaggerFormats = [
        'LocationId' => 'int32',
        'ClientId' => null
    ];


    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static array $attributeMap = [
        'LocationId' => 'LocationId',
        'ClientId' => 'ClientId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static array $setters = [
        'LocationId' => 'setLocationId',
        'ClientId' => 'setClientId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static array $getters = [
        'LocationId' => 'getLocationId',
        'ClientId' => 'getClientId'
    ];


    

    

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->container['LocationId'] = isset($data['LocationId']) ? $data['LocationId'] : null;
        $this->container['ClientId'] = isset($data['ClientId']) ? $data['ClientId'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = parent::listInvalidProperties();

        return $invalidProperties;
    }


    /**
     * Gets LocationId
     *
     * @return int
     */
    public function getLocationId(): int|null
    {
        return $this->container['LocationId'];
    }

    /**
     * Sets LocationId
     *
     * @param int $LocationId The location ID  Default: **null** (Online store location)
     *
     * @return $this
     */


    public function setLocationId(int $LocationId): static
    {
        $this->container['LocationId'] = $LocationId;

        return $this;
    }

    /**
     * Gets ClientId
     *
     * @return string
     */
    public function getClientId(): string|null
    {
        return $this->container['ClientId'];
    }

    /**
     * Sets ClientId
     *
     * @param string $ClientId The client ID
     *
     * @return $this
     */


    public function setClientId(string $ClientId): static
    {
        $this->container['ClientId'] = $ClientId;

        return $this;
    }
    
}


