<?php
/**
 * GetCommissionsResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.23
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Nlocascio\Mindbody\Model;

/**
 * GetCommissionsResponse Class Doc Comment
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class GetCommissionsResponse extends BaseModel
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'GetCommissionsResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'PaginationResponse' => '\Nlocascio\Mindbody\Model\PaginationResponse',
        'Commissions' => '\Nlocascio\Mindbody\Model\CommissionPayrollPurchaseEvent[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'PaginationResponse' => null,
        'Commissions' => null
    ];


    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'PaginationResponse' => 'PaginationResponse',
        'Commissions' => 'Commissions'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'PaginationResponse' => 'setPaginationResponse',
        'Commissions' => 'setCommissions'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'PaginationResponse' => 'getPaginationResponse',
        'Commissions' => 'getCommissions'
    ];


    

    

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['PaginationResponse'] = isset($data['PaginationResponse']) ? $data['PaginationResponse'] : null;
        $this->container['Commissions'] = isset($data['Commissions']) ? $data['Commissions'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = parent::listInvalidProperties();

        return $invalidProperties;
    }


    /**
     * Gets PaginationResponse
     *
     * @return \Nlocascio\Mindbody\Model\PaginationResponse
     */
    public function getPaginationResponse()
    {
        return $this->container['PaginationResponse'];
    }

    /**
     * Sets PaginationResponse
     *
     * @param \Nlocascio\Mindbody\Model\PaginationResponse $PaginationResponse Contains information about the pagination used.
     *
     * @return $this
     */
    public function setPaginationResponse($PaginationResponse): self
    {
        $this->container['PaginationResponse'] = $PaginationResponse;

        return $this;
    }

    /**
     * Gets Commissions
     *
     * @return \Nlocascio\Mindbody\Model\CommissionPayrollPurchaseEvent[]
     */
    public function getCommissions()
    {
        return $this->container['Commissions'];
    }

    /**
     * Sets Commissions
     *
     * @param \Nlocascio\Mindbody\Model\CommissionPayrollPurchaseEvent[] $Commissions Contains information about commissions earned by staff for sales within the given date range. Results are ordered by `SaleId`, then by `StaffId`.
     *
     * @return $this
     */
    public function setCommissions($Commissions): self
    {
        $this->container['Commissions'] = $Commissions;

        return $this;
    }
    
}


