<?php
/**
 * GetContractsResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.23
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Nlocascio\Mindbody\Model;

/**
 * GetContractsResponse Class Doc Comment
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class GetContractsResponse extends BaseModel
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'GetContractsResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'PaginationResponse' => '\Nlocascio\Mindbody\Model\PaginationResponse',
        'Contracts' => '\Nlocascio\Mindbody\Model\Contract[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<int, string|null>
      */
    protected static $swaggerFormats = [
        'PaginationResponse' => null,
        'Contracts' => null
    ];


    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'PaginationResponse' => 'PaginationResponse',
        'Contracts' => 'Contracts'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'PaginationResponse' => 'setPaginationResponse',
        'Contracts' => 'setContracts'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'PaginationResponse' => 'getPaginationResponse',
        'Contracts' => 'getContracts'
    ];


    

    

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['PaginationResponse'] = isset($data['PaginationResponse']) ? $data['PaginationResponse'] : null;
        $this->container['Contracts'] = isset($data['Contracts']) ? $data['Contracts'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = parent::listInvalidProperties();

        return $invalidProperties;
    }


    /**
     * Gets PaginationResponse
     *
     * @return \Nlocascio\Mindbody\Model\PaginationResponse
     */
    public function getPaginationResponse()
    {
        return $this->container['PaginationResponse'];
    }

    /**
     * Sets PaginationResponse
     *
     * @param \Nlocascio\Mindbody\Model\PaginationResponse $PaginationResponse Contains information about the pagination used.
     *
     * @return $this
     */
    public function setPaginationResponse($PaginationResponse): self
    {
        $this->container['PaginationResponse'] = $PaginationResponse;

        return $this;
    }

    /**
     * Gets Contracts
     *
     * @return \Nlocascio\Mindbody\Model\Contract[]
     */
    public function getContracts()
    {
        return $this->container['Contracts'];
    }

    /**
     * Sets Contracts
     *
     * @param \Nlocascio\Mindbody\Model\Contract[] $Contracts Contains information about each contract.
     *
     * @return $this
     */
    public function setContracts($Contracts): self
    {
        $this->container['Contracts'] = $Contracts;

        return $this;
    }
    
}


