<?php
/**
 * GetClientVisitsRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Nlocascio\Mindbody\Model;

/**
 * GetClientVisitsRequest Class Doc Comment
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 * @property string $ClientId The ID of the requested client.
 * @property int $UniqueClientId The unique ID of the requested client.  Note: you need to provide the 'UniqueClientId' OR the 'ClientId'. If both are provided, the 'UniqueClientId' takes precedence.
 * @property int $ClientAssociatedSitesOffset The number of sites to skip when returning the site associated with a client.
 * @property bool $CrossRegionalLookup When `true`, indicates that past and scheduled client visits across all sites in the region are returned.<br />  When `false`, indicates that only visits at the current site are returned.
 * @property \DateTime $EndDate The date past which class visits are not returned.  Default: **today's date**
 * @property \DateTime $StartDate The date before which class visits are not returned.  Default: **the end date**
 * @property bool $UnpaidsOnly When `true`, indicates that only visits that have not been paid for are returned.<br />  When `false`, indicates that all visits are returned, regardless of whether they have been paid for.<br />  Default: **false**
 * @property string $Order The sort order for the results.<br />  When `desc`, results are returned in descending order (newest first).<br />  When `asc`, results are returned in ascending order (oldest first).
 * @property int $Limit Number of results to include, defaults to 100
 * @property int $Offset Page offset, defaults to 0.
 *
 */
class GetClientVisitsRequest extends BaseModel
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $swaggerModelName = 'GetClientVisitsRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static array $swaggerTypes = [
        'ClientId' => 'string',
        'UniqueClientId' => 'int',
        'ClientAssociatedSitesOffset' => 'int',
        'CrossRegionalLookup' => 'bool',
        'EndDate' => '\DateTime',
        'StartDate' => '\DateTime',
        'UnpaidsOnly' => 'bool',
        'Order' => 'string',
        'Limit' => 'int',
        'Offset' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $swaggerFormats = [
        'ClientId' => null,
        'UniqueClientId' => 'int64',
        'ClientAssociatedSitesOffset' => 'int32',
        'CrossRegionalLookup' => null,
        'EndDate' => 'date-time',
        'StartDate' => 'date-time',
        'UnpaidsOnly' => null,
        'Order' => null,
        'Limit' => 'int32',
        'Offset' => 'int32'
    ];


    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static array $attributeMap = [
        'ClientId' => 'ClientId',
        'UniqueClientId' => 'UniqueClientId',
        'ClientAssociatedSitesOffset' => 'ClientAssociatedSitesOffset',
        'CrossRegionalLookup' => 'CrossRegionalLookup',
        'EndDate' => 'EndDate',
        'StartDate' => 'StartDate',
        'UnpaidsOnly' => 'UnpaidsOnly',
        'Order' => 'Order',
        'Limit' => 'Limit',
        'Offset' => 'Offset'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static array $setters = [
        'ClientId' => 'setClientId',
        'UniqueClientId' => 'setUniqueClientId',
        'ClientAssociatedSitesOffset' => 'setClientAssociatedSitesOffset',
        'CrossRegionalLookup' => 'setCrossRegionalLookup',
        'EndDate' => 'setEndDate',
        'StartDate' => 'setStartDate',
        'UnpaidsOnly' => 'setUnpaidsOnly',
        'Order' => 'setOrder',
        'Limit' => 'setLimit',
        'Offset' => 'setOffset'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static array $getters = [
        'ClientId' => 'getClientId',
        'UniqueClientId' => 'getUniqueClientId',
        'ClientAssociatedSitesOffset' => 'getClientAssociatedSitesOffset',
        'CrossRegionalLookup' => 'getCrossRegionalLookup',
        'EndDate' => 'getEndDate',
        'StartDate' => 'getStartDate',
        'UnpaidsOnly' => 'getUnpaidsOnly',
        'Order' => 'getOrder',
        'Limit' => 'getLimit',
        'Offset' => 'getOffset'
    ];


    

    

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->container['ClientId'] = isset($data['ClientId']) ? $data['ClientId'] : null;
        $this->container['UniqueClientId'] = isset($data['UniqueClientId']) ? $data['UniqueClientId'] : null;
        $this->container['ClientAssociatedSitesOffset'] = isset($data['ClientAssociatedSitesOffset']) ? $data['ClientAssociatedSitesOffset'] : null;
        $this->container['CrossRegionalLookup'] = isset($data['CrossRegionalLookup']) ? $data['CrossRegionalLookup'] : null;
        $this->container['EndDate'] = isset($data['EndDate']) ? $data['EndDate'] : null;
        $this->container['StartDate'] = isset($data['StartDate']) ? $data['StartDate'] : null;
        $this->container['UnpaidsOnly'] = isset($data['UnpaidsOnly']) ? $data['UnpaidsOnly'] : null;
        $this->container['Order'] = isset($data['Order']) ? $data['Order'] : null;
        $this->container['Limit'] = isset($data['Limit']) ? $data['Limit'] : null;
        $this->container['Offset'] = isset($data['Offset']) ? $data['Offset'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = parent::listInvalidProperties();

        return $invalidProperties;
    }


    /**
     * Gets ClientId
     *
     * @return string
     */
    public function getClientId(): string|null
    {
        return $this->container['ClientId'];
    }

    /**
     * Sets ClientId
     *
     * @param string $ClientId The ID of the requested client.
     *
     * @return $this
     */


    public function setClientId(string $ClientId): static
    {
        $this->container['ClientId'] = $ClientId;

        return $this;
    }

    /**
     * Gets UniqueClientId
     *
     * @return int
     */
    public function getUniqueClientId(): int|null
    {
        return $this->container['UniqueClientId'];
    }

    /**
     * Sets UniqueClientId
     *
     * @param int $UniqueClientId The unique ID of the requested client.  Note: you need to provide the 'UniqueClientId' OR the 'ClientId'. If both are provided, the 'UniqueClientId' takes precedence.
     *
     * @return $this
     */


    public function setUniqueClientId(int $UniqueClientId): static
    {
        $this->container['UniqueClientId'] = $UniqueClientId;

        return $this;
    }

    /**
     * Gets ClientAssociatedSitesOffset
     *
     * @return int
     */
    public function getClientAssociatedSitesOffset(): int|null
    {
        return $this->container['ClientAssociatedSitesOffset'];
    }

    /**
     * Sets ClientAssociatedSitesOffset
     *
     * @param int $ClientAssociatedSitesOffset The number of sites to skip when returning the site associated with a client.
     *
     * @return $this
     */


    public function setClientAssociatedSitesOffset(int $ClientAssociatedSitesOffset): static
    {
        $this->container['ClientAssociatedSitesOffset'] = $ClientAssociatedSitesOffset;

        return $this;
    }

    /**
     * Gets CrossRegionalLookup
     *
     * @return bool
     */
    public function getCrossRegionalLookup(): bool|null
    {
        return $this->container['CrossRegionalLookup'];
    }

    /**
     * Sets CrossRegionalLookup
     *
     * @param bool $CrossRegionalLookup When `true`, indicates that past and scheduled client visits across all sites in the region are returned.<br />  When `false`, indicates that only visits at the current site are returned.
     *
     * @return $this
     */


    public function setCrossRegionalLookup(bool $CrossRegionalLookup): static
    {
        $this->container['CrossRegionalLookup'] = $CrossRegionalLookup;

        return $this;
    }

    /**
     * Gets EndDate
     *
     * @return \DateTime
     */
    public function getEndDate(): \DateTime|null
    {
        return $this->container['EndDate'];
    }

    /**
     * Sets EndDate
     *
     * @param \DateTime $EndDate The date past which class visits are not returned.  Default: **today's date**
     *
     * @return $this
     */


    public function setEndDate(\DateTime $EndDate): static
    {
        $this->container['EndDate'] = $EndDate;

        return $this;
    }

    /**
     * Gets StartDate
     *
     * @return \DateTime
     */
    public function getStartDate(): \DateTime|null
    {
        return $this->container['StartDate'];
    }

    /**
     * Sets StartDate
     *
     * @param \DateTime $StartDate The date before which class visits are not returned.  Default: **the end date**
     *
     * @return $this
     */


    public function setStartDate(\DateTime $StartDate): static
    {
        $this->container['StartDate'] = $StartDate;

        return $this;
    }

    /**
     * Gets UnpaidsOnly
     *
     * @return bool
     */
    public function getUnpaidsOnly(): bool|null
    {
        return $this->container['UnpaidsOnly'];
    }

    /**
     * Sets UnpaidsOnly
     *
     * @param bool $UnpaidsOnly When `true`, indicates that only visits that have not been paid for are returned.<br />  When `false`, indicates that all visits are returned, regardless of whether they have been paid for.<br />  Default: **false**
     *
     * @return $this
     */


    public function setUnpaidsOnly(bool $UnpaidsOnly): static
    {
        $this->container['UnpaidsOnly'] = $UnpaidsOnly;

        return $this;
    }

    /**
     * Gets Order
     *
     * @return string
     */
    public function getOrder(): string|null
    {
        return $this->container['Order'];
    }

    /**
     * Sets Order
     *
     * @param string $Order The sort order for the results.<br />  When `desc`, results are returned in descending order (newest first).<br />  When `asc`, results are returned in ascending order (oldest first).
     *
     * @return $this
     */


    public function setOrder(string $Order): static
    {
        $this->container['Order'] = $Order;

        return $this;
    }

    /**
     * Gets Limit
     *
     * @return int
     */
    public function getLimit(): int|null
    {
        return $this->container['Limit'];
    }

    /**
     * Sets Limit
     *
     * @param int $Limit Number of results to include, defaults to 100
     *
     * @return $this
     */


    public function setLimit(int $Limit): static
    {
        $this->container['Limit'] = $Limit;

        return $this;
    }

    /**
     * Gets Offset
     *
     * @return int
     */
    public function getOffset(): int|null
    {
        return $this->container['Offset'];
    }

    /**
     * Sets Offset
     *
     * @param int $Offset Page offset, defaults to 0.
     *
     * @return $this
     */


    public function setOffset(int $Offset): static
    {
        $this->container['Offset'] = $Offset;

        return $this;
    }
    
}


