<?php
/**
 * GetCustomPaymentMethodsRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.28
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Nlocascio\Mindbody\Model;

/**
 * GetCustomPaymentMethodsRequest Class Doc Comment
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 * @property int $Limit Number of results to include, defaults to 100
 * @property int $Offset Page offset, defaults to 0.
 *
 */
class GetCustomPaymentMethodsRequest extends BaseModel
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'GetCustomPaymentMethodsRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'Limit' => 'int',
        'Offset' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static $swaggerFormats = [
        'Limit' => 'int32',
        'Offset' => 'int32'
    ];


    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'Limit' => 'Limit',
        'Offset' => 'Offset'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'Limit' => 'setLimit',
        'Offset' => 'setOffset'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'Limit' => 'getLimit',
        'Offset' => 'getOffset'
    ];


    

    

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['Limit'] = isset($data['Limit']) ? $data['Limit'] : null;
        $this->container['Offset'] = isset($data['Offset']) ? $data['Offset'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = parent::listInvalidProperties();

        return $invalidProperties;
    }


    /**
     * Gets Limit
     *
     * @return int
     */
    public function getLimit()
    {
        return $this->container['Limit'];
    }

    /**
     * Sets Limit
     *
     * @param int $Limit Number of results to include, defaults to 100
     *
     * @return $this
     */
    public function setLimit($Limit): self
    {
        $this->container['Limit'] = $Limit;

        return $this;
    }

    /**
     * Gets Offset
     *
     * @return int
     */
    public function getOffset()
    {
        return $this->container['Offset'];
    }

    /**
     * Sets Offset
     *
     * @param int $Offset Page offset, defaults to 0.
     *
     * @return $this
     */
    public function setOffset($Offset): self
    {
        $this->container['Offset'] = $Offset;

        return $this;
    }
    
}


