<?php
/**
 * GetGendersResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.23
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Nlocascio\Mindbody\Model;

/**
 * GetGendersResponse Class Doc Comment
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class GetGendersResponse extends BaseModel
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'GetGendersResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'GenderOptions' => '\Nlocascio\Mindbody\Model\GenderOption[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<int, string|null>
      */
    protected static $swaggerFormats = [
        'GenderOptions' => null
    ];


    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'GenderOptions' => 'GenderOptions'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'GenderOptions' => 'setGenderOptions'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'GenderOptions' => 'getGenderOptions'
    ];


    

    

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['GenderOptions'] = isset($data['GenderOptions']) ? $data['GenderOptions'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = parent::listInvalidProperties();

        return $invalidProperties;
    }


    /**
     * Gets GenderOptions
     *
     * @return \Nlocascio\Mindbody\Model\GenderOption[]
     */
    public function getGenderOptions()
    {
        return $this->container['GenderOptions'];
    }

    /**
     * Sets GenderOptions
     *
     * @param \Nlocascio\Mindbody\Model\GenderOption[] $GenderOptions A list of the gender options and their properties at the site
     *
     * @return $this
     */
    public function setGenderOptions($GenderOptions): self
    {
        $this->container['GenderOptions'] = $GenderOptions;

        return $this;
    }
    
}


