<?php
/**
 * GetRelationshipsResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.40-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Nlocascio\Mindbody\Model;

/**
 * GetRelationshipsResponse Class Doc Comment
 *
 * @category Class
 * @description Get Relationships Response Model
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 * @property \Nlocascio\Mindbody\Model\PaginationResponse $PaginationResponse Contains information about the pagination used.
 * @property \Nlocascio\Mindbody\Model\Relationship[] $Relationships A list of relationships.
 *
 */
class GetRelationshipsResponse extends BaseModel
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'GetRelationshipsResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'PaginationResponse' => '\Nlocascio\Mindbody\Model\PaginationResponse',
        'Relationships' => '\Nlocascio\Mindbody\Model\Relationship[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static $swaggerFormats = [
        'PaginationResponse' => null,
        'Relationships' => null
    ];


    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'PaginationResponse' => 'PaginationResponse',
        'Relationships' => 'Relationships'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'PaginationResponse' => 'setPaginationResponse',
        'Relationships' => 'setRelationships'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'PaginationResponse' => 'getPaginationResponse',
        'Relationships' => 'getRelationships'
    ];


    

    

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['PaginationResponse'] = isset($data['PaginationResponse']) ? $data['PaginationResponse'] : null;
        $this->container['Relationships'] = isset($data['Relationships']) ? $data['Relationships'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = parent::listInvalidProperties();

        return $invalidProperties;
    }


    /**
     * Gets PaginationResponse
     *
     * @return \Nlocascio\Mindbody\Model\PaginationResponse
     */
    public function getPaginationResponse()
    {
        return $this->container['PaginationResponse'];
    }

    /**
     * Sets PaginationResponse
     *
     * @param \Nlocascio\Mindbody\Model\PaginationResponse $PaginationResponse Contains information about the pagination used.
     *
     * @return $this
     */
    public function setPaginationResponse($PaginationResponse): self
    {
        $this->container['PaginationResponse'] = $PaginationResponse;

        return $this;
    }

    /**
     * Gets Relationships
     *
     * @return \Nlocascio\Mindbody\Model\Relationship[]
     */
    public function getRelationships()
    {
        return $this->container['Relationships'];
    }

    /**
     * Sets Relationships
     *
     * @param \Nlocascio\Mindbody\Model\Relationship[] $Relationships A list of relationships.
     *
     * @return $this
     */
    public function setRelationships($Relationships): self
    {
        $this->container['Relationships'] = $Relationships;

        return $this;
    }
    
}


