<?php
/**
 * GetStaffPermissionsRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.23
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Nlocascio\Mindbody\Model;

/**
 * GetStaffPermissionsRequest Class Doc Comment
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 * @property int $StaffId The ID of the staff member whose permissions you want to return.
 *
 */
class GetStaffPermissionsRequest extends BaseModel
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'GetStaffPermissionsRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'StaffId' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static $swaggerFormats = [
        'StaffId' => 'int64'
    ];


    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'StaffId' => 'StaffId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'StaffId' => 'setStaffId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'StaffId' => 'getStaffId'
    ];


    

    

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['StaffId'] = isset($data['StaffId']) ? $data['StaffId'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = parent::listInvalidProperties();

        if ($this->container['StaffId'] === null) {
            $invalidProperties[] = "'StaffId' can't be null";
        }
        return $invalidProperties;
    }


    /**
     * Gets StaffId
     *
     * @return int
     */
    public function getStaffId()
    {
        return $this->container['StaffId'];
    }

    /**
     * Sets StaffId
     *
     * @param int $StaffId The ID of the staff member whose permissions you want to return.
     *
     * @return $this
     */
    public function setStaffId($StaffId): self
    {
        $this->container['StaffId'] = $StaffId;

        return $this;
    }
    
}


