<?php
/**
 * GetStaffSessionTypesRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.23
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Nlocascio\Mindbody\Model;

/**
 * GetStaffSessionTypesRequest Class Doc Comment
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class GetStaffSessionTypesRequest extends BaseModel
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'GetStaffSessionTypesRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'StaffId' => 'int',
        'ProgramIds' => 'int[]',
        'OnlineOnly' => 'bool',
        'Limit' => 'int',
        'Offset' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'StaffId' => 'int64',
        'ProgramIds' => 'int32',
        'OnlineOnly' => null,
        'Limit' => 'int32',
        'Offset' => 'int32'
    ];


    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'StaffId' => 'StaffId',
        'ProgramIds' => 'ProgramIds',
        'OnlineOnly' => 'OnlineOnly',
        'Limit' => 'Limit',
        'Offset' => 'Offset'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'StaffId' => 'setStaffId',
        'ProgramIds' => 'setProgramIds',
        'OnlineOnly' => 'setOnlineOnly',
        'Limit' => 'setLimit',
        'Offset' => 'setOffset'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'StaffId' => 'getStaffId',
        'ProgramIds' => 'getProgramIds',
        'OnlineOnly' => 'getOnlineOnly',
        'Limit' => 'getLimit',
        'Offset' => 'getOffset'
    ];


    

    

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['StaffId'] = isset($data['StaffId']) ? $data['StaffId'] : null;
        $this->container['ProgramIds'] = isset($data['ProgramIds']) ? $data['ProgramIds'] : null;
        $this->container['OnlineOnly'] = isset($data['OnlineOnly']) ? $data['OnlineOnly'] : null;
        $this->container['Limit'] = isset($data['Limit']) ? $data['Limit'] : null;
        $this->container['Offset'] = isset($data['Offset']) ? $data['Offset'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = parent::listInvalidProperties();

        if ($this->container['StaffId'] === null) {
            $invalidProperties[] = "'StaffId' can't be null";
        }
        return $invalidProperties;
    }


    /**
     * Gets StaffId
     *
     * @return int
     */
    public function getStaffId(): int
    {
        return $this->container['StaffId'];
    }

    /**
     * Sets StaffId
     *
     * @param int $StaffId Filters returned session types to only those the staff member performs.  Staff should be active.
     *
     * @return $this
     */
    public function setStaffId($StaffId): self
    {
        $this->container['StaffId'] = $StaffId;

        return $this;
    }

    /**
     * Gets ProgramIds
     *
     * @return int[]
     */
    public function getProgramIds(): int[]
    {
        return $this->container['ProgramIds'];
    }

    /**
     * Sets ProgramIds
     *
     * @param int[] $ProgramIds Filters results to session types that belong in program IDs.
     *
     * @return $this
     */
    public function setProgramIds($ProgramIds): self
    {
        $this->container['ProgramIds'] = $ProgramIds;

        return $this;
    }

    /**
     * Gets OnlineOnly
     *
     * @return bool
     */
    public function getOnlineOnly(): bool
    {
        return $this->container['OnlineOnly'];
    }

    /**
     * Sets OnlineOnly
     *
     * @param bool $OnlineOnly Only session types that can be booked online.
     *
     * @return $this
     */
    public function setOnlineOnly($OnlineOnly): self
    {
        $this->container['OnlineOnly'] = $OnlineOnly;

        return $this;
    }

    /**
     * Gets Limit
     *
     * @return int
     */
    public function getLimit(): int
    {
        return $this->container['Limit'];
    }

    /**
     * Sets Limit
     *
     * @param int $Limit Number of results to include, defaults to 100
     *
     * @return $this
     */
    public function setLimit($Limit): self
    {
        $this->container['Limit'] = $Limit;

        return $this;
    }

    /**
     * Gets Offset
     *
     * @return int
     */
    public function getOffset(): int
    {
        return $this->container['Offset'];
    }

    /**
     * Sets Offset
     *
     * @param int $Offset Page offset, defaults to 0.
     *
     * @return $this
     */
    public function setOffset($Offset): self
    {
        $this->container['Offset'] = $Offset;

        return $this;
    }
    
}


