<?php
/**
 * GetScheduleItemsRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.40-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Nlocascio\Mindbody\Model;

/**
 * GetScheduleItemsRequest Class Doc Comment
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 * @property int[] $LocationIds A list of requested location IDs.
 * @property int[] $StaffIds A list of requested staff IDs.
 * @property \DateTime $StartDate The start date of the requested date range.   <br />Default: **today’s date**
 * @property \DateTime $EndDate The end date of the requested date range.   <br />Default: **today’s date**
 * @property bool $IgnorePrepFinishTimes When `true`, appointment preparation and finish unavailabilities are not returned.   <br />Default: **false**
 * @property int $Limit Number of results to include, defaults to 100
 * @property int $Offset Page offset, defaults to 0.
 *
 */
class GetScheduleItemsRequest extends BaseModel
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'GetScheduleItemsRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'LocationIds' => 'int[]',
        'StaffIds' => 'int[]',
        'StartDate' => '\DateTime',
        'EndDate' => '\DateTime',
        'IgnorePrepFinishTimes' => 'bool',
        'Limit' => 'int',
        'Offset' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static $swaggerFormats = [
        'LocationIds' => 'int32',
        'StaffIds' => 'int64',
        'StartDate' => 'date-time',
        'EndDate' => 'date-time',
        'IgnorePrepFinishTimes' => null,
        'Limit' => 'int32',
        'Offset' => 'int32'
    ];


    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'LocationIds' => 'LocationIds',
        'StaffIds' => 'StaffIds',
        'StartDate' => 'StartDate',
        'EndDate' => 'EndDate',
        'IgnorePrepFinishTimes' => 'IgnorePrepFinishTimes',
        'Limit' => 'Limit',
        'Offset' => 'Offset'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'LocationIds' => 'setLocationIds',
        'StaffIds' => 'setStaffIds',
        'StartDate' => 'setStartDate',
        'EndDate' => 'setEndDate',
        'IgnorePrepFinishTimes' => 'setIgnorePrepFinishTimes',
        'Limit' => 'setLimit',
        'Offset' => 'setOffset'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'LocationIds' => 'getLocationIds',
        'StaffIds' => 'getStaffIds',
        'StartDate' => 'getStartDate',
        'EndDate' => 'getEndDate',
        'IgnorePrepFinishTimes' => 'getIgnorePrepFinishTimes',
        'Limit' => 'getLimit',
        'Offset' => 'getOffset'
    ];


    

    

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['LocationIds'] = isset($data['LocationIds']) ? $data['LocationIds'] : null;
        $this->container['StaffIds'] = isset($data['StaffIds']) ? $data['StaffIds'] : null;
        $this->container['StartDate'] = isset($data['StartDate']) ? $data['StartDate'] : null;
        $this->container['EndDate'] = isset($data['EndDate']) ? $data['EndDate'] : null;
        $this->container['IgnorePrepFinishTimes'] = isset($data['IgnorePrepFinishTimes']) ? $data['IgnorePrepFinishTimes'] : null;
        $this->container['Limit'] = isset($data['Limit']) ? $data['Limit'] : null;
        $this->container['Offset'] = isset($data['Offset']) ? $data['Offset'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = parent::listInvalidProperties();

        return $invalidProperties;
    }


    /**
     * Gets LocationIds
     *
     * @return int[]
     */
    public function getLocationIds()
    {
        return $this->container['LocationIds'];
    }

    /**
     * Sets LocationIds
     *
     * @param int[] $LocationIds A list of requested location IDs.
     *
     * @return $this
     */
    public function setLocationIds($LocationIds): self
    {
        $this->container['LocationIds'] = $LocationIds;

        return $this;
    }

    /**
     * Gets StaffIds
     *
     * @return int[]
     */
    public function getStaffIds()
    {
        return $this->container['StaffIds'];
    }

    /**
     * Sets StaffIds
     *
     * @param int[] $StaffIds A list of requested staff IDs.
     *
     * @return $this
     */
    public function setStaffIds($StaffIds): self
    {
        $this->container['StaffIds'] = $StaffIds;

        return $this;
    }

    /**
     * Gets StartDate
     *
     * @return \DateTime
     */
    public function getStartDate()
    {
        return $this->container['StartDate'];
    }

    /**
     * Sets StartDate
     *
     * @param \DateTime $StartDate The start date of the requested date range.   <br />Default: **today’s date**
     *
     * @return $this
     */
    public function setStartDate($StartDate): self
    {
        $this->container['StartDate'] = $StartDate;

        return $this;
    }

    /**
     * Gets EndDate
     *
     * @return \DateTime
     */
    public function getEndDate()
    {
        return $this->container['EndDate'];
    }

    /**
     * Sets EndDate
     *
     * @param \DateTime $EndDate The end date of the requested date range.   <br />Default: **today’s date**
     *
     * @return $this
     */
    public function setEndDate($EndDate): self
    {
        $this->container['EndDate'] = $EndDate;

        return $this;
    }

    /**
     * Gets IgnorePrepFinishTimes
     *
     * @return bool
     */
    public function getIgnorePrepFinishTimes()
    {
        return $this->container['IgnorePrepFinishTimes'];
    }

    /**
     * Sets IgnorePrepFinishTimes
     *
     * @param bool $IgnorePrepFinishTimes When `true`, appointment preparation and finish unavailabilities are not returned.   <br />Default: **false**
     *
     * @return $this
     */
    public function setIgnorePrepFinishTimes($IgnorePrepFinishTimes): self
    {
        $this->container['IgnorePrepFinishTimes'] = $IgnorePrepFinishTimes;

        return $this;
    }

    /**
     * Gets Limit
     *
     * @return int
     */
    public function getLimit()
    {
        return $this->container['Limit'];
    }

    /**
     * Sets Limit
     *
     * @param int $Limit Number of results to include, defaults to 100
     *
     * @return $this
     */
    public function setLimit($Limit): self
    {
        $this->container['Limit'] = $Limit;

        return $this;
    }

    /**
     * Gets Offset
     *
     * @return int
     */
    public function getOffset()
    {
        return $this->container['Offset'];
    }

    /**
     * Sets Offset
     *
     * @param int $Offset Page offset, defaults to 0.
     *
     * @return $this
     */
    public function setOffset($Offset): self
    {
        $this->container['Offset'] = $Offset;

        return $this;
    }
    
}


