<?php
/**
 * GetSitesRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.50
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Nlocascio\Mindbody\Model;

/**
 * GetSitesRequest Class Doc Comment
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 * @property int[] $SiteIds List of the requested site IDs. When omitted, returns all sites that the source has access to.
 * @property bool $IncludeLeadChannels This is an optional parameter to get lead channels for a Site.
 * @property int $Limit Number of results to include, defaults to 100
 * @property int $Offset Page offset, defaults to 0.
 *
 */
class GetSitesRequest extends BaseModel
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'GetSitesRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'SiteIds' => 'int[]',
        'IncludeLeadChannels' => 'bool',
        'Limit' => 'int',
        'Offset' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static $swaggerFormats = [
        'SiteIds' => 'int32',
        'IncludeLeadChannels' => null,
        'Limit' => 'int32',
        'Offset' => 'int32'
    ];


    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'SiteIds' => 'SiteIds',
        'IncludeLeadChannels' => 'IncludeLeadChannels',
        'Limit' => 'Limit',
        'Offset' => 'Offset'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'SiteIds' => 'setSiteIds',
        'IncludeLeadChannels' => 'setIncludeLeadChannels',
        'Limit' => 'setLimit',
        'Offset' => 'setOffset'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'SiteIds' => 'getSiteIds',
        'IncludeLeadChannels' => 'getIncludeLeadChannels',
        'Limit' => 'getLimit',
        'Offset' => 'getOffset'
    ];


    

    

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['SiteIds'] = isset($data['SiteIds']) ? $data['SiteIds'] : null;
        $this->container['IncludeLeadChannels'] = isset($data['IncludeLeadChannels']) ? $data['IncludeLeadChannels'] : null;
        $this->container['Limit'] = isset($data['Limit']) ? $data['Limit'] : null;
        $this->container['Offset'] = isset($data['Offset']) ? $data['Offset'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = parent::listInvalidProperties();

        return $invalidProperties;
    }


    /**
     * Gets SiteIds
     *
     * @return int[]
     */
    public function getSiteIds()
    {
        return $this->container['SiteIds'];
    }

    /**
     * Sets SiteIds
     *
     * @param int[] $SiteIds List of the requested site IDs. When omitted, returns all sites that the source has access to.
     *
     * @return $this
     */
    public function setSiteIds($SiteIds): self
    {
        $this->container['SiteIds'] = $SiteIds;

        return $this;
    }

    /**
     * Gets IncludeLeadChannels
     *
     * @return bool
     */
    public function getIncludeLeadChannels()
    {
        return $this->container['IncludeLeadChannels'];
    }

    /**
     * Sets IncludeLeadChannels
     *
     * @param bool $IncludeLeadChannels This is an optional parameter to get lead channels for a Site.
     *
     * @return $this
     */
    public function setIncludeLeadChannels($IncludeLeadChannels): self
    {
        $this->container['IncludeLeadChannels'] = $IncludeLeadChannels;

        return $this;
    }

    /**
     * Gets Limit
     *
     * @return int
     */
    public function getLimit()
    {
        return $this->container['Limit'];
    }

    /**
     * Sets Limit
     *
     * @param int $Limit Number of results to include, defaults to 100
     *
     * @return $this
     */
    public function setLimit($Limit): self
    {
        $this->container['Limit'] = $Limit;

        return $this;
    }

    /**
     * Gets Offset
     *
     * @return int
     */
    public function getOffset()
    {
        return $this->container['Offset'];
    }

    /**
     * Sets Offset
     *
     * @param int $Offset Page offset, defaults to 0.
     *
     * @return $this
     */
    public function setOffset($Offset): self
    {
        $this->container['Offset'] = $Offset;

        return $this;
    }
    
}


