<?php
/**
 * GetTransactionsRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.50
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Nlocascio\Mindbody\Model;

/**
 * GetTransactionsRequest Class Doc Comment
 *
 * @category Class
 * @description Transactions Request
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 * @property int $SaleId Filters the transaction results with the ID number associated with the sale.
 * @property int $TransactionId Filters the transaction results with the ID number generated when the sale is processed.
 * @property int $ClientId Filters results to the requested client ID.
 * @property int $LocationId Filters the transaction results with the ID number associated with the location of the sale.
 * @property string $Status Filters the transaction results by the estimated transaction status.
 * @property \DateTime $TransactionStartDateTime Filters the transaction results that happpened after this date and time.   Default: **today’s date**
 * @property \DateTime $TransactionEndDateTime Filters the transaction results that happpened before this date and time.   Default: **today’s date**
 * @property int $Limit Number of results to include, defaults to 100
 * @property int $Offset Page offset, defaults to 0.
 *
 */
class GetTransactionsRequest extends BaseModel
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'GetTransactionsRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'SaleId' => 'int',
        'TransactionId' => 'int',
        'ClientId' => 'int',
        'LocationId' => 'int',
        'Status' => 'string',
        'TransactionStartDateTime' => '\DateTime',
        'TransactionEndDateTime' => '\DateTime',
        'Limit' => 'int',
        'Offset' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static $swaggerFormats = [
        'SaleId' => 'int64',
        'TransactionId' => 'int32',
        'ClientId' => 'int64',
        'LocationId' => 'int32',
        'Status' => null,
        'TransactionStartDateTime' => 'date-time',
        'TransactionEndDateTime' => 'date-time',
        'Limit' => 'int32',
        'Offset' => 'int32'
    ];


    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'SaleId' => 'SaleId',
        'TransactionId' => 'TransactionId',
        'ClientId' => 'ClientId',
        'LocationId' => 'LocationId',
        'Status' => 'Status',
        'TransactionStartDateTime' => 'TransactionStartDateTime',
        'TransactionEndDateTime' => 'TransactionEndDateTime',
        'Limit' => 'Limit',
        'Offset' => 'Offset'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'SaleId' => 'setSaleId',
        'TransactionId' => 'setTransactionId',
        'ClientId' => 'setClientId',
        'LocationId' => 'setLocationId',
        'Status' => 'setStatus',
        'TransactionStartDateTime' => 'setTransactionStartDateTime',
        'TransactionEndDateTime' => 'setTransactionEndDateTime',
        'Limit' => 'setLimit',
        'Offset' => 'setOffset'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'SaleId' => 'getSaleId',
        'TransactionId' => 'getTransactionId',
        'ClientId' => 'getClientId',
        'LocationId' => 'getLocationId',
        'Status' => 'getStatus',
        'TransactionStartDateTime' => 'getTransactionStartDateTime',
        'TransactionEndDateTime' => 'getTransactionEndDateTime',
        'Limit' => 'getLimit',
        'Offset' => 'getOffset'
    ];


    

    

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['SaleId'] = isset($data['SaleId']) ? $data['SaleId'] : null;
        $this->container['TransactionId'] = isset($data['TransactionId']) ? $data['TransactionId'] : null;
        $this->container['ClientId'] = isset($data['ClientId']) ? $data['ClientId'] : null;
        $this->container['LocationId'] = isset($data['LocationId']) ? $data['LocationId'] : null;
        $this->container['Status'] = isset($data['Status']) ? $data['Status'] : null;
        $this->container['TransactionStartDateTime'] = isset($data['TransactionStartDateTime']) ? $data['TransactionStartDateTime'] : null;
        $this->container['TransactionEndDateTime'] = isset($data['TransactionEndDateTime']) ? $data['TransactionEndDateTime'] : null;
        $this->container['Limit'] = isset($data['Limit']) ? $data['Limit'] : null;
        $this->container['Offset'] = isset($data['Offset']) ? $data['Offset'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = parent::listInvalidProperties();

        return $invalidProperties;
    }


    /**
     * Gets SaleId
     *
     * @return int
     */
    public function getSaleId()
    {
        return $this->container['SaleId'];
    }

    /**
     * Sets SaleId
     *
     * @param int $SaleId Filters the transaction results with the ID number associated with the sale.
     *
     * @return $this
     */
    public function setSaleId($SaleId): self
    {
        $this->container['SaleId'] = $SaleId;

        return $this;
    }

    /**
     * Gets TransactionId
     *
     * @return int
     */
    public function getTransactionId()
    {
        return $this->container['TransactionId'];
    }

    /**
     * Sets TransactionId
     *
     * @param int $TransactionId Filters the transaction results with the ID number generated when the sale is processed.
     *
     * @return $this
     */
    public function setTransactionId($TransactionId): self
    {
        $this->container['TransactionId'] = $TransactionId;

        return $this;
    }

    /**
     * Gets ClientId
     *
     * @return int
     */
    public function getClientId()
    {
        return $this->container['ClientId'];
    }

    /**
     * Sets ClientId
     *
     * @param int $ClientId Filters results to the requested client ID.
     *
     * @return $this
     */
    public function setClientId($ClientId): self
    {
        $this->container['ClientId'] = $ClientId;

        return $this;
    }

    /**
     * Gets LocationId
     *
     * @return int
     */
    public function getLocationId()
    {
        return $this->container['LocationId'];
    }

    /**
     * Sets LocationId
     *
     * @param int $LocationId Filters the transaction results with the ID number associated with the location of the sale.
     *
     * @return $this
     */
    public function setLocationId($LocationId): self
    {
        $this->container['LocationId'] = $LocationId;

        return $this;
    }

    /**
     * Gets Status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['Status'];
    }

    /**
     * Sets Status
     *
     * @param string $Status Filters the transaction results by the estimated transaction status.
     *
     * @return $this
     */
    public function setStatus($Status): self
    {
        $this->container['Status'] = $Status;

        return $this;
    }

    /**
     * Gets TransactionStartDateTime
     *
     * @return \DateTime
     */
    public function getTransactionStartDateTime()
    {
        return $this->container['TransactionStartDateTime'];
    }

    /**
     * Sets TransactionStartDateTime
     *
     * @param \DateTime $TransactionStartDateTime Filters the transaction results that happpened after this date and time.   Default: **today’s date**
     *
     * @return $this
     */
    public function setTransactionStartDateTime($TransactionStartDateTime): self
    {
        $this->container['TransactionStartDateTime'] = $TransactionStartDateTime;

        return $this;
    }

    /**
     * Gets TransactionEndDateTime
     *
     * @return \DateTime
     */
    public function getTransactionEndDateTime()
    {
        return $this->container['TransactionEndDateTime'];
    }

    /**
     * Sets TransactionEndDateTime
     *
     * @param \DateTime $TransactionEndDateTime Filters the transaction results that happpened before this date and time.   Default: **today’s date**
     *
     * @return $this
     */
    public function setTransactionEndDateTime($TransactionEndDateTime): self
    {
        $this->container['TransactionEndDateTime'] = $TransactionEndDateTime;

        return $this;
    }

    /**
     * Gets Limit
     *
     * @return int
     */
    public function getLimit()
    {
        return $this->container['Limit'];
    }

    /**
     * Sets Limit
     *
     * @param int $Limit Number of results to include, defaults to 100
     *
     * @return $this
     */
    public function setLimit($Limit): self
    {
        $this->container['Limit'] = $Limit;

        return $this;
    }

    /**
     * Gets Offset
     *
     * @return int
     */
    public function getOffset()
    {
        return $this->container['Offset'];
    }

    /**
     * Sets Offset
     *
     * @param int $Offset Page offset, defaults to 0.
     *
     * @return $this
     */
    public function setOffset($Offset): self
    {
        $this->container['Offset'] = $Offset;

        return $this;
    }
    
}


