<?php
/**
 * IssueResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Nlocascio\Mindbody\Model;

/**
 * IssueResponse Class Doc Comment
 *
 * @category Class
 * @description POST UserToken/Issue successful response
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 * @property string $TokenType TokenType
 * @property string $AccessToken The authentication token value.
 * @property \DateTime $Expires Token expiration in UTC.
 * @property \Nlocascio\Mindbody\Model\User $User Contains information about the user represented by the access token.
 *
 */
class IssueResponse extends BaseModel
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $swaggerModelName = 'IssueResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static array $swaggerTypes = [
        'TokenType' => 'string',
        'AccessToken' => 'string',
        'Expires' => '\DateTime',
        'User' => '\Nlocascio\Mindbody\Model\User'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $swaggerFormats = [
        'TokenType' => null,
        'AccessToken' => null,
        'Expires' => 'date-time',
        'User' => null
    ];


    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static array $attributeMap = [
        'TokenType' => 'TokenType',
        'AccessToken' => 'AccessToken',
        'Expires' => 'Expires',
        'User' => 'User'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static array $setters = [
        'TokenType' => 'setTokenType',
        'AccessToken' => 'setAccessToken',
        'Expires' => 'setExpires',
        'User' => 'setUser'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static array $getters = [
        'TokenType' => 'getTokenType',
        'AccessToken' => 'getAccessToken',
        'Expires' => 'getExpires',
        'User' => 'getUser'
    ];


    

    

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->container['TokenType'] = isset($data['TokenType']) ? $data['TokenType'] : null;
        $this->container['AccessToken'] = isset($data['AccessToken']) ? $data['AccessToken'] : null;
        $this->container['Expires'] = isset($data['Expires']) ? $data['Expires'] : null;
        $this->container['User'] = isset($data['User']) ? $data['User'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = parent::listInvalidProperties();

        return $invalidProperties;
    }


    /**
     * Gets TokenType
     *
     * @return string
     */
    public function getTokenType(): string|null
    {
        return $this->container['TokenType'];
    }

    /**
     * Sets TokenType
     *
     * @param string $TokenType TokenType
     *
     * @return $this
     */


    public function setTokenType(string $TokenType): static
    {
        $this->container['TokenType'] = $TokenType;

        return $this;
    }

    /**
     * Gets AccessToken
     *
     * @return string
     */
    public function getAccessToken(): string|null
    {
        return $this->container['AccessToken'];
    }

    /**
     * Sets AccessToken
     *
     * @param string $AccessToken The authentication token value.
     *
     * @return $this
     */


    public function setAccessToken(string $AccessToken): static
    {
        $this->container['AccessToken'] = $AccessToken;

        return $this;
    }

    /**
     * Gets Expires
     *
     * @return \DateTime
     */
    public function getExpires(): \DateTime|null
    {
        return $this->container['Expires'];
    }

    /**
     * Sets Expires
     *
     * @param \DateTime $Expires Token expiration in UTC.
     *
     * @return $this
     */


    public function setExpires(\DateTime $Expires): static
    {
        $this->container['Expires'] = $Expires;

        return $this;
    }

    /**
     * Gets User
     *
     * @return \Nlocascio\Mindbody\Model\User
     */
    public function getUser(): \Nlocascio\Mindbody\Model\User|null
    {
        return $this->container['User'];
    }

    /**
     * Sets User
     *
     * @param \Nlocascio\Mindbody\Model\User $User Contains information about the user represented by the access token.
     *
     * @return $this
     */


    public function setUser(\Nlocascio\Mindbody\Model\User $User): static
    {
        $this->container['User'] = $User;

        return $this;
    }
    
}


