<?php
/**
 * ItineraryEventRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Nlocascio\Mindbody\Model;

/**
 * ItineraryEventRequest Class Doc Comment
 *
 * @category Class
 * @description Represents a single event (service) within an itinerary-based appointment booking.
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 * @property int $SessionTypeId The session type (service) associated with this event.
 * @property \DateTime $StartDateTime The start date and time of this event.
 * @property int $Duration The duration of the event in minutes. If not provided or 0, the service's default duration is used.
 * @property string $Notes Any notes specific to this event.
 * @property bool $StaffRequested When `true`, indicates that the staff member was requested specifically by the client.
 * @property int $StaffId The ID of the staff member for this event. Optional if using waitlist or if staff assignment is flexible.
 * @property int[] $ResourceIds A list of resource IDs (rooms, equipment) to associate with this event.
 * @property \Nlocascio\Mindbody\Model\AppointmentModelsItineraryAddOn[] $AddOns A list of add-on services attached to this event.
 *
 */
class ItineraryEventRequest extends BaseModel
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $swaggerModelName = 'ItineraryEventRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static array $swaggerTypes = [
        'SessionTypeId' => 'int',
        'StartDateTime' => '\DateTime',
        'Duration' => 'int',
        'Notes' => 'string',
        'StaffRequested' => 'bool',
        'StaffId' => 'int',
        'ResourceIds' => 'int[]',
        'AddOns' => '\Nlocascio\Mindbody\Model\AppointmentModelsItineraryAddOn[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $swaggerFormats = [
        'SessionTypeId' => 'int32',
        'StartDateTime' => 'date-time',
        'Duration' => 'int32',
        'Notes' => null,
        'StaffRequested' => null,
        'StaffId' => 'int64',
        'ResourceIds' => 'int32',
        'AddOns' => null
    ];


    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static array $attributeMap = [
        'SessionTypeId' => 'SessionTypeId',
        'StartDateTime' => 'StartDateTime',
        'Duration' => 'Duration',
        'Notes' => 'Notes',
        'StaffRequested' => 'StaffRequested',
        'StaffId' => 'StaffId',
        'ResourceIds' => 'ResourceIds',
        'AddOns' => 'AddOns'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static array $setters = [
        'SessionTypeId' => 'setSessionTypeId',
        'StartDateTime' => 'setStartDateTime',
        'Duration' => 'setDuration',
        'Notes' => 'setNotes',
        'StaffRequested' => 'setStaffRequested',
        'StaffId' => 'setStaffId',
        'ResourceIds' => 'setResourceIds',
        'AddOns' => 'setAddOns'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static array $getters = [
        'SessionTypeId' => 'getSessionTypeId',
        'StartDateTime' => 'getStartDateTime',
        'Duration' => 'getDuration',
        'Notes' => 'getNotes',
        'StaffRequested' => 'getStaffRequested',
        'StaffId' => 'getStaffId',
        'ResourceIds' => 'getResourceIds',
        'AddOns' => 'getAddOns'
    ];


    

    

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->container['SessionTypeId'] = isset($data['SessionTypeId']) ? $data['SessionTypeId'] : null;
        $this->container['StartDateTime'] = isset($data['StartDateTime']) ? $data['StartDateTime'] : null;
        $this->container['Duration'] = isset($data['Duration']) ? $data['Duration'] : null;
        $this->container['Notes'] = isset($data['Notes']) ? $data['Notes'] : null;
        $this->container['StaffRequested'] = isset($data['StaffRequested']) ? $data['StaffRequested'] : null;
        $this->container['StaffId'] = isset($data['StaffId']) ? $data['StaffId'] : null;
        $this->container['ResourceIds'] = isset($data['ResourceIds']) ? $data['ResourceIds'] : null;
        $this->container['AddOns'] = isset($data['AddOns']) ? $data['AddOns'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = parent::listInvalidProperties();

        return $invalidProperties;
    }


    /**
     * Gets SessionTypeId
     *
     * @return int
     */
    public function getSessionTypeId(): int
    {
        return $this->container['SessionTypeId'];
    }

    /**
     * Sets SessionTypeId
     *
     * @param int $SessionTypeId The session type (service) associated with this event.
     *
     * @return $this
     */


    public function setSessionTypeId(int $SessionTypeId): static
    {
        $this->container['SessionTypeId'] = $SessionTypeId;

        return $this;
    }

    /**
     * Gets StartDateTime
     *
     * @return \DateTime
     */
    public function getStartDateTime(): \DateTime
    {
        return $this->container['StartDateTime'];
    }

    /**
     * Sets StartDateTime
     *
     * @param \DateTime $StartDateTime The start date and time of this event.
     *
     * @return $this
     */


    public function setStartDateTime(\DateTime $StartDateTime): static
    {
        $this->container['StartDateTime'] = $StartDateTime;

        return $this;
    }

    /**
     * Gets Duration
     *
     * @return int
     */
    public function getDuration(): int
    {
        return $this->container['Duration'];
    }

    /**
     * Sets Duration
     *
     * @param int $Duration The duration of the event in minutes. If not provided or 0, the service's default duration is used.
     *
     * @return $this
     */


    public function setDuration(int $Duration): static
    {
        $this->container['Duration'] = $Duration;

        return $this;
    }

    /**
     * Gets Notes
     *
     * @return string
     */
    public function getNotes(): string
    {
        return $this->container['Notes'];
    }

    /**
     * Sets Notes
     *
     * @param string $Notes Any notes specific to this event.
     *
     * @return $this
     */


    public function setNotes(string $Notes): static
    {
        $this->container['Notes'] = $Notes;

        return $this;
    }

    /**
     * Gets StaffRequested
     *
     * @return bool
     */
    public function getStaffRequested(): bool
    {
        return $this->container['StaffRequested'];
    }

    /**
     * Sets StaffRequested
     *
     * @param bool $StaffRequested When `true`, indicates that the staff member was requested specifically by the client.
     *
     * @return $this
     */


    public function setStaffRequested(bool $StaffRequested): static
    {
        $this->container['StaffRequested'] = $StaffRequested;

        return $this;
    }

    /**
     * Gets StaffId
     *
     * @return int
     */
    public function getStaffId(): int
    {
        return $this->container['StaffId'];
    }

    /**
     * Sets StaffId
     *
     * @param int $StaffId The ID of the staff member for this event. Optional if using waitlist or if staff assignment is flexible.
     *
     * @return $this
     */


    public function setStaffId(int $StaffId): static
    {
        $this->container['StaffId'] = $StaffId;

        return $this;
    }

    /**
     * Gets ResourceIds
     *
     * @return int[]
     */
    public function getResourceIds(): array
    {
        return $this->container['ResourceIds'];
    }

    /**
     * Sets ResourceIds
     *
     * @param int[] $ResourceIds A list of resource IDs (rooms, equipment) to associate with this event.
     *
     * @return $this
     */


    public function setResourceIds(array $ResourceIds): static
    {
        $this->container['ResourceIds'] = $ResourceIds;

        return $this;
    }

    /**
     * Gets AddOns
     *
     * @return \Nlocascio\Mindbody\Model\AppointmentModelsItineraryAddOn[]
     */
    public function getAddOns(): array
    {
        return $this->container['AddOns'];
    }

    /**
     * Sets AddOns
     *
     * @param \Nlocascio\Mindbody\Model\AppointmentModelsItineraryAddOn[] $AddOns A list of add-on services attached to this event.
     *
     * @return $this
     */


    public function setAddOns(array $AddOns): static
    {
        $this->container['AddOns'] = $AddOns;

        return $this;
    }
    
}


