<?php
/**
 * MobileProvider
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.28
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Nlocascio\Mindbody\Model;

/**
 * MobileProvider Class Doc Comment
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 * @property int $Id Id
 * @property bool $Active Active
 * @property string $ProviderName ProviderName
 * @property string $ProviderAddress ProviderAddress
 *
 */
class MobileProvider extends BaseModel implements ModelWithId
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'MobileProvider';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'Id' => 'int',
        'Active' => 'bool',
        'ProviderName' => 'string',
        'ProviderAddress' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static $swaggerFormats = [
        'Id' => 'int32',
        'Active' => null,
        'ProviderName' => null,
        'ProviderAddress' => null
    ];


    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'Id' => 'Id',
        'Active' => 'Active',
        'ProviderName' => 'ProviderName',
        'ProviderAddress' => 'ProviderAddress'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'Id' => 'setId',
        'Active' => 'setActive',
        'ProviderName' => 'setProviderName',
        'ProviderAddress' => 'setProviderAddress'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'Id' => 'getId',
        'Active' => 'getActive',
        'ProviderName' => 'getProviderName',
        'ProviderAddress' => 'getProviderAddress'
    ];


    

    

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['Id'] = isset($data['Id']) ? $data['Id'] : null;
        $this->container['Active'] = isset($data['Active']) ? $data['Active'] : null;
        $this->container['ProviderName'] = isset($data['ProviderName']) ? $data['ProviderName'] : null;
        $this->container['ProviderAddress'] = isset($data['ProviderAddress']) ? $data['ProviderAddress'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = parent::listInvalidProperties();

        return $invalidProperties;
    }


    /**
     * Gets Id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['Id'];
    }

    /**
     * Sets Id
     *
     * @param int $Id Id
     *
     * @return $this
     */
    public function setId($Id): self
    {
        $this->container['Id'] = $Id;

        return $this;
    }

    /**
     * Gets Active
     *
     * @return bool
     */
    public function getActive()
    {
        return $this->container['Active'];
    }

    /**
     * Sets Active
     *
     * @param bool $Active Active
     *
     * @return $this
     */
    public function setActive($Active): self
    {
        $this->container['Active'] = $Active;

        return $this;
    }

    /**
     * Gets ProviderName
     *
     * @return string
     */
    public function getProviderName()
    {
        return $this->container['ProviderName'];
    }

    /**
     * Sets ProviderName
     *
     * @param string $ProviderName ProviderName
     *
     * @return $this
     */
    public function setProviderName($ProviderName): self
    {
        $this->container['ProviderName'] = $ProviderName;

        return $this;
    }

    /**
     * Gets ProviderAddress
     *
     * @return string
     */
    public function getProviderAddress()
    {
        return $this->container['ProviderAddress'];
    }

    /**
     * Sets ProviderAddress
     *
     * @param string $ProviderAddress ProviderAddress
     *
     * @return $this
     */
    public function setProviderAddress($ProviderAddress): self
    {
        $this->container['ProviderAddress'] = $ProviderAddress;

        return $this;
    }
    
}


