<?php
/**
 * Package
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Nlocascio\Mindbody\Model;

/**
 * Package Class Doc Comment
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 * @property int $Id The ID of the package.
 * @property string $Name The name of the package.
 * @property double $DiscountPercentage The discount percentage applied to the package.
 * @property bool $SellOnline When `true`, only products that can be sold online are returned.<br />  When `false`, all products are returned.
 * @property \Nlocascio\Mindbody\Model\Service[] $Services Information about the services in the packages.
 * @property \Nlocascio\Mindbody\Model\Product[] $Products Information about the products in the packages.
 *
 */
class Package extends BaseModel implements ModelWithIntId
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $swaggerModelName = 'Package';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static array $swaggerTypes = [
        'Id' => 'int',
        'Name' => 'string',
        'DiscountPercentage' => 'double',
        'SellOnline' => 'bool',
        'Services' => '\Nlocascio\Mindbody\Model\Service[]',
        'Products' => '\Nlocascio\Mindbody\Model\Product[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $swaggerFormats = [
        'Id' => 'int32',
        'Name' => null,
        'DiscountPercentage' => 'double',
        'SellOnline' => null,
        'Services' => null,
        'Products' => null
    ];


    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static array $attributeMap = [
        'Id' => 'Id',
        'Name' => 'Name',
        'DiscountPercentage' => 'DiscountPercentage',
        'SellOnline' => 'SellOnline',
        'Services' => 'Services',
        'Products' => 'Products'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static array $setters = [
        'Id' => 'setId',
        'Name' => 'setName',
        'DiscountPercentage' => 'setDiscountPercentage',
        'SellOnline' => 'setSellOnline',
        'Services' => 'setServices',
        'Products' => 'setProducts'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static array $getters = [
        'Id' => 'getId',
        'Name' => 'getName',
        'DiscountPercentage' => 'getDiscountPercentage',
        'SellOnline' => 'getSellOnline',
        'Services' => 'getServices',
        'Products' => 'getProducts'
    ];


    

    

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->container['Id'] = isset($data['Id']) ? $data['Id'] : null;
        $this->container['Name'] = isset($data['Name']) ? $data['Name'] : null;
        $this->container['DiscountPercentage'] = isset($data['DiscountPercentage']) ? $data['DiscountPercentage'] : null;
        $this->container['SellOnline'] = isset($data['SellOnline']) ? $data['SellOnline'] : null;
        $this->container['Services'] = isset($data['Services']) ? $data['Services'] : null;
        $this->container['Products'] = isset($data['Products']) ? $data['Products'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = parent::listInvalidProperties();

        return $invalidProperties;
    }


    /**
     * Gets Id
     *
     * @return int
     */
    public function getId(): int|null
    {
        return $this->container['Id'];
    }

    /**
     * Sets Id
     *
     * @param int $Id The ID of the package.
     *
     * @return $this
     */


    public function setId(int $Id): static
    {
        $this->container['Id'] = $Id;

        return $this;
    }

    /**
     * Gets Name
     *
     * @return string
     */
    public function getName(): string|null
    {
        return $this->container['Name'];
    }

    /**
     * Sets Name
     *
     * @param string $Name The name of the package.
     *
     * @return $this
     */


    public function setName(string $Name): static
    {
        $this->container['Name'] = $Name;

        return $this;
    }

    /**
     * Gets DiscountPercentage
     *
     * @return double
     */
    public function getDiscountPercentage(): float|null
    {
        return $this->container['DiscountPercentage'];
    }

    /**
     * Sets DiscountPercentage
     *
     * @param double $DiscountPercentage The discount percentage applied to the package.
     *
     * @return $this
     */


    public function setDiscountPercentage(float $DiscountPercentage): static
    {
        $this->container['DiscountPercentage'] = $DiscountPercentage;

        return $this;
    }

    /**
     * Gets SellOnline
     *
     * @return bool
     */
    public function getSellOnline(): bool|null
    {
        return $this->container['SellOnline'];
    }

    /**
     * Sets SellOnline
     *
     * @param bool $SellOnline When `true`, only products that can be sold online are returned.<br />  When `false`, all products are returned.
     *
     * @return $this
     */


    public function setSellOnline(bool $SellOnline): static
    {
        $this->container['SellOnline'] = $SellOnline;

        return $this;
    }

    /**
     * Gets Services
     *
     * @return \Nlocascio\Mindbody\Model\Service[]
     */
    public function getServices(): array|null
    {
        return $this->container['Services'];
    }

    /**
     * Sets Services
     *
     * @param \Nlocascio\Mindbody\Model\Service[] $Services Information about the services in the packages.
     *
     * @return $this
     */


    public function setServices(array $Services): static
    {
        $this->container['Services'] = $Services;

        return $this;
    }

    /**
     * Gets Products
     *
     * @return \Nlocascio\Mindbody\Model\Product[]
     */
    public function getProducts(): array|null
    {
        return $this->container['Products'];
    }

    /**
     * Sets Products
     *
     * @param \Nlocascio\Mindbody\Model\Product[] $Products Information about the products in the packages.
     *
     * @return $this
     */


    public function setProducts(array $Products): static
    {
        $this->container['Products'] = $Products;

        return $this;
    }
    
}


