<?php
/**
 * PickASpotPickASpotClass
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.40-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Nlocascio\Mindbody\Model;

/**
 * PickASpotPickASpotClass Class Doc Comment
 *
 * @category Class
 * @description Contains information about the PickASpot classes.
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 * @property int $SiteId The unique ID of the Site.
 * @property int $LocationId The unique ID of the Location.
 * @property string $ClassId The unique ID of the Class.
 * @property string $ClassExternalId The unique Class external ID.
 * @property string $ClassName Contains the class name.
 * @property \DateTime $ClassStartTime Class start time.
 * @property \DateTime $ClassEndTime Class end time.
 * @property int $ClassMaximumCapacity Contains information about the Class maximum capacity.
 * @property string $RoomId The unique Room ID.
 * @property \Nlocascio\Mindbody\Model\PickASpotSpot $Spots Contains information about the spot detail.
 * @property \Nlocascio\Mindbody\Model\PickASpotReservation[] $Reservations Contains information about the reservation collection.
 *
 */
class PickASpotPickASpotClass extends BaseModel
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'PickASpot.PickASpotClass';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'SiteId' => 'int',
        'LocationId' => 'int',
        'ClassId' => 'string',
        'ClassExternalId' => 'string',
        'ClassName' => 'string',
        'ClassStartTime' => '\DateTime',
        'ClassEndTime' => '\DateTime',
        'ClassMaximumCapacity' => 'int',
        'RoomId' => 'string',
        'Spots' => '\Nlocascio\Mindbody\Model\PickASpotSpot',
        'Reservations' => '\Nlocascio\Mindbody\Model\PickASpotReservation[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static $swaggerFormats = [
        'SiteId' => 'int32',
        'LocationId' => 'int32',
        'ClassId' => null,
        'ClassExternalId' => null,
        'ClassName' => null,
        'ClassStartTime' => 'date-time',
        'ClassEndTime' => 'date-time',
        'ClassMaximumCapacity' => 'int32',
        'RoomId' => null,
        'Spots' => null,
        'Reservations' => null
    ];


    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'SiteId' => 'SiteId',
        'LocationId' => 'LocationId',
        'ClassId' => 'ClassId',
        'ClassExternalId' => 'ClassExternalId',
        'ClassName' => 'ClassName',
        'ClassStartTime' => 'ClassStartTime',
        'ClassEndTime' => 'ClassEndTime',
        'ClassMaximumCapacity' => 'ClassMaximumCapacity',
        'RoomId' => 'RoomId',
        'Spots' => 'Spots',
        'Reservations' => 'Reservations'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'SiteId' => 'setSiteId',
        'LocationId' => 'setLocationId',
        'ClassId' => 'setClassId',
        'ClassExternalId' => 'setClassExternalId',
        'ClassName' => 'setClassName',
        'ClassStartTime' => 'setClassStartTime',
        'ClassEndTime' => 'setClassEndTime',
        'ClassMaximumCapacity' => 'setClassMaximumCapacity',
        'RoomId' => 'setRoomId',
        'Spots' => 'setSpots',
        'Reservations' => 'setReservations'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'SiteId' => 'getSiteId',
        'LocationId' => 'getLocationId',
        'ClassId' => 'getClassId',
        'ClassExternalId' => 'getClassExternalId',
        'ClassName' => 'getClassName',
        'ClassStartTime' => 'getClassStartTime',
        'ClassEndTime' => 'getClassEndTime',
        'ClassMaximumCapacity' => 'getClassMaximumCapacity',
        'RoomId' => 'getRoomId',
        'Spots' => 'getSpots',
        'Reservations' => 'getReservations'
    ];


    

    

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['SiteId'] = isset($data['SiteId']) ? $data['SiteId'] : null;
        $this->container['LocationId'] = isset($data['LocationId']) ? $data['LocationId'] : null;
        $this->container['ClassId'] = isset($data['ClassId']) ? $data['ClassId'] : null;
        $this->container['ClassExternalId'] = isset($data['ClassExternalId']) ? $data['ClassExternalId'] : null;
        $this->container['ClassName'] = isset($data['ClassName']) ? $data['ClassName'] : null;
        $this->container['ClassStartTime'] = isset($data['ClassStartTime']) ? $data['ClassStartTime'] : null;
        $this->container['ClassEndTime'] = isset($data['ClassEndTime']) ? $data['ClassEndTime'] : null;
        $this->container['ClassMaximumCapacity'] = isset($data['ClassMaximumCapacity']) ? $data['ClassMaximumCapacity'] : null;
        $this->container['RoomId'] = isset($data['RoomId']) ? $data['RoomId'] : null;
        $this->container['Spots'] = isset($data['Spots']) ? $data['Spots'] : null;
        $this->container['Reservations'] = isset($data['Reservations']) ? $data['Reservations'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = parent::listInvalidProperties();

        return $invalidProperties;
    }


    /**
     * Gets SiteId
     *
     * @return int
     */
    public function getSiteId()
    {
        return $this->container['SiteId'];
    }

    /**
     * Sets SiteId
     *
     * @param int $SiteId The unique ID of the Site.
     *
     * @return $this
     */
    public function setSiteId($SiteId): self
    {
        $this->container['SiteId'] = $SiteId;

        return $this;
    }

    /**
     * Gets LocationId
     *
     * @return int
     */
    public function getLocationId()
    {
        return $this->container['LocationId'];
    }

    /**
     * Sets LocationId
     *
     * @param int $LocationId The unique ID of the Location.
     *
     * @return $this
     */
    public function setLocationId($LocationId): self
    {
        $this->container['LocationId'] = $LocationId;

        return $this;
    }

    /**
     * Gets ClassId
     *
     * @return string
     */
    public function getClassId()
    {
        return $this->container['ClassId'];
    }

    /**
     * Sets ClassId
     *
     * @param string $ClassId The unique ID of the Class.
     *
     * @return $this
     */
    public function setClassId($ClassId): self
    {
        $this->container['ClassId'] = $ClassId;

        return $this;
    }

    /**
     * Gets ClassExternalId
     *
     * @return string
     */
    public function getClassExternalId()
    {
        return $this->container['ClassExternalId'];
    }

    /**
     * Sets ClassExternalId
     *
     * @param string $ClassExternalId The unique Class external ID.
     *
     * @return $this
     */
    public function setClassExternalId($ClassExternalId): self
    {
        $this->container['ClassExternalId'] = $ClassExternalId;

        return $this;
    }

    /**
     * Gets ClassName
     *
     * @return string
     */
    public function getClassName()
    {
        return $this->container['ClassName'];
    }

    /**
     * Sets ClassName
     *
     * @param string $ClassName Contains the class name.
     *
     * @return $this
     */
    public function setClassName($ClassName): self
    {
        $this->container['ClassName'] = $ClassName;

        return $this;
    }

    /**
     * Gets ClassStartTime
     *
     * @return \DateTime
     */
    public function getClassStartTime()
    {
        return $this->container['ClassStartTime'];
    }

    /**
     * Sets ClassStartTime
     *
     * @param \DateTime $ClassStartTime Class start time.
     *
     * @return $this
     */
    public function setClassStartTime($ClassStartTime): self
    {
        $this->container['ClassStartTime'] = $ClassStartTime;

        return $this;
    }

    /**
     * Gets ClassEndTime
     *
     * @return \DateTime
     */
    public function getClassEndTime()
    {
        return $this->container['ClassEndTime'];
    }

    /**
     * Sets ClassEndTime
     *
     * @param \DateTime $ClassEndTime Class end time.
     *
     * @return $this
     */
    public function setClassEndTime($ClassEndTime): self
    {
        $this->container['ClassEndTime'] = $ClassEndTime;

        return $this;
    }

    /**
     * Gets ClassMaximumCapacity
     *
     * @return int
     */
    public function getClassMaximumCapacity()
    {
        return $this->container['ClassMaximumCapacity'];
    }

    /**
     * Sets ClassMaximumCapacity
     *
     * @param int $ClassMaximumCapacity Contains information about the Class maximum capacity.
     *
     * @return $this
     */
    public function setClassMaximumCapacity($ClassMaximumCapacity): self
    {
        $this->container['ClassMaximumCapacity'] = $ClassMaximumCapacity;

        return $this;
    }

    /**
     * Gets RoomId
     *
     * @return string
     */
    public function getRoomId()
    {
        return $this->container['RoomId'];
    }

    /**
     * Sets RoomId
     *
     * @param string $RoomId The unique Room ID.
     *
     * @return $this
     */
    public function setRoomId($RoomId): self
    {
        $this->container['RoomId'] = $RoomId;

        return $this;
    }

    /**
     * Gets Spots
     *
     * @return \Nlocascio\Mindbody\Model\PickASpotSpot
     */
    public function getSpots()
    {
        return $this->container['Spots'];
    }

    /**
     * Sets Spots
     *
     * @param \Nlocascio\Mindbody\Model\PickASpotSpot $Spots Contains information about the spot detail.
     *
     * @return $this
     */
    public function setSpots($Spots): self
    {
        $this->container['Spots'] = $Spots;

        return $this;
    }

    /**
     * Gets Reservations
     *
     * @return \Nlocascio\Mindbody\Model\PickASpotReservation[]
     */
    public function getReservations()
    {
        return $this->container['Reservations'];
    }

    /**
     * Sets Reservations
     *
     * @param \Nlocascio\Mindbody\Model\PickASpotReservation[] $Reservations Contains information about the reservation collection.
     *
     * @return $this
     */
    public function setReservations($Reservations): self
    {
        $this->container['Reservations'] = $Reservations;

        return $this;
    }
    
}


