<?php
/**
 * PickASpotResponseDetails
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.50
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Nlocascio\Mindbody\Model;

/**
 * PickASpotResponseDetails Class Doc Comment
 *
 * @category Class
 * @description Contains information about the response message detail.
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 * @property string $Status Contains information about the response status.
 * @property string $TransactionId The unique transaction ID.
 * @property string $Message Contains information about the response message detail.
 *
 */
class PickASpotResponseDetails extends BaseModel
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'PickASpot.ResponseDetails';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'Status' => 'string',
        'TransactionId' => 'string',
        'Message' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static $swaggerFormats = [
        'Status' => null,
        'TransactionId' => null,
        'Message' => null
    ];


    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'Status' => 'Status',
        'TransactionId' => 'TransactionId',
        'Message' => 'Message'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'Status' => 'setStatus',
        'TransactionId' => 'setTransactionId',
        'Message' => 'setMessage'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'Status' => 'getStatus',
        'TransactionId' => 'getTransactionId',
        'Message' => 'getMessage'
    ];


    

    

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['Status'] = isset($data['Status']) ? $data['Status'] : null;
        $this->container['TransactionId'] = isset($data['TransactionId']) ? $data['TransactionId'] : null;
        $this->container['Message'] = isset($data['Message']) ? $data['Message'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = parent::listInvalidProperties();

        return $invalidProperties;
    }


    /**
     * Gets Status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['Status'];
    }

    /**
     * Sets Status
     *
     * @param string $Status Contains information about the response status.
     *
     * @return $this
     */
    public function setStatus($Status): self
    {
        $this->container['Status'] = $Status;

        return $this;
    }

    /**
     * Gets TransactionId
     *
     * @return string
     */
    public function getTransactionId()
    {
        return $this->container['TransactionId'];
    }

    /**
     * Sets TransactionId
     *
     * @param string $TransactionId The unique transaction ID.
     *
     * @return $this
     */
    public function setTransactionId($TransactionId): self
    {
        $this->container['TransactionId'] = $TransactionId;

        return $this;
    }

    /**
     * Gets Message
     *
     * @return string
     */
    public function getMessage()
    {
        return $this->container['Message'];
    }

    /**
     * Sets Message
     *
     * @param string $Message Contains information about the response message detail.
     *
     * @return $this
     */
    public function setMessage($Message): self
    {
        $this->container['Message'] = $Message;

        return $this;
    }
    
}


