<?php
/**
 * Program
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Nlocascio\Mindbody\Model;

/**
 * Program Class Doc Comment
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 * @property int $CancelOffset CancelOffset
 * @property int $Id Id
 * @property string $Name Name
 * @property string $ScheduleType ScheduleType
 * @property string $ContentFormat ContentFormat
 * @property bool $OnlineBookingDisabled OnlineBookingDisabled
 * @property int $ScheduleOffset ScheduleOffset
 * @property int $ScheduleOffsetEnd ScheduleOffsetEnd
 * @property \Nlocascio\Mindbody\Model\PricingRelationships $PricingRelationships PricingRelationships
 *
 */
class Program extends BaseModel implements ModelWithIntId
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $swaggerModelName = 'Program';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static array $swaggerTypes = [
        'CancelOffset' => 'int',
        'Id' => 'int',
        'Name' => 'string',
        'ScheduleType' => 'string',
        'ContentFormat' => 'string',
        'OnlineBookingDisabled' => 'bool',
        'ScheduleOffset' => 'int',
        'ScheduleOffsetEnd' => 'int',
        'PricingRelationships' => '\Nlocascio\Mindbody\Model\PricingRelationships'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $swaggerFormats = [
        'CancelOffset' => 'int32',
        'Id' => 'int32',
        'Name' => null,
        'ScheduleType' => null,
        'ContentFormat' => null,
        'OnlineBookingDisabled' => null,
        'ScheduleOffset' => 'int32',
        'ScheduleOffsetEnd' => 'int32',
        'PricingRelationships' => null
    ];


    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static array $attributeMap = [
        'CancelOffset' => 'CancelOffset',
        'Id' => 'Id',
        'Name' => 'Name',
        'ScheduleType' => 'ScheduleType',
        'ContentFormat' => 'ContentFormat',
        'OnlineBookingDisabled' => 'OnlineBookingDisabled',
        'ScheduleOffset' => 'ScheduleOffset',
        'ScheduleOffsetEnd' => 'ScheduleOffsetEnd',
        'PricingRelationships' => 'PricingRelationships'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static array $setters = [
        'CancelOffset' => 'setCancelOffset',
        'Id' => 'setId',
        'Name' => 'setName',
        'ScheduleType' => 'setScheduleType',
        'ContentFormat' => 'setContentFormat',
        'OnlineBookingDisabled' => 'setOnlineBookingDisabled',
        'ScheduleOffset' => 'setScheduleOffset',
        'ScheduleOffsetEnd' => 'setScheduleOffsetEnd',
        'PricingRelationships' => 'setPricingRelationships'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static array $getters = [
        'CancelOffset' => 'getCancelOffset',
        'Id' => 'getId',
        'Name' => 'getName',
        'ScheduleType' => 'getScheduleType',
        'ContentFormat' => 'getContentFormat',
        'OnlineBookingDisabled' => 'getOnlineBookingDisabled',
        'ScheduleOffset' => 'getScheduleOffset',
        'ScheduleOffsetEnd' => 'getScheduleOffsetEnd',
        'PricingRelationships' => 'getPricingRelationships'
    ];


    const SCHEDULE_TYPE_ALL = 'All';
    const SCHEDULE_TYPE__CLASS = 'Class';
    const SCHEDULE_TYPE_DROP_IN = 'DropIn';
    const SCHEDULE_TYPE_ENROLLMENT = 'Enrollment';
    const SCHEDULE_TYPE_APPOINTMENT = 'Appointment';
    const SCHEDULE_TYPE_RESOURCE = 'Resource';
    const SCHEDULE_TYPE_MEDIA = 'Media';
    const SCHEDULE_TYPE_ARRIVAL = 'Arrival';
    const CONTENT_FORMAT_IN_PERSON = 'InPerson';
    const CONTENT_FORMAT_MINDBODY = 'Mindbody';
    const CONTENT_FORMAT_OTHER = 'Other';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getScheduleTypeAllowableValues(): array
    {
        return [
            self::SCHEDULE_TYPE_ALL,
            self::SCHEDULE_TYPE__CLASS,
            self::SCHEDULE_TYPE_DROP_IN,
            self::SCHEDULE_TYPE_ENROLLMENT,
            self::SCHEDULE_TYPE_APPOINTMENT,
            self::SCHEDULE_TYPE_RESOURCE,
            self::SCHEDULE_TYPE_MEDIA,
            self::SCHEDULE_TYPE_ARRIVAL,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getContentFormatAllowableValues(): array
    {
        return [
            self::CONTENT_FORMAT_IN_PERSON,
            self::CONTENT_FORMAT_MINDBODY,
            self::CONTENT_FORMAT_OTHER,
        ];
    }
    

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->container['CancelOffset'] = isset($data['CancelOffset']) ? $data['CancelOffset'] : null;
        $this->container['Id'] = isset($data['Id']) ? $data['Id'] : null;
        $this->container['Name'] = isset($data['Name']) ? $data['Name'] : null;
        $this->container['ScheduleType'] = isset($data['ScheduleType']) ? $data['ScheduleType'] : null;
        $this->container['ContentFormat'] = isset($data['ContentFormat']) ? $data['ContentFormat'] : null;
        $this->container['OnlineBookingDisabled'] = isset($data['OnlineBookingDisabled']) ? $data['OnlineBookingDisabled'] : null;
        $this->container['ScheduleOffset'] = isset($data['ScheduleOffset']) ? $data['ScheduleOffset'] : null;
        $this->container['ScheduleOffsetEnd'] = isset($data['ScheduleOffsetEnd']) ? $data['ScheduleOffsetEnd'] : null;
        $this->container['PricingRelationships'] = isset($data['PricingRelationships']) ? $data['PricingRelationships'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = parent::listInvalidProperties();

        $allowedValues = $this->getScheduleTypeAllowableValues();
        if (!is_null($this->container['ScheduleType']) && !in_array($this->container['ScheduleType'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'ScheduleType', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getContentFormatAllowableValues();
        if (!is_null($this->container['ContentFormat']) && !in_array($this->container['ContentFormat'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'ContentFormat', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }


    /**
     * Gets CancelOffset
     *
     * @return int
     */
    public function getCancelOffset(): int
    {
        return $this->container['CancelOffset'];
    }

    /**
     * Sets CancelOffset
     *
     * @param int $CancelOffset CancelOffset
     *
     * @return $this
     */


    public function setCancelOffset(int $CancelOffset): static
    {
        $this->container['CancelOffset'] = $CancelOffset;

        return $this;
    }

    /**
     * Gets Id
     *
     * @return int
     */
    public function getId(): int
    {
        return $this->container['Id'];
    }

    /**
     * Sets Id
     *
     * @param int $Id Id
     *
     * @return $this
     */


    public function setId(int $Id): static
    {
        $this->container['Id'] = $Id;

        return $this;
    }

    /**
     * Gets Name
     *
     * @return string
     */
    public function getName(): string
    {
        return $this->container['Name'];
    }

    /**
     * Sets Name
     *
     * @param string $Name Name
     *
     * @return $this
     */


    public function setName(string $Name): static
    {
        $this->container['Name'] = $Name;

        return $this;
    }

    /**
     * Gets ScheduleType
     *
     * @return string
     */
    public function getScheduleType(): string
    {
        return $this->container['ScheduleType'];
    }

    /**
     * Sets ScheduleType
     *
     * @param string $ScheduleType ScheduleType
     *
     * @return $this
     */


    public function setScheduleType(string $ScheduleType): static
    {
        $allowedValues = $this->getScheduleTypeAllowableValues();
        if (!is_null($ScheduleType) && !in_array($ScheduleType, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'ScheduleType', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['ScheduleType'] = $ScheduleType;

        return $this;
    }

    /**
     * Gets ContentFormat
     *
     * @return string
     */
    public function getContentFormat(): string
    {
        return $this->container['ContentFormat'];
    }

    /**
     * Sets ContentFormat
     *
     * @param string $ContentFormat ContentFormat
     *
     * @return $this
     */


    public function setContentFormat(string $ContentFormat): static
    {
        $allowedValues = $this->getContentFormatAllowableValues();
        if (!is_null($ContentFormat) && !in_array($ContentFormat, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'ContentFormat', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['ContentFormat'] = $ContentFormat;

        return $this;
    }

    /**
     * Gets OnlineBookingDisabled
     *
     * @return bool
     */
    public function getOnlineBookingDisabled(): bool
    {
        return $this->container['OnlineBookingDisabled'];
    }

    /**
     * Sets OnlineBookingDisabled
     *
     * @param bool $OnlineBookingDisabled OnlineBookingDisabled
     *
     * @return $this
     */


    public function setOnlineBookingDisabled(bool $OnlineBookingDisabled): static
    {
        $this->container['OnlineBookingDisabled'] = $OnlineBookingDisabled;

        return $this;
    }

    /**
     * Gets ScheduleOffset
     *
     * @return int
     */
    public function getScheduleOffset(): int
    {
        return $this->container['ScheduleOffset'];
    }

    /**
     * Sets ScheduleOffset
     *
     * @param int $ScheduleOffset ScheduleOffset
     *
     * @return $this
     */


    public function setScheduleOffset(int $ScheduleOffset): static
    {
        $this->container['ScheduleOffset'] = $ScheduleOffset;

        return $this;
    }

    /**
     * Gets ScheduleOffsetEnd
     *
     * @return int
     */
    public function getScheduleOffsetEnd(): int
    {
        return $this->container['ScheduleOffsetEnd'];
    }

    /**
     * Sets ScheduleOffsetEnd
     *
     * @param int $ScheduleOffsetEnd ScheduleOffsetEnd
     *
     * @return $this
     */


    public function setScheduleOffsetEnd(int $ScheduleOffsetEnd): static
    {
        $this->container['ScheduleOffsetEnd'] = $ScheduleOffsetEnd;

        return $this;
    }

    /**
     * Gets PricingRelationships
     *
     * @return \Nlocascio\Mindbody\Model\PricingRelationships
     */
    public function getPricingRelationships(): \Nlocascio\Mindbody\Model\PricingRelationships
    {
        return $this->container['PricingRelationships'];
    }

    /**
     * Sets PricingRelationships
     *
     * @param \Nlocascio\Mindbody\Model\PricingRelationships $PricingRelationships PricingRelationships
     *
     * @return $this
     */


    public function setPricingRelationships(\Nlocascio\Mindbody\Model\PricingRelationships $PricingRelationships): static
    {
        $this->container['PricingRelationships'] = $PricingRelationships;

        return $this;
    }
    
}


