<?php
/**
 * PurchaseContractResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.23
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Nlocascio\Mindbody\Model;

/**
 * PurchaseContractResponse Class Doc Comment
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PurchaseContractResponse extends BaseModel
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'PurchaseContractResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'ClientId' => 'string',
        'LocationId' => 'int',
        'ContractId' => 'int',
        'ClientContractId' => 'int',
        'PaymentProcessingFailures' => '\Nlocascio\Mindbody\Model\PaymentProcessingFailure[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<int, string|null>
      */
    protected static $swaggerFormats = [
        'ClientId' => null,
        'LocationId' => 'int32',
        'ContractId' => 'int32',
        'ClientContractId' => 'int32',
        'PaymentProcessingFailures' => null
    ];


    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'ClientId' => 'ClientId',
        'LocationId' => 'LocationId',
        'ContractId' => 'ContractId',
        'ClientContractId' => 'ClientContractId',
        'PaymentProcessingFailures' => 'PaymentProcessingFailures'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'ClientId' => 'setClientId',
        'LocationId' => 'setLocationId',
        'ContractId' => 'setContractId',
        'ClientContractId' => 'setClientContractId',
        'PaymentProcessingFailures' => 'setPaymentProcessingFailures'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'ClientId' => 'getClientId',
        'LocationId' => 'getLocationId',
        'ContractId' => 'getContractId',
        'ClientContractId' => 'getClientContractId',
        'PaymentProcessingFailures' => 'getPaymentProcessingFailures'
    ];


    

    

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['ClientId'] = isset($data['ClientId']) ? $data['ClientId'] : null;
        $this->container['LocationId'] = isset($data['LocationId']) ? $data['LocationId'] : null;
        $this->container['ContractId'] = isset($data['ContractId']) ? $data['ContractId'] : null;
        $this->container['ClientContractId'] = isset($data['ClientContractId']) ? $data['ClientContractId'] : null;
        $this->container['PaymentProcessingFailures'] = isset($data['PaymentProcessingFailures']) ? $data['PaymentProcessingFailures'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = parent::listInvalidProperties();

        return $invalidProperties;
    }


    /**
     * Gets ClientId
     *
     * @return string
     */
    public function getClientId()
    {
        return $this->container['ClientId'];
    }

    /**
     * Sets ClientId
     *
     * @param string $ClientId The ID of the client who is purchasing the contract.
     *
     * @return $this
     */
    public function setClientId($ClientId): self
    {
        $this->container['ClientId'] = $ClientId;

        return $this;
    }

    /**
     * Gets LocationId
     *
     * @return int
     */
    public function getLocationId()
    {
        return $this->container['LocationId'];
    }

    /**
     * Sets LocationId
     *
     * @param int $LocationId The ID of the location where the contract is being purchased.
     *
     * @return $this
     */
    public function setLocationId($LocationId): self
    {
        $this->container['LocationId'] = $LocationId;

        return $this;
    }

    /**
     * Gets ContractId
     *
     * @return int
     */
    public function getContractId()
    {
        return $this->container['ContractId'];
    }

    /**
     * Sets ContractId
     *
     * @param int $ContractId The ID of the general contract being purchased.
     *
     * @return $this
     */
    public function setContractId($ContractId): self
    {
        $this->container['ContractId'] = $ContractId;

        return $this;
    }

    /**
     * Gets ClientContractId
     *
     * @return int
     */
    public function getClientContractId()
    {
        return $this->container['ClientContractId'];
    }

    /**
     * Sets ClientContractId
     *
     * @param int $ClientContractId The ID of the specific contract being purchased by this specific client, not to be confused with the `ContractId`, which refers to a general contract that the business offers.
     *
     * @return $this
     */
    public function setClientContractId($ClientContractId): self
    {
        $this->container['ClientContractId'] = $ClientContractId;

        return $this;
    }

    /**
     * Gets PaymentProcessingFailures
     *
     * @return \Nlocascio\Mindbody\Model\PaymentProcessingFailure[]
     */
    public function getPaymentProcessingFailures()
    {
        return $this->container['PaymentProcessingFailures'];
    }

    /**
     * Sets PaymentProcessingFailures
     *
     * @param \Nlocascio\Mindbody\Model\PaymentProcessingFailure[] $PaymentProcessingFailures Any cart processing failures, for example when SCA challenged, the cart is in PaymentAuthenticationRequired state and at least one of the failures listed will provide an authentication Url.
     *
     * @return $this
     */
    public function setPaymentProcessingFailures($PaymentProcessingFailures): self
    {
        $this->container['PaymentProcessingFailures'] = $PaymentProcessingFailures;

        return $this;
    }
    
}


