<?php
/**
 * PurchaseAccountCreditRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Nlocascio\Mindbody\Model;

/**
 * PurchaseAccountCreditRequest Class Doc Comment
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 * @property bool $Test When `true`, allows you to test the request without affecting the database.  When `false`, the request is carried out and the database is affected.
 * @property int $LocationId The ID of the location where the account credit is being sold.
 * @property string $ClientId The ID of the location where the account credit is being sold.
 * @property bool $SendEmailReceipt When `true`, indicates that a purchase receipt email should be sent to the purchasing client, if all settings are correctly configured.<br />  When `false`, no email is sent to the purchaser.
 * @property int $SalesRepId The ID of the staff member to be marked as the sales rep for this account credit sale.
 * @property bool $ConsumerPresent When `true`, indicates that the consumer is present or otherwise able to successfully negotiate an SCA challenge.   It is not a good idea to have this always be false as that could very likely lead to a bank declining all transactions for the merchant. Defaults to false.  Default: **false**
 * @property string $PaymentAuthenticationCallbackUrl The URL consumer is redirected to if the bank requests SCA. This field is only needed if ConsumerPresent is true.
 * @property \Nlocascio\Mindbody\Model\CheckoutPaymentInfo $PaymentInfo Contains information about the payment.
 *
 */
class PurchaseAccountCreditRequest extends BaseModel
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $swaggerModelName = 'PurchaseAccountCreditRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static array $swaggerTypes = [
        'Test' => 'bool',
        'LocationId' => 'int',
        'ClientId' => 'string',
        'SendEmailReceipt' => 'bool',
        'SalesRepId' => 'int',
        'ConsumerPresent' => 'bool',
        'PaymentAuthenticationCallbackUrl' => 'string',
        'PaymentInfo' => '\Nlocascio\Mindbody\Model\CheckoutPaymentInfo'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $swaggerFormats = [
        'Test' => null,
        'LocationId' => 'int32',
        'ClientId' => null,
        'SendEmailReceipt' => null,
        'SalesRepId' => 'int64',
        'ConsumerPresent' => null,
        'PaymentAuthenticationCallbackUrl' => null,
        'PaymentInfo' => null
    ];


    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static array $attributeMap = [
        'Test' => 'Test',
        'LocationId' => 'LocationId',
        'ClientId' => 'ClientId',
        'SendEmailReceipt' => 'SendEmailReceipt',
        'SalesRepId' => 'SalesRepId',
        'ConsumerPresent' => 'ConsumerPresent',
        'PaymentAuthenticationCallbackUrl' => 'PaymentAuthenticationCallbackUrl',
        'PaymentInfo' => 'PaymentInfo'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static array $setters = [
        'Test' => 'setTest',
        'LocationId' => 'setLocationId',
        'ClientId' => 'setClientId',
        'SendEmailReceipt' => 'setSendEmailReceipt',
        'SalesRepId' => 'setSalesRepId',
        'ConsumerPresent' => 'setConsumerPresent',
        'PaymentAuthenticationCallbackUrl' => 'setPaymentAuthenticationCallbackUrl',
        'PaymentInfo' => 'setPaymentInfo'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static array $getters = [
        'Test' => 'getTest',
        'LocationId' => 'getLocationId',
        'ClientId' => 'getClientId',
        'SendEmailReceipt' => 'getSendEmailReceipt',
        'SalesRepId' => 'getSalesRepId',
        'ConsumerPresent' => 'getConsumerPresent',
        'PaymentAuthenticationCallbackUrl' => 'getPaymentAuthenticationCallbackUrl',
        'PaymentInfo' => 'getPaymentInfo'
    ];


    

    

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->container['Test'] = isset($data['Test']) ? $data['Test'] : null;
        $this->container['LocationId'] = isset($data['LocationId']) ? $data['LocationId'] : null;
        $this->container['ClientId'] = isset($data['ClientId']) ? $data['ClientId'] : null;
        $this->container['SendEmailReceipt'] = isset($data['SendEmailReceipt']) ? $data['SendEmailReceipt'] : null;
        $this->container['SalesRepId'] = isset($data['SalesRepId']) ? $data['SalesRepId'] : null;
        $this->container['ConsumerPresent'] = isset($data['ConsumerPresent']) ? $data['ConsumerPresent'] : null;
        $this->container['PaymentAuthenticationCallbackUrl'] = isset($data['PaymentAuthenticationCallbackUrl']) ? $data['PaymentAuthenticationCallbackUrl'] : null;
        $this->container['PaymentInfo'] = isset($data['PaymentInfo']) ? $data['PaymentInfo'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = parent::listInvalidProperties();

        if ($this->container['ClientId'] === null) {
            $invalidProperties[] = "'ClientId' can't be null";
        }
        return $invalidProperties;
    }


    /**
     * Gets Test
     *
     * @return bool
     */
    public function getTest(): bool
    {
        return $this->container['Test'];
    }

    /**
     * Sets Test
     *
     * @param bool $Test When `true`, allows you to test the request without affecting the database.  When `false`, the request is carried out and the database is affected.
     *
     * @return $this
     */


    public function setTest(bool $Test): static
    {
        $this->container['Test'] = $Test;

        return $this;
    }

    /**
     * Gets LocationId
     *
     * @return int
     */
    public function getLocationId(): int
    {
        return $this->container['LocationId'];
    }

    /**
     * Sets LocationId
     *
     * @param int $LocationId The ID of the location where the account credit is being sold.
     *
     * @return $this
     */


    public function setLocationId(int $LocationId): static
    {
        $this->container['LocationId'] = $LocationId;

        return $this;
    }

    /**
     * Gets ClientId
     *
     * @return string
     */
    public function getClientId(): string
    {
        return $this->container['ClientId'];
    }

    /**
     * Sets ClientId
     *
     * @param string $ClientId The ID of the location where the account credit is being sold.
     *
     * @return $this
     */


    public function setClientId(string $ClientId): static
    {
        $this->container['ClientId'] = $ClientId;

        return $this;
    }

    /**
     * Gets SendEmailReceipt
     *
     * @return bool
     */
    public function getSendEmailReceipt(): bool
    {
        return $this->container['SendEmailReceipt'];
    }

    /**
     * Sets SendEmailReceipt
     *
     * @param bool $SendEmailReceipt When `true`, indicates that a purchase receipt email should be sent to the purchasing client, if all settings are correctly configured.<br />  When `false`, no email is sent to the purchaser.
     *
     * @return $this
     */


    public function setSendEmailReceipt(bool $SendEmailReceipt): static
    {
        $this->container['SendEmailReceipt'] = $SendEmailReceipt;

        return $this;
    }

    /**
     * Gets SalesRepId
     *
     * @return int
     */
    public function getSalesRepId(): int
    {
        return $this->container['SalesRepId'];
    }

    /**
     * Sets SalesRepId
     *
     * @param int $SalesRepId The ID of the staff member to be marked as the sales rep for this account credit sale.
     *
     * @return $this
     */


    public function setSalesRepId(int $SalesRepId): static
    {
        $this->container['SalesRepId'] = $SalesRepId;

        return $this;
    }

    /**
     * Gets ConsumerPresent
     *
     * @return bool
     */
    public function getConsumerPresent(): bool
    {
        return $this->container['ConsumerPresent'];
    }

    /**
     * Sets ConsumerPresent
     *
     * @param bool $ConsumerPresent When `true`, indicates that the consumer is present or otherwise able to successfully negotiate an SCA challenge.   It is not a good idea to have this always be false as that could very likely lead to a bank declining all transactions for the merchant. Defaults to false.  Default: **false**
     *
     * @return $this
     */


    public function setConsumerPresent(bool $ConsumerPresent): static
    {
        $this->container['ConsumerPresent'] = $ConsumerPresent;

        return $this;
    }

    /**
     * Gets PaymentAuthenticationCallbackUrl
     *
     * @return string
     */
    public function getPaymentAuthenticationCallbackUrl(): string
    {
        return $this->container['PaymentAuthenticationCallbackUrl'];
    }

    /**
     * Sets PaymentAuthenticationCallbackUrl
     *
     * @param string $PaymentAuthenticationCallbackUrl The URL consumer is redirected to if the bank requests SCA. This field is only needed if ConsumerPresent is true.
     *
     * @return $this
     */


    public function setPaymentAuthenticationCallbackUrl(string $PaymentAuthenticationCallbackUrl): static
    {
        $this->container['PaymentAuthenticationCallbackUrl'] = $PaymentAuthenticationCallbackUrl;

        return $this;
    }

    /**
     * Gets PaymentInfo
     *
     * @return \Nlocascio\Mindbody\Model\CheckoutPaymentInfo
     */
    public function getPaymentInfo(): \Nlocascio\Mindbody\Model\CheckoutPaymentInfo
    {
        return $this->container['PaymentInfo'];
    }

    /**
     * Sets PaymentInfo
     *
     * @param \Nlocascio\Mindbody\Model\CheckoutPaymentInfo $PaymentInfo Contains information about the payment.
     *
     * @return $this
     */


    public function setPaymentInfo(\Nlocascio\Mindbody\Model\CheckoutPaymentInfo $PaymentInfo): static
    {
        $this->container['PaymentInfo'] = $PaymentInfo;

        return $this;
    }
    
}


