<?php
/**
 * ResourceAvailability
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.50
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Nlocascio\Mindbody\Model;

/**
 * ResourceAvailability Class Doc Comment
 *
 * @category Class
 * @description An availability of a resource
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 * @property int $ResourceId Id
 * @property \DateTime $StartDateTime Starts
 * @property \DateTime $EndDateTime Ends
 * @property int[] $SessionTypeIds List of SessionTypeIds that this availability is restricted to. If empty, no restrictions.
 * @property int[] $ProgramIds List of ProgramIds that this availability is restricted to. If empty, no restrictions.
 *
 */
class ResourceAvailability extends BaseModel
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ResourceAvailability';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'ResourceId' => 'int',
        'StartDateTime' => '\DateTime',
        'EndDateTime' => '\DateTime',
        'SessionTypeIds' => 'int[]',
        'ProgramIds' => 'int[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static $swaggerFormats = [
        'ResourceId' => 'int32',
        'StartDateTime' => 'date-time',
        'EndDateTime' => 'date-time',
        'SessionTypeIds' => 'int32',
        'ProgramIds' => 'int32'
    ];


    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'ResourceId' => 'ResourceId',
        'StartDateTime' => 'StartDateTime',
        'EndDateTime' => 'EndDateTime',
        'SessionTypeIds' => 'SessionTypeIds',
        'ProgramIds' => 'ProgramIds'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'ResourceId' => 'setResourceId',
        'StartDateTime' => 'setStartDateTime',
        'EndDateTime' => 'setEndDateTime',
        'SessionTypeIds' => 'setSessionTypeIds',
        'ProgramIds' => 'setProgramIds'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'ResourceId' => 'getResourceId',
        'StartDateTime' => 'getStartDateTime',
        'EndDateTime' => 'getEndDateTime',
        'SessionTypeIds' => 'getSessionTypeIds',
        'ProgramIds' => 'getProgramIds'
    ];


    

    

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['ResourceId'] = isset($data['ResourceId']) ? $data['ResourceId'] : null;
        $this->container['StartDateTime'] = isset($data['StartDateTime']) ? $data['StartDateTime'] : null;
        $this->container['EndDateTime'] = isset($data['EndDateTime']) ? $data['EndDateTime'] : null;
        $this->container['SessionTypeIds'] = isset($data['SessionTypeIds']) ? $data['SessionTypeIds'] : null;
        $this->container['ProgramIds'] = isset($data['ProgramIds']) ? $data['ProgramIds'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = parent::listInvalidProperties();

        return $invalidProperties;
    }


    /**
     * Gets ResourceId
     *
     * @return int
     */
    public function getResourceId()
    {
        return $this->container['ResourceId'];
    }

    /**
     * Sets ResourceId
     *
     * @param int $ResourceId Id
     *
     * @return $this
     */
    public function setResourceId($ResourceId): self
    {
        $this->container['ResourceId'] = $ResourceId;

        return $this;
    }

    /**
     * Gets StartDateTime
     *
     * @return \DateTime
     */
    public function getStartDateTime()
    {
        return $this->container['StartDateTime'];
    }

    /**
     * Sets StartDateTime
     *
     * @param \DateTime $StartDateTime Starts
     *
     * @return $this
     */
    public function setStartDateTime($StartDateTime): self
    {
        $this->container['StartDateTime'] = $StartDateTime;

        return $this;
    }

    /**
     * Gets EndDateTime
     *
     * @return \DateTime
     */
    public function getEndDateTime()
    {
        return $this->container['EndDateTime'];
    }

    /**
     * Sets EndDateTime
     *
     * @param \DateTime $EndDateTime Ends
     *
     * @return $this
     */
    public function setEndDateTime($EndDateTime): self
    {
        $this->container['EndDateTime'] = $EndDateTime;

        return $this;
    }

    /**
     * Gets SessionTypeIds
     *
     * @return int[]
     */
    public function getSessionTypeIds()
    {
        return $this->container['SessionTypeIds'];
    }

    /**
     * Sets SessionTypeIds
     *
     * @param int[] $SessionTypeIds List of SessionTypeIds that this availability is restricted to. If empty, no restrictions.
     *
     * @return $this
     */
    public function setSessionTypeIds($SessionTypeIds): self
    {
        $this->container['SessionTypeIds'] = $SessionTypeIds;

        return $this;
    }

    /**
     * Gets ProgramIds
     *
     * @return int[]
     */
    public function getProgramIds()
    {
        return $this->container['ProgramIds'];
    }

    /**
     * Sets ProgramIds
     *
     * @param int[] $ProgramIds List of ProgramIds that this availability is restricted to. If empty, no restrictions.
     *
     * @return $this
     */
    public function setProgramIds($ProgramIds): self
    {
        $this->container['ProgramIds'] = $ProgramIds;

        return $this;
    }
    
}


