<?php
/**
 * SalesRep
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.28
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Nlocascio\Mindbody\Model;

/**
 * SalesRep Class Doc Comment
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 * @property string $FirstName The first name of the sales representative.
 * @property int $Id The staff ID of the sales representative.
 * @property string $LastName The last name of the sales representative.
 * @property int $SalesRepNumber This value is the number that identifies the type of sales representative assigned to this client. One to six types of sales representatives can be assigned to a client at any given time, depending on site settings.
 * @property int[] $SalesRepNumbers A list of the different types of sales representative functions assigned to this staff member.
 *
 */
class SalesRep extends BaseModel implements ModelWithId
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'SalesRep';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'FirstName' => 'string',
        'Id' => 'int',
        'LastName' => 'string',
        'SalesRepNumber' => 'int',
        'SalesRepNumbers' => 'int[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static $swaggerFormats = [
        'FirstName' => null,
        'Id' => 'int64',
        'LastName' => null,
        'SalesRepNumber' => 'int32',
        'SalesRepNumbers' => 'int32'
    ];


    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'FirstName' => 'FirstName',
        'Id' => 'Id',
        'LastName' => 'LastName',
        'SalesRepNumber' => 'SalesRepNumber',
        'SalesRepNumbers' => 'SalesRepNumbers'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'FirstName' => 'setFirstName',
        'Id' => 'setId',
        'LastName' => 'setLastName',
        'SalesRepNumber' => 'setSalesRepNumber',
        'SalesRepNumbers' => 'setSalesRepNumbers'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'FirstName' => 'getFirstName',
        'Id' => 'getId',
        'LastName' => 'getLastName',
        'SalesRepNumber' => 'getSalesRepNumber',
        'SalesRepNumbers' => 'getSalesRepNumbers'
    ];


    

    

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['FirstName'] = isset($data['FirstName']) ? $data['FirstName'] : null;
        $this->container['Id'] = isset($data['Id']) ? $data['Id'] : null;
        $this->container['LastName'] = isset($data['LastName']) ? $data['LastName'] : null;
        $this->container['SalesRepNumber'] = isset($data['SalesRepNumber']) ? $data['SalesRepNumber'] : null;
        $this->container['SalesRepNumbers'] = isset($data['SalesRepNumbers']) ? $data['SalesRepNumbers'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = parent::listInvalidProperties();

        return $invalidProperties;
    }


    /**
     * Gets FirstName
     *
     * @return string
     */
    public function getFirstName()
    {
        return $this->container['FirstName'];
    }

    /**
     * Sets FirstName
     *
     * @param string $FirstName The first name of the sales representative.
     *
     * @return $this
     */
    public function setFirstName($FirstName): self
    {
        $this->container['FirstName'] = $FirstName;

        return $this;
    }

    /**
     * Gets Id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['Id'];
    }

    /**
     * Sets Id
     *
     * @param int $Id The staff ID of the sales representative.
     *
     * @return $this
     */
    public function setId($Id): self
    {
        $this->container['Id'] = $Id;

        return $this;
    }

    /**
     * Gets LastName
     *
     * @return string
     */
    public function getLastName()
    {
        return $this->container['LastName'];
    }

    /**
     * Sets LastName
     *
     * @param string $LastName The last name of the sales representative.
     *
     * @return $this
     */
    public function setLastName($LastName): self
    {
        $this->container['LastName'] = $LastName;

        return $this;
    }

    /**
     * Gets SalesRepNumber
     *
     * @return int
     */
    public function getSalesRepNumber()
    {
        return $this->container['SalesRepNumber'];
    }

    /**
     * Sets SalesRepNumber
     *
     * @param int $SalesRepNumber This value is the number that identifies the type of sales representative assigned to this client. One to six types of sales representatives can be assigned to a client at any given time, depending on site settings.
     *
     * @return $this
     */
    public function setSalesRepNumber($SalesRepNumber): self
    {
        $this->container['SalesRepNumber'] = $SalesRepNumber;

        return $this;
    }

    /**
     * Gets SalesRepNumbers
     *
     * @return int[]
     */
    public function getSalesRepNumbers()
    {
        return $this->container['SalesRepNumbers'];
    }

    /**
     * Sets SalesRepNumbers
     *
     * @param int[] $SalesRepNumbers A list of the different types of sales representative functions assigned to this staff member.
     *
     * @return $this
     */
    public function setSalesRepNumbers($SalesRepNumbers): self
    {
        $this->container['SalesRepNumbers'] = $SalesRepNumbers;

        return $this;
    }
    
}


