<?php
/**
 * Semester
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.40-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Nlocascio\Mindbody\Model;

/**
 * Semester Class Doc Comment
 *
 * @category Class
 * @description Semesters help you quickly classify enrollments.
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 * @property int $Id This semester’s unique ID.
 * @property string $Name Name of the semester.
 * @property string $Description The description of the semester.
 * @property \DateTime $StartDate Start date of the semester.
 * @property \DateTime $EndDate End date of the semester.
 * @property double $MultiRegistrationDiscount Discount for multiple registration in the semester.
 * @property \DateTime $MultiRegistrationDeadline Registration deadline of the semester.
 * @property bool $Active When `true`, indicates that the semester is active.
 *
 */
class Semester extends BaseModel implements ModelWithId
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Semester';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'Id' => 'int',
        'Name' => 'string',
        'Description' => 'string',
        'StartDate' => '\DateTime',
        'EndDate' => '\DateTime',
        'MultiRegistrationDiscount' => 'double',
        'MultiRegistrationDeadline' => '\DateTime',
        'Active' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static $swaggerFormats = [
        'Id' => 'int32',
        'Name' => null,
        'Description' => null,
        'StartDate' => 'date-time',
        'EndDate' => 'date-time',
        'MultiRegistrationDiscount' => 'double',
        'MultiRegistrationDeadline' => 'date-time',
        'Active' => null
    ];


    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'Id' => 'Id',
        'Name' => 'Name',
        'Description' => 'Description',
        'StartDate' => 'StartDate',
        'EndDate' => 'EndDate',
        'MultiRegistrationDiscount' => 'MultiRegistrationDiscount',
        'MultiRegistrationDeadline' => 'MultiRegistrationDeadline',
        'Active' => 'Active'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'Id' => 'setId',
        'Name' => 'setName',
        'Description' => 'setDescription',
        'StartDate' => 'setStartDate',
        'EndDate' => 'setEndDate',
        'MultiRegistrationDiscount' => 'setMultiRegistrationDiscount',
        'MultiRegistrationDeadline' => 'setMultiRegistrationDeadline',
        'Active' => 'setActive'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'Id' => 'getId',
        'Name' => 'getName',
        'Description' => 'getDescription',
        'StartDate' => 'getStartDate',
        'EndDate' => 'getEndDate',
        'MultiRegistrationDiscount' => 'getMultiRegistrationDiscount',
        'MultiRegistrationDeadline' => 'getMultiRegistrationDeadline',
        'Active' => 'getActive'
    ];


    

    

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['Id'] = isset($data['Id']) ? $data['Id'] : null;
        $this->container['Name'] = isset($data['Name']) ? $data['Name'] : null;
        $this->container['Description'] = isset($data['Description']) ? $data['Description'] : null;
        $this->container['StartDate'] = isset($data['StartDate']) ? $data['StartDate'] : null;
        $this->container['EndDate'] = isset($data['EndDate']) ? $data['EndDate'] : null;
        $this->container['MultiRegistrationDiscount'] = isset($data['MultiRegistrationDiscount']) ? $data['MultiRegistrationDiscount'] : null;
        $this->container['MultiRegistrationDeadline'] = isset($data['MultiRegistrationDeadline']) ? $data['MultiRegistrationDeadline'] : null;
        $this->container['Active'] = isset($data['Active']) ? $data['Active'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = parent::listInvalidProperties();

        return $invalidProperties;
    }


    /**
     * Gets Id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['Id'];
    }

    /**
     * Sets Id
     *
     * @param int $Id This semester’s unique ID.
     *
     * @return $this
     */
    public function setId($Id): self
    {
        $this->container['Id'] = $Id;

        return $this;
    }

    /**
     * Gets Name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['Name'];
    }

    /**
     * Sets Name
     *
     * @param string $Name Name of the semester.
     *
     * @return $this
     */
    public function setName($Name): self
    {
        $this->container['Name'] = $Name;

        return $this;
    }

    /**
     * Gets Description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->container['Description'];
    }

    /**
     * Sets Description
     *
     * @param string $Description The description of the semester.
     *
     * @return $this
     */
    public function setDescription($Description): self
    {
        $this->container['Description'] = $Description;

        return $this;
    }

    /**
     * Gets StartDate
     *
     * @return \DateTime
     */
    public function getStartDate()
    {
        return $this->container['StartDate'];
    }

    /**
     * Sets StartDate
     *
     * @param \DateTime $StartDate Start date of the semester.
     *
     * @return $this
     */
    public function setStartDate($StartDate): self
    {
        $this->container['StartDate'] = $StartDate;

        return $this;
    }

    /**
     * Gets EndDate
     *
     * @return \DateTime
     */
    public function getEndDate()
    {
        return $this->container['EndDate'];
    }

    /**
     * Sets EndDate
     *
     * @param \DateTime $EndDate End date of the semester.
     *
     * @return $this
     */
    public function setEndDate($EndDate): self
    {
        $this->container['EndDate'] = $EndDate;

        return $this;
    }

    /**
     * Gets MultiRegistrationDiscount
     *
     * @return double
     */
    public function getMultiRegistrationDiscount()
    {
        return $this->container['MultiRegistrationDiscount'];
    }

    /**
     * Sets MultiRegistrationDiscount
     *
     * @param double $MultiRegistrationDiscount Discount for multiple registration in the semester.
     *
     * @return $this
     */
    public function setMultiRegistrationDiscount($MultiRegistrationDiscount): self
    {
        $this->container['MultiRegistrationDiscount'] = $MultiRegistrationDiscount;

        return $this;
    }

    /**
     * Gets MultiRegistrationDeadline
     *
     * @return \DateTime
     */
    public function getMultiRegistrationDeadline()
    {
        return $this->container['MultiRegistrationDeadline'];
    }

    /**
     * Sets MultiRegistrationDeadline
     *
     * @param \DateTime $MultiRegistrationDeadline Registration deadline of the semester.
     *
     * @return $this
     */
    public function setMultiRegistrationDeadline($MultiRegistrationDeadline): self
    {
        $this->container['MultiRegistrationDeadline'] = $MultiRegistrationDeadline;

        return $this;
    }

    /**
     * Gets Active
     *
     * @return bool
     */
    public function getActive()
    {
        return $this->container['Active'];
    }

    /**
     * Sets Active
     *
     * @param bool $Active When `true`, indicates that the semester is active.
     *
     * @return $this
     */
    public function setActive($Active): self
    {
        $this->container['Active'] = $Active;

        return $this;
    }
    
}


