<?php
/**
 * SessionType
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Nlocascio\Mindbody\Model;

/**
 * SessionType Class Doc Comment
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 * @property string $Type Type
 * @property int $DefaultTimeLength DefaultTimeLength
 * @property int $StaffTimeLength StaffTimeLength
 * @property int $ProgramId ProgramId
 * @property int $NumDeducted NumDeducted
 * @property int $Id Id
 * @property string $Name Name
 * @property bool $Active Active
 * @property int $Capacity Capacity
 * @property bool $ResourceRequired ResourceRequired
 * @property \Nlocascio\Mindbody\Model\ServiceTag $Category Category
 * @property \Nlocascio\Mindbody\Model\ServiceTag $Subcategory Subcategory
 * @property string $OnlineDescription OnlineDescription
 * @property bool $AvailableForAddOn AvailableForAddOn
 *
 */
class SessionType extends BaseModel implements ModelWithIntId
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $swaggerModelName = 'SessionType';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static array $swaggerTypes = [
        'Type' => 'string',
        'DefaultTimeLength' => 'int',
        'StaffTimeLength' => 'int',
        'ProgramId' => 'int',
        'NumDeducted' => 'int',
        'Id' => 'int',
        'Name' => 'string',
        'Active' => 'bool',
        'Capacity' => 'int',
        'ResourceRequired' => 'bool',
        'Category' => '\Nlocascio\Mindbody\Model\ServiceTag',
        'Subcategory' => '\Nlocascio\Mindbody\Model\ServiceTag',
        'OnlineDescription' => 'string',
        'AvailableForAddOn' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $swaggerFormats = [
        'Type' => null,
        'DefaultTimeLength' => 'int32',
        'StaffTimeLength' => 'int32',
        'ProgramId' => 'int32',
        'NumDeducted' => 'int32',
        'Id' => 'int32',
        'Name' => null,
        'Active' => null,
        'Capacity' => 'int32',
        'ResourceRequired' => null,
        'Category' => null,
        'Subcategory' => null,
        'OnlineDescription' => null,
        'AvailableForAddOn' => null
    ];


    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static array $attributeMap = [
        'Type' => 'Type',
        'DefaultTimeLength' => 'DefaultTimeLength',
        'StaffTimeLength' => 'StaffTimeLength',
        'ProgramId' => 'ProgramId',
        'NumDeducted' => 'NumDeducted',
        'Id' => 'Id',
        'Name' => 'Name',
        'Active' => 'Active',
        'Capacity' => 'Capacity',
        'ResourceRequired' => 'ResourceRequired',
        'Category' => 'Category',
        'Subcategory' => 'Subcategory',
        'OnlineDescription' => 'OnlineDescription',
        'AvailableForAddOn' => 'AvailableForAddOn'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static array $setters = [
        'Type' => 'setType',
        'DefaultTimeLength' => 'setDefaultTimeLength',
        'StaffTimeLength' => 'setStaffTimeLength',
        'ProgramId' => 'setProgramId',
        'NumDeducted' => 'setNumDeducted',
        'Id' => 'setId',
        'Name' => 'setName',
        'Active' => 'setActive',
        'Capacity' => 'setCapacity',
        'ResourceRequired' => 'setResourceRequired',
        'Category' => 'setCategory',
        'Subcategory' => 'setSubcategory',
        'OnlineDescription' => 'setOnlineDescription',
        'AvailableForAddOn' => 'setAvailableForAddOn'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static array $getters = [
        'Type' => 'getType',
        'DefaultTimeLength' => 'getDefaultTimeLength',
        'StaffTimeLength' => 'getStaffTimeLength',
        'ProgramId' => 'getProgramId',
        'NumDeducted' => 'getNumDeducted',
        'Id' => 'getId',
        'Name' => 'getName',
        'Active' => 'getActive',
        'Capacity' => 'getCapacity',
        'ResourceRequired' => 'getResourceRequired',
        'Category' => 'getCategory',
        'Subcategory' => 'getSubcategory',
        'OnlineDescription' => 'getOnlineDescription',
        'AvailableForAddOn' => 'getAvailableForAddOn'
    ];


    const TYPE_ALL = 'All';
    const TYPE_DROP_IN = 'DropIn';
    const TYPE_ENROLLMENT = 'Enrollment';
    const TYPE_APPOINTMENT = 'Appointment';
    const TYPE_RESOURCE = 'Resource';
    const TYPE_MEDIA = 'Media';
    const TYPE_ARRIVAL = 'Arrival';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTypeAllowableValues(): array
    {
        return [
            self::TYPE_ALL,
            self::TYPE_DROP_IN,
            self::TYPE_ENROLLMENT,
            self::TYPE_APPOINTMENT,
            self::TYPE_RESOURCE,
            self::TYPE_MEDIA,
            self::TYPE_ARRIVAL,
        ];
    }
    

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->container['Type'] = isset($data['Type']) ? $data['Type'] : null;
        $this->container['DefaultTimeLength'] = isset($data['DefaultTimeLength']) ? $data['DefaultTimeLength'] : null;
        $this->container['StaffTimeLength'] = isset($data['StaffTimeLength']) ? $data['StaffTimeLength'] : null;
        $this->container['ProgramId'] = isset($data['ProgramId']) ? $data['ProgramId'] : null;
        $this->container['NumDeducted'] = isset($data['NumDeducted']) ? $data['NumDeducted'] : null;
        $this->container['Id'] = isset($data['Id']) ? $data['Id'] : null;
        $this->container['Name'] = isset($data['Name']) ? $data['Name'] : null;
        $this->container['Active'] = isset($data['Active']) ? $data['Active'] : null;
        $this->container['Capacity'] = isset($data['Capacity']) ? $data['Capacity'] : null;
        $this->container['ResourceRequired'] = isset($data['ResourceRequired']) ? $data['ResourceRequired'] : null;
        $this->container['Category'] = isset($data['Category']) ? $data['Category'] : null;
        $this->container['Subcategory'] = isset($data['Subcategory']) ? $data['Subcategory'] : null;
        $this->container['OnlineDescription'] = isset($data['OnlineDescription']) ? $data['OnlineDescription'] : null;
        $this->container['AvailableForAddOn'] = isset($data['AvailableForAddOn']) ? $data['AvailableForAddOn'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = parent::listInvalidProperties();

        $allowedValues = $this->getTypeAllowableValues();
        if (!is_null($this->container['Type']) && !in_array($this->container['Type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'Type', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }


    /**
     * Gets Type
     *
     * @return string
     */
    public function getType(): string
    {
        return $this->container['Type'];
    }

    /**
     * Sets Type
     *
     * @param string $Type Type
     *
     * @return $this
     */


    public function setType(string $Type): static
    {
        $allowedValues = $this->getTypeAllowableValues();
        if (!is_null($Type) && !in_array($Type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'Type', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['Type'] = $Type;

        return $this;
    }

    /**
     * Gets DefaultTimeLength
     *
     * @return int
     */
    public function getDefaultTimeLength(): int
    {
        return $this->container['DefaultTimeLength'];
    }

    /**
     * Sets DefaultTimeLength
     *
     * @param int $DefaultTimeLength DefaultTimeLength
     *
     * @return $this
     */


    public function setDefaultTimeLength(int $DefaultTimeLength): static
    {
        $this->container['DefaultTimeLength'] = $DefaultTimeLength;

        return $this;
    }

    /**
     * Gets StaffTimeLength
     *
     * @return int
     */
    public function getStaffTimeLength(): int
    {
        return $this->container['StaffTimeLength'];
    }

    /**
     * Sets StaffTimeLength
     *
     * @param int $StaffTimeLength StaffTimeLength
     *
     * @return $this
     */


    public function setStaffTimeLength(int $StaffTimeLength): static
    {
        $this->container['StaffTimeLength'] = $StaffTimeLength;

        return $this;
    }

    /**
     * Gets ProgramId
     *
     * @return int
     */
    public function getProgramId(): int
    {
        return $this->container['ProgramId'];
    }

    /**
     * Sets ProgramId
     *
     * @param int $ProgramId ProgramId
     *
     * @return $this
     */


    public function setProgramId(int $ProgramId): static
    {
        $this->container['ProgramId'] = $ProgramId;

        return $this;
    }

    /**
     * Gets NumDeducted
     *
     * @return int
     */
    public function getNumDeducted(): int
    {
        return $this->container['NumDeducted'];
    }

    /**
     * Sets NumDeducted
     *
     * @param int $NumDeducted NumDeducted
     *
     * @return $this
     */


    public function setNumDeducted(int $NumDeducted): static
    {
        $this->container['NumDeducted'] = $NumDeducted;

        return $this;
    }

    /**
     * Gets Id
     *
     * @return int
     */
    public function getId(): int
    {
        return $this->container['Id'];
    }

    /**
     * Sets Id
     *
     * @param int $Id Id
     *
     * @return $this
     */


    public function setId(int $Id): static
    {
        $this->container['Id'] = $Id;

        return $this;
    }

    /**
     * Gets Name
     *
     * @return string
     */
    public function getName(): string
    {
        return $this->container['Name'];
    }

    /**
     * Sets Name
     *
     * @param string $Name Name
     *
     * @return $this
     */


    public function setName(string $Name): static
    {
        $this->container['Name'] = $Name;

        return $this;
    }

    /**
     * Gets Active
     *
     * @return bool
     */
    public function getActive(): bool
    {
        return $this->container['Active'];
    }

    /**
     * Sets Active
     *
     * @param bool $Active Active
     *
     * @return $this
     */


    public function setActive(bool $Active): static
    {
        $this->container['Active'] = $Active;

        return $this;
    }

    /**
     * Gets Capacity
     *
     * @return int
     */
    public function getCapacity(): int
    {
        return $this->container['Capacity'];
    }

    /**
     * Sets Capacity
     *
     * @param int $Capacity Capacity
     *
     * @return $this
     */


    public function setCapacity(int $Capacity): static
    {
        $this->container['Capacity'] = $Capacity;

        return $this;
    }

    /**
     * Gets ResourceRequired
     *
     * @return bool
     */
    public function getResourceRequired(): bool
    {
        return $this->container['ResourceRequired'];
    }

    /**
     * Sets ResourceRequired
     *
     * @param bool $ResourceRequired ResourceRequired
     *
     * @return $this
     */


    public function setResourceRequired(bool $ResourceRequired): static
    {
        $this->container['ResourceRequired'] = $ResourceRequired;

        return $this;
    }

    /**
     * Gets Category
     *
     * @return \Nlocascio\Mindbody\Model\ServiceTag
     */
    public function getCategory(): \Nlocascio\Mindbody\Model\ServiceTag
    {
        return $this->container['Category'];
    }

    /**
     * Sets Category
     *
     * @param \Nlocascio\Mindbody\Model\ServiceTag $Category Category
     *
     * @return $this
     */


    public function setCategory(\Nlocascio\Mindbody\Model\ServiceTag $Category): static
    {
        $this->container['Category'] = $Category;

        return $this;
    }

    /**
     * Gets Subcategory
     *
     * @return \Nlocascio\Mindbody\Model\ServiceTag
     */
    public function getSubcategory(): \Nlocascio\Mindbody\Model\ServiceTag
    {
        return $this->container['Subcategory'];
    }

    /**
     * Sets Subcategory
     *
     * @param \Nlocascio\Mindbody\Model\ServiceTag $Subcategory Subcategory
     *
     * @return $this
     */


    public function setSubcategory(\Nlocascio\Mindbody\Model\ServiceTag $Subcategory): static
    {
        $this->container['Subcategory'] = $Subcategory;

        return $this;
    }

    /**
     * Gets OnlineDescription
     *
     * @return string
     */
    public function getOnlineDescription(): string
    {
        return $this->container['OnlineDescription'];
    }

    /**
     * Sets OnlineDescription
     *
     * @param string $OnlineDescription OnlineDescription
     *
     * @return $this
     */


    public function setOnlineDescription(string $OnlineDescription): static
    {
        $this->container['OnlineDescription'] = $OnlineDescription;

        return $this;
    }

    /**
     * Gets AvailableForAddOn
     *
     * @return bool
     */
    public function getAvailableForAddOn(): bool
    {
        return $this->container['AvailableForAddOn'];
    }

    /**
     * Sets AvailableForAddOn
     *
     * @param bool $AvailableForAddOn AvailableForAddOn
     *
     * @return $this
     */


    public function setAvailableForAddOn(bool $AvailableForAddOn): static
    {
        $this->container['AvailableForAddOn'] = $AvailableForAddOn;

        return $this;
    }
    
}


