<?php
/**
 * UpdateClientVisitRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.23
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Nlocascio\Mindbody\Model;

/**
 * UpdateClientVisitRequest Class Doc Comment
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UpdateClientVisitRequest extends BaseModel
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'UpdateClientVisitRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'VisitId' => 'int',
        'Makeup' => 'bool',
        'SignedIn' => 'bool',
        'Execute' => 'string',
        'Test' => 'bool',
        'SendEmail' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'VisitId' => 'int32',
        'Makeup' => null,
        'SignedIn' => null,
        'Execute' => null,
        'Test' => null,
        'SendEmail' => null
    ];


    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'VisitId' => 'VisitId',
        'Makeup' => 'Makeup',
        'SignedIn' => 'SignedIn',
        'Execute' => 'Execute',
        'Test' => 'Test',
        'SendEmail' => 'SendEmail'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'VisitId' => 'setVisitId',
        'Makeup' => 'setMakeup',
        'SignedIn' => 'setSignedIn',
        'Execute' => 'setExecute',
        'Test' => 'setTest',
        'SendEmail' => 'setSendEmail'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'VisitId' => 'getVisitId',
        'Makeup' => 'getMakeup',
        'SignedIn' => 'getSignedIn',
        'Execute' => 'getExecute',
        'Test' => 'getTest',
        'SendEmail' => 'getSendEmail'
    ];


    

    

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['VisitId'] = isset($data['VisitId']) ? $data['VisitId'] : null;
        $this->container['Makeup'] = isset($data['Makeup']) ? $data['Makeup'] : null;
        $this->container['SignedIn'] = isset($data['SignedIn']) ? $data['SignedIn'] : null;
        $this->container['Execute'] = isset($data['Execute']) ? $data['Execute'] : null;
        $this->container['Test'] = isset($data['Test']) ? $data['Test'] : null;
        $this->container['SendEmail'] = isset($data['SendEmail']) ? $data['SendEmail'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = parent::listInvalidProperties();

        if ($this->container['VisitId'] === null) {
            $invalidProperties[] = "'VisitId' can't be null";
        }
        return $invalidProperties;
    }


    /**
     * Gets VisitId
     *
     * @return int
     */
    public function getVisitId()
    {
        return $this->container['VisitId'];
    }

    /**
     * Sets VisitId
     *
     * @param int $VisitId The ID of the visit to be updated.
     *
     * @return $this
     */
    public function setVisitId($VisitId): self
    {
        $this->container['VisitId'] = $VisitId;

        return $this;
    }

    /**
     * Gets Makeup
     *
     * @return bool
     */
    public function getMakeup()
    {
        return $this->container['Makeup'];
    }

    /**
     * Sets Makeup
     *
     * @param bool $Makeup When `true`, indicates that the visit is eligible to be made up.
     *
     * @return $this
     */
    public function setMakeup($Makeup): self
    {
        $this->container['Makeup'] = $Makeup;

        return $this;
    }

    /**
     * Gets SignedIn
     *
     * @return bool
     */
    public function getSignedIn()
    {
        return $this->container['SignedIn'];
    }

    /**
     * Sets SignedIn
     *
     * @param bool $SignedIn When `true`, indicates that the client has signed in for the visit.
     *
     * @return $this
     */
    public function setSignedIn($SignedIn): self
    {
        $this->container['SignedIn'] = $SignedIn;

        return $this;
    }

    /**
     * Gets Execute
     *
     * @return string
     */
    public function getExecute()
    {
        return $this->container['Execute'];
    }

    /**
     * Sets Execute
     *
     * @param string $Execute The execute code used to update this visit. Possible values are:  * Cancel  * Latecancel  * Unlatecancel
     *
     * @return $this
     */
    public function setExecute($Execute): self
    {
        $this->container['Execute'] = $Execute;

        return $this;
    }

    /**
     * Gets Test
     *
     * @return bool
     */
    public function getTest()
    {
        return $this->container['Test'];
    }

    /**
     * Sets Test
     *
     * @param bool $Test When `true`, indicates that test mode is enabled. When test mode is enabled, input information is validated, but not committed.<br />  Default: **false**
     *
     * @return $this
     */
    public function setTest($Test): self
    {
        $this->container['Test'] = $Test;

        return $this;
    }

    /**
     * Gets SendEmail
     *
     * @return bool
     */
    public function getSendEmail()
    {
        return $this->container['SendEmail'];
    }

    /**
     * Sets SendEmail
     *
     * @param bool $SendEmail When `true`, indicates that the client should be sent an email for cancellations. Note that email is not sent unless the client has an email address and automatic emails have been set up correctly.<br />  Default: **false**
     *
     * @return $this
     */
    public function setSendEmail($SendEmail): self
    {
        $this->container['SendEmail'] = $SendEmail;

        return $this;
    }
    
}


