<?php
/**
 * UpdateClientRewardsRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.50
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Nlocascio\Mindbody\Model;

/**
 * UpdateClientRewardsRequest Class Doc Comment
 *
 * @category Class
 * @description Request object for using the API to Earn or Redeem reward points
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 * @property string $ClientId The ID of the client that is getting rewards earned or redeemed.
 * @property int $Points The amount of points the client is getting earned or redeemed, must be a positive number.
 * @property string $Source If Action passed as **Earned**,    possible values are:  * Appointment Booking  * Class Booking  * Referral  * Sale    <br />Omit if Action passed as **Redeemed**.
 * @property int $SourceId The unique identifier in the MINDBODY system for the **Source**. If Action is **Earned**, and an optional SourceID is provided, it is validated as follows:     * If Source is Appointment Booking, then a provided SourceID must be a valid Visit.AppointmentId for the indicated Client.  * If Source is **Class Booking**, then a provided SourceID must be a valid Visit.Id for the indicated client.  * If Source is **Sale**, then a provided SourceID must be a valid Sale.Id for the indicated client.   * If Source is **Referral**, then a provided SourceID must be a valid Client.Id (RelatedClientId) and have been referred by the indicated client (ClientRelationship.Id = -1).  If Action is **Redeemed**, and an optional SourceID is provided, then SourceID must be a valid Sale.Id for the indicated client, and refers to the sale where the indicated points were redeemed.
 * @property string $Action Indicates if rewards are getting earned or redeemed.     Possible values are:  *Earned  *Redeemed
 * @property \DateTime $ActionDateTime The date and time when the points were earned or redeemed in UTC format. This date may be in the past, however it may not be in the future.  Default: **current date/time**
 *
 */
class UpdateClientRewardsRequest extends BaseModel
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'UpdateClientRewardsRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'ClientId' => 'string',
        'Points' => 'int',
        'Source' => 'string',
        'SourceId' => 'int',
        'Action' => 'string',
        'ActionDateTime' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static $swaggerFormats = [
        'ClientId' => null,
        'Points' => 'int64',
        'Source' => null,
        'SourceId' => 'int64',
        'Action' => null,
        'ActionDateTime' => 'date-time'
    ];


    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'ClientId' => 'ClientId',
        'Points' => 'Points',
        'Source' => 'Source',
        'SourceId' => 'SourceId',
        'Action' => 'Action',
        'ActionDateTime' => 'ActionDateTime'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'ClientId' => 'setClientId',
        'Points' => 'setPoints',
        'Source' => 'setSource',
        'SourceId' => 'setSourceId',
        'Action' => 'setAction',
        'ActionDateTime' => 'setActionDateTime'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'ClientId' => 'getClientId',
        'Points' => 'getPoints',
        'Source' => 'getSource',
        'SourceId' => 'getSourceId',
        'Action' => 'getAction',
        'ActionDateTime' => 'getActionDateTime'
    ];


    

    

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['ClientId'] = isset($data['ClientId']) ? $data['ClientId'] : null;
        $this->container['Points'] = isset($data['Points']) ? $data['Points'] : null;
        $this->container['Source'] = isset($data['Source']) ? $data['Source'] : null;
        $this->container['SourceId'] = isset($data['SourceId']) ? $data['SourceId'] : null;
        $this->container['Action'] = isset($data['Action']) ? $data['Action'] : null;
        $this->container['ActionDateTime'] = isset($data['ActionDateTime']) ? $data['ActionDateTime'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = parent::listInvalidProperties();

        if ($this->container['ClientId'] === null) {
            $invalidProperties[] = "'ClientId' can't be null";
        }
        if ($this->container['Points'] === null) {
            $invalidProperties[] = "'Points' can't be null";
        }
        if (($this->container['Points'] < 1)) {
            $invalidProperties[] = "invalid value for 'Points', must be bigger than or equal to 1.";
        }

        if ($this->container['Action'] === null) {
            $invalidProperties[] = "'Action' can't be null";
        }
        return $invalidProperties;
    }


    /**
     * Gets ClientId
     *
     * @return string
     */
    public function getClientId()
    {
        return $this->container['ClientId'];
    }

    /**
     * Sets ClientId
     *
     * @param string $ClientId The ID of the client that is getting rewards earned or redeemed.
     *
     * @return $this
     */
    public function setClientId($ClientId): self
    {
        $this->container['ClientId'] = $ClientId;

        return $this;
    }

    /**
     * Gets Points
     *
     * @return int
     */
    public function getPoints()
    {
        return $this->container['Points'];
    }

    /**
     * Sets Points
     *
     * @param int $Points The amount of points the client is getting earned or redeemed, must be a positive number.
     *
     * @return $this
     */
    public function setPoints($Points): self
    {

        if (($Points < 1)) {
            throw new \InvalidArgumentException('invalid value for $Points when calling UpdateClientRewardsRequest., must be bigger than or equal to 1.');
        }

        $this->container['Points'] = $Points;

        return $this;
    }

    /**
     * Gets Source
     *
     * @return string
     */
    public function getSource()
    {
        return $this->container['Source'];
    }

    /**
     * Sets Source
     *
     * @param string $Source If Action passed as **Earned**,    possible values are:  * Appointment Booking  * Class Booking  * Referral  * Sale    <br />Omit if Action passed as **Redeemed**.
     *
     * @return $this
     */
    public function setSource($Source): self
    {
        $this->container['Source'] = $Source;

        return $this;
    }

    /**
     * Gets SourceId
     *
     * @return int
     */
    public function getSourceId()
    {
        return $this->container['SourceId'];
    }

    /**
     * Sets SourceId
     *
     * @param int $SourceId The unique identifier in the MINDBODY system for the **Source**. If Action is **Earned**, and an optional SourceID is provided, it is validated as follows:     * If Source is Appointment Booking, then a provided SourceID must be a valid Visit.AppointmentId for the indicated Client.  * If Source is **Class Booking**, then a provided SourceID must be a valid Visit.Id for the indicated client.  * If Source is **Sale**, then a provided SourceID must be a valid Sale.Id for the indicated client.   * If Source is **Referral**, then a provided SourceID must be a valid Client.Id (RelatedClientId) and have been referred by the indicated client (ClientRelationship.Id = -1).  If Action is **Redeemed**, and an optional SourceID is provided, then SourceID must be a valid Sale.Id for the indicated client, and refers to the sale where the indicated points were redeemed.
     *
     * @return $this
     */
    public function setSourceId($SourceId): self
    {
        $this->container['SourceId'] = $SourceId;

        return $this;
    }

    /**
     * Gets Action
     *
     * @return string
     */
    public function getAction()
    {
        return $this->container['Action'];
    }

    /**
     * Sets Action
     *
     * @param string $Action Indicates if rewards are getting earned or redeemed.     Possible values are:  *Earned  *Redeemed
     *
     * @return $this
     */
    public function setAction($Action): self
    {
        $this->container['Action'] = $Action;

        return $this;
    }

    /**
     * Gets ActionDateTime
     *
     * @return \DateTime
     */
    public function getActionDateTime()
    {
        return $this->container['ActionDateTime'];
    }

    /**
     * Sets ActionDateTime
     *
     * @param \DateTime $ActionDateTime The date and time when the points were earned or redeemed in UTC format. This date may be in the past, however it may not be in the future.  Default: **current date/time**
     *
     * @return $this
     */
    public function setActionDateTime($ActionDateTime): self
    {
        $this->container['ActionDateTime'] = $ActionDateTime;

        return $this;
    }
    
}


