<?php
/**
 * UploadClientPhotoRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.23
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Nlocascio\Mindbody\Model;

/**
 * UploadClientPhotoRequest Class Doc Comment
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UploadClientPhotoRequest extends BaseModel
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'UploadClientPhotoRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'Bytes' => 'string',
        'ClientId' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'Bytes' => 'byte',
        'ClientId' => null
    ];


    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'Bytes' => 'Bytes',
        'ClientId' => 'ClientId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'Bytes' => 'setBytes',
        'ClientId' => 'setClientId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'Bytes' => 'getBytes',
        'ClientId' => 'getClientId'
    ];


    

    

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['Bytes'] = isset($data['Bytes']) ? $data['Bytes'] : null;
        $this->container['ClientId'] = isset($data['ClientId']) ? $data['ClientId'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = parent::listInvalidProperties();

        if ($this->container['Bytes'] === null) {
            $invalidProperties[] = "'Bytes' can't be null";
        }
        if (!preg_match("/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/", $this->container['Bytes'])) {
            $invalidProperties[] = "invalid value for 'Bytes', must be conform to the pattern /^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/.";
        }

        if ($this->container['ClientId'] === null) {
            $invalidProperties[] = "'ClientId' can't be null";
        }
        return $invalidProperties;
    }


    /**
     * Gets Bytes
     *
     * @return string
     */
    public function getBytes(): string
    {
        return $this->container['Bytes'];
    }

    /**
     * Sets Bytes
     *
     * @param string $Bytes A Base64-encoded string representation of the image’s byte array.
     *
     * @return $this
     */
    public function setBytes($Bytes): self
    {

        if ((!preg_match("/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/", $Bytes))) {
            throw new \InvalidArgumentException("invalid value for $Bytes when calling UploadClientPhotoRequest., must conform to the pattern /^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/.");
        }

        $this->container['Bytes'] = $Bytes;

        return $this;
    }

    /**
     * Gets ClientId
     *
     * @return string
     */
    public function getClientId(): string
    {
        return $this->container['ClientId'];
    }

    /**
     * Sets ClientId
     *
     * @param string $ClientId The RSSID of the client for whom the photo is to be uploaded.
     *
     * @return $this
     */
    public function setClientId($ClientId): self
    {
        $this->container['ClientId'] = $ClientId;

        return $this;
    }
    
}


