<?php
/**
 * ModelInterface
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nlocascio\Mindbody\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.23
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Nlocascio\Mindbody\Api;

use GuzzleHttp\ClientInterface;
use Nlocascio\Mindbody\Configuration;
use Nlocascio\Mindbody\HeaderSelector;

/**
 * Interface abstracting Api access.
 *
 * @package Nlocascio\Mindbody\Api
 * @author  Swagger Codegen team
 */
interface ApiInterface
{
  public function __construct(
    ClientInterface $client = null,
    Configuration $config = null,
    HeaderSelector $selector = null
  );

/**
 * get the Configuration
 *
 * @return Configuration
 */
  public function getConfig(): Configuration;

}
