<?php
/**
 * PublicApi
 * PHP version 5
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.28
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Nlocascio\Mindbody\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Utils;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Nlocascio\Mindbody\ApiException;
use Nlocascio\Mindbody\Configuration;
use Nlocascio\Mindbody\HeaderSelector;
use Nlocascio\Mindbody\ObjectSerializer;

/**
 * PublicApi Class Doc Comment
 *
 * @category Class
 * @package  Nlocascio\Mindbody
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PublicApi implements ApiInterface
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * Operation staffGetSalesReps
     *
     * @param  bool $RequestActiveOnly When &#x60;true&#x60;, will return only active reps data.  Default : **false** (optional)
     * @param  int $RequestLimit Number of results to include, defaults to 100 (optional)
     * @param  int $RequestOffset Page offset, defaults to 0. (optional)
     * @param  int[] $RequestSalesRepNumbers This is the list of the sales rep numbers for which the salesrep data will be fetched. (optional)
     *
     * @throws \Nlocascio\Mindbody\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Nlocascio\Mindbody\Model\GetSalesRepsResponse
     */
    public function staffGetSalesReps($RequestActiveOnly = null, $RequestLimit = null, $RequestOffset = null, $RequestSalesRepNumbers = null): \Nlocascio\Mindbody\Model\GetSalesRepsResponse
    {
        list($response) = $this->staffGetSalesRepsWithHttpInfo($RequestActiveOnly, $RequestLimit, $RequestOffset, $RequestSalesRepNumbers);
        return $response;
    }

    /**
     * Operation staffGetSalesRepsWithHttpInfo
     *
     * @param  bool $RequestActiveOnly When &#x60;true&#x60;, will return only active reps data.  Default : **false** (optional)
     * @param  int $RequestLimit Number of results to include, defaults to 100 (optional)
     * @param  int $RequestOffset Page offset, defaults to 0. (optional)
     * @param  int[] $RequestSalesRepNumbers This is the list of the sales rep numbers for which the salesrep data will be fetched. (optional)
     *
     * @throws \Nlocascio\Mindbody\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Nlocascio\Mindbody\Model\GetSalesRepsResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function staffGetSalesRepsWithHttpInfo($RequestActiveOnly = null, $RequestLimit = null, $RequestOffset = null, $RequestSalesRepNumbers = null): array
    {
        $returnType = '\Nlocascio\Mindbody\Model\GetSalesRepsResponse';
        $request = $this->staffGetSalesRepsRequest($RequestActiveOnly, $RequestLimit, $RequestOffset, $RequestSalesRepNumbers);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Nlocascio\Mindbody\Model\GetSalesRepsResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation staffGetSalesRepsAsync
     *
     * 
     *
     * @param  bool $RequestActiveOnly When &#x60;true&#x60;, will return only active reps data.  Default : **false** (optional)
     * @param  int $RequestLimit Number of results to include, defaults to 100 (optional)
     * @param  int $RequestOffset Page offset, defaults to 0. (optional)
     * @param  int[] $RequestSalesRepNumbers This is the list of the sales rep numbers for which the salesrep data will be fetched. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function staffGetSalesRepsAsync($RequestActiveOnly = null, $RequestLimit = null, $RequestOffset = null, $RequestSalesRepNumbers = null): \GuzzleHttp\Promise\PromiseInterface
    {
        return $this->staffGetSalesRepsAsyncWithHttpInfo($RequestActiveOnly, $RequestLimit, $RequestOffset, $RequestSalesRepNumbers)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation staffGetSalesRepsAsyncWithHttpInfo
     *
     * 
     *
     * @param  bool $RequestActiveOnly When &#x60;true&#x60;, will return only active reps data.  Default : **false** (optional)
     * @param  int $RequestLimit Number of results to include, defaults to 100 (optional)
     * @param  int $RequestOffset Page offset, defaults to 0. (optional)
     * @param  int[] $RequestSalesRepNumbers This is the list of the sales rep numbers for which the salesrep data will be fetched. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function staffGetSalesRepsAsyncWithHttpInfo($RequestActiveOnly = null, $RequestLimit = null, $RequestOffset = null, $RequestSalesRepNumbers = null): \GuzzleHttp\Promise\PromiseInterface
    {
        $returnType = '\Nlocascio\Mindbody\Model\GetSalesRepsResponse';
        $request = $this->staffGetSalesRepsRequest($RequestActiveOnly, $RequestLimit, $RequestOffset, $RequestSalesRepNumbers);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'staffGetSalesReps'
     *
     * @param  bool $RequestActiveOnly When &#x60;true&#x60;, will return only active reps data.  Default : **false** (optional)
     * @param  int $RequestLimit Number of results to include, defaults to 100 (optional)
     * @param  int $RequestOffset Page offset, defaults to 0. (optional)
     * @param  int[] $RequestSalesRepNumbers This is the list of the sales rep numbers for which the salesrep data will be fetched. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function staffGetSalesRepsRequest($RequestActiveOnly = null, $RequestLimit = null, $RequestOffset = null, $RequestSalesRepNumbers = null): \GuzzleHttp\Psr7\Request
    {

        $resourcePath = '/public/v6/staff/salesreps';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($RequestActiveOnly !== null) {
            $queryParams['request.activeOnly'] = ObjectSerializer::toQueryValue($RequestActiveOnly);
        }
        // query params
        if ($RequestLimit !== null) {
            $queryParams['request.limit'] = ObjectSerializer::toQueryValue($RequestLimit);
        }
        // query params
        if ($RequestOffset !== null) {
            $queryParams['request.offset'] = ObjectSerializer::toQueryValue($RequestOffset);
        }
        // query params
        if (is_array($RequestSalesRepNumbers)) {
            $queryParams['request.salesRepNumbers'] = $RequestSalesRepNumbers;
        } else
        if ($RequestSalesRepNumbers !== null) {
            $queryParams['request.salesRepNumbers'] = ObjectSerializer::toQueryValue($RequestSalesRepNumbers);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json', 'application/xml', 'text/xml', 'multipart/form-data']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json', 'application/xml', 'text/xml', 'multipart/form-data'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = Utils::jsonEncode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = Utils::jsonEncode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('API-Key');
        if ($apiKey !== null) {
            $headers['API-Key'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('authorization');
        if ($apiKey !== null) {
            $headers['authorization'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('siteId');
        if ($apiKey !== null) {
            $headers['siteId'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
